### PR TITLE
jinja : fix quadratic cost in gather_string_parts

### LINKED ISSUE #26974: Misc. bug: chat-template rendering is O(N²) in emitted parts (gather_string_parts)
### Name and Version

version: 10252 (fe2adf0)
built with Clang 21.1.8 for Linux x86_64

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
// Plese check the problem description

cmake -B build-clean -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
      -DLLAMA_CURL=OFF -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_EXAMPLES=OFF \
      -DLLAMA_BUILD_SERVER=OFF -DLLAMA_BUILD_TOOLS=OFF
cmake --build build-clean --target llama-common -j
```

### Problem description & steps to reproduce

Note: The defect is in common/jinja/ (gather_string_parts), which is shared by all tools that render chat templates. **llama-server is the one where the collection sizes come from the request, so it is the only one where it is reachable at meaningful scale.**

# `gather_string_parts` merges string parts in O(N²); chat-template rendering collapses as tool count grows

### Summary

`jinja::runtime::gather_string_parts` (`common/jinja/runtime.h`) merges adjacent string parts by calling `vector::erase` inside a loop. Each erase shifts every following element, so an O(N) merge costs O(N²). Under callgrind this one loop accounts for **57% of all instructions** executed during a chat-template render.

The visible effect is that render time explodes with the size of the collections a template
iterates — most commonly `tools`. With the bundled
`CohereForAI-c4ai-command-r-plus-tool_use.jinja`, unmodified:

| tools | properties per tool | seconds | with the patch below |
|---:|---:|---:|---:|
| 5 | 5 | 0.031 | — |
| 20 | 10 | 0.177 | — |
| 20 | 20 | 0.434 | **0.222** |
| 40 | 30 | 2.425 | 0.649 |
| 50 | 50 | 9.295 | **1.453** |
| 100 | 100 | 128.5 | **6.923** |

20–40 tools is an ordinary agentic setup, and it already costs half a second to two seconds of CPU per request before a single token is generated. The larger sizes are included to show where the curve goes, not because anyone sends them.

The patch produces **byte-identical prompts** at every size tested (26,521 / 149,971 / 587,721 bytes).

### The cause

```cpp
// common/jinja/runtime.h
static value_string gather_string_parts(const value & val) {
    value_string parts = mk_val<value_string>();
    gather_string_parts_recursive(val, parts);
    // join consecutive parts with the same type
    auto & p = parts->val_str.parts;
    for (size_t i = 1; i < p.size(); ) {
        if (p[i].is_input == p[i - 1].is_input) {
            p[i - 1].val += p[i].val;
            p.erase(p.begin() + i);      // <-- O(N) shift, inside the loop
        } else {
            i++;
        }
    }
    return parts;
}
```

`jinja::string` is a `std::vector<string_part>`. A render that emits N pieces produces N parts, nearly all carrying the same `is_input` flag, so nearly every iteration erases, each erase memmoves the tail. N merges cost O(N²) element moves.

callgrind, 20 tools × 20 properties:

```
54.31%  < caller: jinja::runtime::gather_string_parts        (15,460 calls)
36.39%    std::vector<jinja::string_part>::_M_erase          (35,121,435 calls)
20.84%    __memcpy_avx_unaligned_erms                        (the shifting)
```

`gather_string_parts` is also called 15,460 times for this one render, each call re-running the merge over the parts accumulated so far.

### Suggested patch

A single in-place compaction pass, O(N):

```cpp
// join consecutive parts with the same type (single in-place pass)
auto & p = parts->val_str.parts;
if (!p.empty()) {
    size_t w = 0;
    for (size_t r = 1; r < p.size(); r++) {
        if (p[w].is_input == p[r].is_input) {
            p[w].val += p[r].val;
        } else if (++w != r) {
            p[w] = std::move(p[r]);
        }
    }
    p.resize(w + 1);
}
```

The `++w != r` guard matters: without it the move degenerates into self-move-assignment whenever no merge has happened yet, and a self-moved `std::string` is left in an unspecified state. 
Our first attempt omitted it and silently lost 39 bytes of prompt, caught only because the reproduction below prints the rendered length.

The project's own tests pass with it applied: **`test-jinja`, `test-chat-template`, `test-chat-auto-parser` and `test-chat-peg-parser` all pass**. (`test-chat` does not build in this configuration — it needs `mtmd.h`, which `-DLLAMA_BUILD_TOOLS=OFF` excludes — and fails the same way without the patch, so it is unrelated.)

### Reproduction

Needs no model weights and no GPU.

```bash
cmake -B build-clean -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
      -DLLAMA_CURL=OFF -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_EXAMPLES=OFF \
      -DLLAMA_BUILD_SERVER=OFF -DLLAMA_BUILD_TOOLS=OFF
cmake --build build-clean --target llama-common -j
# note: the target is `llama-common`; `--target common` exits 0 while building nothing

cat > poc.cpp <<'EOF'
// Cost of common_chat_templates_apply as a function of collection sizes, using a template
// shipped in models/templates/ unmodified.
#include <chrono>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>

#include <nlohmann/json.hpp>
#include "chat.h"

using json = nlohmann::ordered_json;

static std::string slurp(const char * path) {
    std::ifstream f(path);
    std::stringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

static double render(common_chat_templates * tmpls, int n_tools, int n_props,
                     size_t * out_bytes, const char ** out_status) {
    common_chat_templates_inputs in;
    common_chat_msg msg;
    msg.role    = "user";
    msg.content = "hi";
    in.messages              = {msg};
    in.use_jinja             = true;
    in.add_generation_prompt = true;

    for (int i = 0; i < n_tools; i++) {
        json props = json::object();
        for (int p = 0; p < n_props; p++) {
            props["p" + std::to_string(p)] = {{"type", "string"}, {"description", "d"}};
        }
        common_chat_tool tool;
        tool.name        = "t" + std::to_string(i);
        tool.description = "d";
        tool.parameters  = json{{"type", "object"}, {"properties", props}}.dump();
        in.tools.push_back(tool);
    }

    const auto t0 = std::chrono::steady_clock::now();
    *out_bytes  = 0;
    *out_status = "ok";
    try {
        *out_bytes = common_chat_templates_apply(tmpls, in).prompt.size();
    } catch (const std::exception & e) {
        *out_status = e.what();
    } catch (...) {
        *out_status = "unknown exception";
    }
    return std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
}

int main(int argc, char ** argv) {
    if (argc < 2) {
        printf("usage: poc <template.jinja>\n");
        return 2;
    }
    auto tmpls = common_chat_templates_init(nullptr, slurp(argv[1]));
    if (!tmpls) {
        printf("template init failed\n");
        return 1;
    }

    printf("%7s %7s %10s  %s\n", "tools", "props", "seconds", "render");
    for (auto [nt, np] : {std::pair<int,int>{5,5}, {20,10}, {20,20},
                          {40,30}, {50,50}, {100,100}}) {
        size_t bytes = 0;
        const char * status = "";
        const double dt = render(tmpls.get(), nt, np, &bytes, &status);
        // the outcome sits next to the timing, so the number cannot be mistaken for the
        // cost of throwing rather than the cost of rendering
        printf("%7d %7d %10.3f  [%s, prompt %zu bytes]\n", nt, np, dt, status, bytes);
        fflush(stdout);
    }
    return 0;
}
EOF

clang++ -std=c++17 -O2 -Icommon -Iinclude -Iggml/include -Ivendor poc.cpp \
    -Lbuild-clean/bin -lllama-common -lllama -lggml -lggml-base \
    -Wl,-rpath,build-clean/bin -o poc

# the rpath is relative, so run from the repository root
./poc models/templates/CohereForAI-c4ai-command-r-plus-tool_use.jinja
```

Not specific to one template: `ByteDance-Seed-OSS.jinja` gives 92 s at 100 × 100 unpatched. **55 of the 64 templates in `models/templates/` contain nested `for` loops**, and in most of them both levels iterate caller-supplied collections — `for tool in tools` over `for param in tool.function.parameters.properties`.

### The cost tracks the number of emissions, not the number of bytes

Three controls, using `common_chat_verify_template` with `{% for i in range(N) %}<pad>{% endfor %}`:

**A — total output pinned at 256 KB, emission count varied 64×**

| emissions | bytes each | seconds |
|---:|---:|---:|
| 256 | 1024 | 0.116 |
| 1,024 | 256 | 0.763 |
| 4,096 | 64 | 9.544 |
| 16,384 | 16 | **141.5** |

**B — emissions pinned at 2,048, total output varied 16×**

| emissions | bytes each | seconds |
|---:|---:|---:|
| 2,048 | 32 | 2.461 |
| 2,048 | 512 | 2.873 |

**C — an empty loop body is exactly linear**

| iterations | empty body | emitting body |
|---:|---:|---:|
| 2,048 | 0.39 | 2.64 |
| 4,096 | 0.78 | 9.95 |
| 40,000 | 7.57 | — |

Producing the same 256 KB costs 0.116 s or 141.5 s depending only on how many pieces it was assembled from, 64× the emissions for 1,220× the time, while 16× the bytes at a fixed emission count costs 1.17×. The empty loop doubles exactly with N, so the iteration machinery is linear and the super-linear term is in the merge.

**What this does not say.** Cost is not a function of `tools × properties` alone: at a fixed product of 2,500 the shapes differ by 4.5× (50 × 50: 9.23 s; 1 × 2,500: 41.57 s) at the same output size, so the shape matters too. The claim here is only that the merge is quadratic in the part count.

### A separate, smaller observation

Control C also shows 40,000 iterations of an **empty** `{% for %}{% endfor %}` costing 7.57 s. That is linear, so it is not the subject
of this report, but the constant looks high and it is independent of the merge.

### Environment

llama.cpp at `fe2adf0`, `Release`, clang 21, no sanitizers, x86-64. Timings can totally vary by machine; the growth is the claim.

### First Bad Commit

_No response_

### Relevant log output

<details>
<summary>Logs</summary>

```console

```
</details>

### PR DESCRIPTION
**Pull request by Yunzez**
## Overview
Fix #26974

I made the issue and says the `vector::erase` loop in `gather_string_parts` as the cause, and says `string::append` returning by value was tested and ruled out at 4%. 

When I was fixing it I realize it is backwards. Both are quadratic, and in isolation `append` is the larger term. 

Two independent O(N^2) terms in the same function:

1. `gather_string_parts_recursive` calls `parts->val_str.append(str_val)` once per value. `string::append` ends in `return *this;` and returns `string` **by value**, so every call copies the whole accumulated parts vector. N calls over a vector growing to N.
2. The merge loop calls `vector::erase` inside the loop; each erase shifts the tail.

### Isolated cost of `gather_string_parts` (array of N one-part strings)

| N | baseline | merge fix only | append fix only | both |
|---:|---:|---:|---:|---:|
| 4,000 | 0.0682 | 0.0359 | - | 0.0002 |
| 8,000 | 0.2749 | 0.1534 | - | 0.0004 |
| 16,000 | 1.0913 | 0.5719 | - | 0.0008 |
| 32,000 | 4.3607 | 2.2778 | - | 0.0019 |
| **growth per 2x N** | **4.0** | **4.0** | **4.0** | **2.2** |

The merge fix alone halves the constant and leaves the function quadratic. Both changes are needed for it to become linear.

### End-to-end, `common_chat_templates_apply`

`models/templates/CohereForAI-c4ai-command-r-plus-tool_use.jinja`, unmodified, tools and
properties supplied the way a request supplies them:

| tools x props | baseline | merge fix only | both |
|---|---:|---:|---:|
| 5 x 5 | 0.030 | 0.029 | 0.028 |
| 20 x 20 | 0.427 | 0.221 | 0.207 |
| 40 x 30 | 2.454 | 0.663 | 0.585 |
| 50 x 50 | **9.158** | 1.440 | **1.237** |

The issue quoted 9.295 s at 50x50 on an older tree; 9.158 s here confirms it.

The end-to-end split differs from the isolated one (merge dominates here, append dominates there) because the shapes differ: the real path reaches the merge with a large parts vector built from comparatively few `append` calls.

I added the `++w != r` guard. Without it, `p[w] = std::move(p[r])` is a self-move whenever no merge has happened yet, and a self-moved `std::string` is left in an unspecified state. The first attempt at this patch omitted the guard and silently dropped 39 bytes of prompt.

### Test
I added a few regression tests for this fix, assited by Claude then reviewed manually, please remove them if this is not neccessary, I put them here to make sure my code was right, I did introduce a new dependency. :) 

`tests/test-jinja.cpp`, under `string parts`:

- *merge joins only the neighbours with the same type*: builds parts that alternate between input and template, asserts the merge produces exactly 3 parts with the right values and flags. Guards the self-move.
- *gather cost stays linear in the number of parts*: gathers an array of 4,000 then 16,000 strings, best of 5 each, asserts the 4x size costs less than 8x the time.

Measured ratios, 4x the parts:
| state | ratio | verdict |
|---|---:|---|
| no fixes | 16.13 | FAIL |
| merge fix only | 16.43 | FAIL |
| append fix only | 16.01 | FAIL |
| both fixes | ~4.2 | PASS |

Threshold 8.0 sits halfway between linear and quadratic in log terms. Ran 8 consecutive times on the patched tree with no flake. Costs about 1 ms when passing, about 1.2 s when failing.

## Requirements

- I have read and agree with the [contributing guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md)
- AI usage disclosure: Yes, Claude is assited in test generation, then manually reviewed.

### CODE REVIEW

File: common/jinja/runtime.h [hunk 1]
```diff
@@ -763,13 +763,17 @@ struct runtime {
...
-                p[i - 1].val += p[i].val;
-                p.erase(p.begin() + i);
-            } else {
-                i++;
+        if (!p.empty()) {
+            size_t w = 0;
+            for (size_t r = 1; r < p.size(); r++) {
+                if (p[w].is_input == p[r].is_input) {
+                    p[w].val += p[r].val;
+                } else if (++w != r) {
```
Comment (lexasub) [inline common/jinja/runtime.h]: ++p in if condition in current situation is strange. Hard to recognize pattern)

File: common/jinja/runtime.h [hunk 2]
```diff
@@ -763,13 +763,17 @@ struct runtime {
         gather_string_parts_recursive(val, parts);
         // join consecutive parts with the same type
         auto & p = parts->val_str.parts;
-        for (size_t i = 1; i < p.size(); ) {
-            if (p[i].is_input == p[i - 1].is_input) {
-                p[i - 1].val += p[i].val;
-                p.erase(p.begin() + i);
-            } else {
-                i++;
+        if (!p.empty()) {
```
Comment (lexasub) [inline common/jinja/runtime.h]: May be return on empty?

File: common/jinja/string.cpp [hunk 3]
```diff
@@ -103,7 +103,7 @@ void string::mark_input_based_on(const string & other) {
     }
 }
 
-string string::append(const string & other) {
+string & string::append(const string & other) {
     for (const auto & part : other.parts) {
```
Comment (lexasub) [inline common/jinja/string.cpp:107]: why changed? In your changed code result not used

File: common/jinja/runtime.h (hunk 2 above)
Comment (Yunzez) [reply common/jinja/runtime.h]: Now returns on empty :)

File: common/jinja/runtime.h (hunk 1 above)
Comment (Yunzez) [reply common/jinja/runtime.h]: Fixed,

File: common/jinja/string.cpp (hunk 3 above)
Comment (Yunzez) [reply common/jinja/string.cpp:107]: The cost is in constructing it before it is discarded: append() currently returns by value, and return *this; copies the accumulated parts vector. Since *this is an lvalue that is not a local object, the guaranteed copy-elision/NRVO/implicit-move cases don't apply. 

I could make append() return void, but its return value is still used at runtime.cpp:142 and runtime.cpp:248. 

Returning a reference removes the hot-path copy without changing those call sites, so rigth now is the smaller change.

**Review by ngxson — APPROVED** [review]

**Comment by lexasub** [comment]
@ngxson Can I ask the bot for drafts as the author of mr sometimes reviews on my own, or only when I'm sure it's ready?

**Comment by CISC** [comment]
Bot points 1 and 2 seem reasonable to change?

**Comment by ngxson** [comment]
yes, adding timing test make no sense, please remove it

**Comment by lexasub** [comment]
@Yunzez failed test on vino (jinja)

**Comment by Yunzez** [comment]
man, yeah I will remove the test, I failed my own test 😅

**Review by CISC — APPROVED** [review]
