### ISSUE TITLE
Compile bug: Cannot compile with SYCL on EndeavourOS (Arch) past b8233

### ISSUE THREAD

**Issue by strtgbb** [ggml-org/llama.cpp#20368]
### Git commit

Any past b8233

### Operating systems

Linux

### GGML backends

SYCL

### Problem description & steps to reproduce

Trying to compile a recent commit with basekit 2025.0
```sh
[ 10%] Building CXX object ggml/src/ggml-sycl/CMakeFiles/ggml-sycl.dir/im2col.cpp.o
icpx: warning: argument unused during compilation: '-Xsycl-target-backend --offload-arch=xe2' [-Wunused-command-line-argument]
In file included from llama.cpp/ggml/src/ggml-sycl/fattn.cpp:18:
llama.cpp/ggml/src/ggml-sycl/fattn-tile.hpp:2:10: fatal error: 'sycl/ext/oneapi/work_group_static.hpp' file not found
    2 | #include <sycl/ext/oneapi/work_group_static.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
Upgrading to 2025.3 allows compilation, but the resulting binary coredumps or gets stuck trying to load the model while hogging a single core on multiple tested commits.

The SYCL build guide states that Arch Linux is supported, but there is a mismatch between the recommended oneAPI versions (2025.2.1, 2025.1) and what is actually available in the Arch repos (2025.0 [extra] and 2025.3 [aur]).
Intel's website appears to be broken, it won't let me download and manually install anything older than latest.

### First Bad Commit

commit 213c4a0b81788e058c30479842954fb0815be61a (tag: b8234)

### Compile command

```shell
source /opt/intel/oneapi/setvars.sh

VER=$(git describe --tags)
rm -rf build.sycl.$VER
mkdir build.sycl.$VER

cmake -B build.sycl.$VER \
  -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx \
  -DGGML_SYCL=ON -DGGML_SYCL_TARGET=INTEL -DGGML_SYCL_DEVICE_ARCH=xe2 \
  -DGGML_NATIVE=ON -DGGML_OPENMP=ON \
  -DGGML_ONEDNN=ON -DGGML_MKL=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_C_FLAGS="-march=native -O3 -pipe" \
  -DCMAKE_CXX_FLAGS="-march=native -O3 -pipe" -DGGML_CCACHE=OFF

cmake --build build.sycl.$VER --config Release -j$(nproc)
```

### Relevant log output

```shell
2025.3 compiler throws a lot of warnings:
...
In file included from llama.cpp/common/./jinja/parser.h:4:
llama.cpp/common/./jinja/runtime.h:110:19: warning: function 'execute_impl' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
  110 |     virtual value execute_impl(context &) { throw std::runtime_error("cannot exec " + type()); }
      |                   ^
llama.cpp/common/./jinja/runtime.h:146:11: warning: function 'execute_impl' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
  146 |     value execute_impl(context &) override {
      |           ^
llama.cpp/common/./jinja/runtime.h:198:11: warning: function 'execute_impl' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
  198 |     value execute_impl(context &) override {
      |           ^
llama.cpp/common/./jinja/runtime.h:212:11: warning: function 'execute_impl' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
  212 |     value execute_impl(context &) override {
      |           ^
llama.cpp/common/./jinja/runtime.h:504:11: warning: function 'execute_impl' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
  504 |     value execute_impl(context &) override {
      |           ^
llama.cpp/common/./jinja/runtime.h:504:11: warning: function 'execute_impl' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
  504 |     value execute_impl(context &) override {
      |           ^
21 warnings generated.
[ 99%] Linking CXX executable ../../bin/llama-cli
[ 99%] Built target llama-cli
```

**Comment by strtgbb** [comment]
I forked a branch off of b2e1427c9b78a937ff2907ae3f2d998512f29c02 and dropped 213c4a0b81788e058c30479842954fb0815be61a from history. I was then able to compile with 2025.0.4 and get good performance from Qwen3.5 without it going insane like it did on b8233.

**Comment by NeoZhangJianyu** [comment]
@strtgbb 
Thank you for your feedback!
I will check the issues.

1. FA feature use the new feature of SYCL, which is not supported by old compiler, like 2025.0. I will add the check for compiler version to hint the user to upgrade oneAPI.
2. the warning of parser.h is common part code, instead of SYCL backend. It's another issue.
3. For the crash, you can disable FA by "export GGML_SYCL_ENABLE_FLASH_ATTN=0".
    It's new feature. Maybe some unknown issue.

Could you share the whole log with the cmd line?
And what's your GPU?

Thank you!

**Comment by NeoZhangJianyu** [comment]
```
-DGGML_ONEDNN=ON -DGGML_MKL=ON \
-O3
```
oneDNN and oneMKL are replaced by each other. You only need choose one.
"-O3" is not verified. For stable, recommend "-O2".

Thank you!

**Comment by strtgbb** [comment]
`export GGML_SYCL_ENABLE_FLASH_ATTN=0` doesn't seem to make a difference. I have switched to `-O2`.

[compile.log](https://github.com/user-attachments/files/25890610/compile.log)

GPU: ARC B580

The log for binaries compiled with `2025.3.2` is usually pretty short:
```sh
$ ./llama-cli -t 6 -ngl 99 -m $M/Qwen2.5-7B-Instruct-Q4_K_M.gguf -p hi -st -fa off

Loading model... |Segmentation fault         (core dumped) ./llama-cli -t 6 -ngl 99 -m $M/Qwen2.5-7B-Instruct-Q4_K_M.gguf -p hi -st -fa off
```
Github is not allowing me to attach the coredump file.

On another attempt with -v it got stuck, and I had to kill it. It was causing my display to freeze intermittently, log attached.
[stuckloading.log](https://github.com/user-attachments/files/25890305/stuckloading.log)

**Comment by NeoZhangJianyu** [comment]
Got it!
Let me check.

It shouldn't freeze the display.

**Comment by NeoZhangJianyu** [comment]
I test the latest code and it's passed on Arc 770, ubuntu 22.04.

```
wget https://huggingface.co/paultimothymooney/Qwen2.5-7B-Instruct-Q4_K_M-GGUF/resolve/main/qwen2.5-7b-instruct-q4_k_m.gguf?download=true -O qwen2.5-7b-instruct-q4_k_m.gguf

commit 00de615345c9d3ead161c15bf0cc313e46f4def6 (HEAD -> master, origin/master, origin/HEAD)
Author: Pascal <admin@serveurperso.com>
Date:   Wed Mar 11 05:31:33 2026 +0100

icpx --version
Intel(R) oneAPI DPC++/C++ Compiler 2025.3.0 (2025.3.0.20251010)

./examples/sycl/test.sh -m ../models/qwen2.5-7b-instruct-q4_k_m.gguf -mg 0
```

Could you check it?

Thank you!

**Comment by strtgbb** [comment]
```sh
$ icpx --version
Intel(R) oneAPI DPC++/C++ Compiler 2025.3.2 (2025.3.2.20260112)

$ git log -1 --oneline
00de61534 (HEAD) Fix agentic mcp image single model (#20339)

$ rm -rf build build.sycl

$ ./examples/sycl/build.sh
...

$ ./examples/sycl/test.sh -m $M/Qwen2.5-7B-Instruct-Q4_K_M.gguf -mg 0
...
main: llama threadpool init, n_threads = 6

system_info: n_threads = 6 (n_threads_batch = 6) / 12 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | BMI2 = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 | 

sampler seed: 0
sampler params: 
	repeat_last_n = 64, repeat_penalty = 1.000, frequency_penalty = 0.000, presence_penalty = 0.000
	dry_multiplier = 0.000, dry_base = 1.750, dry_allowed_length = 2, dry_penalty_last_n = -1
	top_k = 40, top_p = 0.950, min_p = 0.050, xtc_probability = 0.000, xtc_threshold = 0.100, typical_p = 1.000, top_n_sigma = -1.000, temp = 0.800
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000, adaptive_target = -1.000, adaptive_decay = 0.900
sampler chain: logits -> ?penalties -> ?dry -> ?top-n-sigma -> top-k -> ?typical -> top-p -> min-p -> ?xtc -> temp-ext -> dist 
generate: n_ctx = 4096, n_batch = 2048, n_predict = 400, n_keep = 0

Building a website can be done in 10 simple steps:
Step 1:./examples/sycl/test.sh: line 129: 1582527 Segmentation fault         (core dumped) ZES_ENABLE_SYSMAN=1 ${BIN_FILE} -m ${MODEL_FILE} -no-cnv -p "${INPUT_PROMPT}" -n 400 -e -ngl ${NGL} -s ${SEED} -c ${CONTEXT} ${GPUS_SETTING} -lv ${LOG_VERBOSE} --mmap
```

**Comment by strtgbb** [comment]
`export SYCL_CACHE_PERSISTENT=0` fixed the runtime issue.

**Comment by NeoZhangJianyu** [comment]
OK, it's good!

**Comment by strtgbb** [comment]
But if I remove the cache `rm -rf ~/.cache/libsycl_cache`, then run with `SYCL_CACHE_PERSISTENT=1`, it coredumps again. Is bad data getting into the cache?

**Comment by NeoZhangJianyu** [comment]
Use it, the JIT result will be saved to local.
It will be used to speed up next startup.

Maybe the speed of startup impact some code abnormal behavior.

In the development model, the binary file is changed. So clear the cache is necessary.
I guess the crash is due to the mixed old cache with new code.

In general, we don't set SYCL_CACHE_PERSISTENT.

**Comment by strtgbb** [comment]
Mixed old cache does not explain it, I fully deleted the cache, but the crash with SYCL_CACHE_PERSISTENT=1 still occurs.

**Comment by NeoZhangJianyu** [comment]
Could you share the call stack of the crash?
I don't use SYCL_CACHE_PERSISTENT before.

My suggestion is not use it, because it won't impact the second startup speed, or running speed in all cases.

**Comment by strtgbb** [comment]
It appears I had it enabled in my shell environment, but it is indeed disabled by default, oops. I find it strange that it causes crashes with the new compiler, but not the old compiler.

[gdb_bt.txt](https://github.com/user-attachments/files/25905304/gdb_bt.txt)
[coredump.txt](https://github.com/user-attachments/files/25905303/coredump.txt)

**Comment by NeoZhangJianyu** [comment]
The crash happened in sycl::_V1::detail::PersistentDeviceCodeCache::getItemFromDisc().
Looks like the persistent trigger this crash.

If disable it and avoid the crash, I suggest disable it as default in your system.

The function is defined by SYCL internal. I guess it's SYCL issue.

**Comment by strtgbb** [comment]
I still don't have Qwen3.5 working with SYCL unfortunately.
I compiled from b2e1427c9b78a937ff2907ae3f2d998512f29c02

It's been like this for a few minutes, disk usage is 0 and VRAM is filled, so model has loaded. But one CPU core is at 100%.
```
$ SYCL_CACHE_PERSISTENT=0 ./llama-cli -t 6 -ngl 99 -m $M/Qwen3.5-4B-Q6_K.gguf -p hi -st

Loading model... /
```

**Comment by strtgbb** [comment]
Adding `-fa off` allows me to run Qwen3.5, however, I like using `-ctk`/`-ctv`, which requires fa on.

Turns out it sort of works with fa on and quantized kv cache?
`-fa on -ctv q8_0 -ctk q8_0` runs, but now prompt processing has dropped to 0.4 t/s.

EDIT: I guess this was just JIT, subsequent runs are fine.

**Comment by NeoZhangJianyu** [comment]
OK, it's good!

Because JIT will create the binary code in first startup.
It will impact the performance of first running.
In next running, there is no JIT be triggered. The e2e performance will be increased than first.

FA is always optional. 
You could open/close it according to the test result.
