### ISSUE TITLE
Compile bug: undefined reference to `SSL_ctrl` when building with -DLLAMA_CURL=OFF

### ISSUE THREAD

**Issue by mudler** [ggml-org/llama.cpp#16285]
### Git commit

72b24d96c6888c609d562779a23787304ae4609c

### Operating systems

Linux

### GGML backends

CPU

### Problem description & steps to reproduce

Seems that when disabling -DLLAMA_CURL=OFF, we ask to link against openssl, but this is not added to ldflags

### First Bad Commit

https://github.com/ggml-org/llama.cpp/pull/16185

### Compile command

```shell
cmake .. -DBUILD_SHARED_LIBS=OFF -DLLAMA_CURL=OFF -DCPPHTTPLIB_OPENSSL_SUPPORT=OFF -DGGML_NATIVE=OFF -DGGML_AVX=on -DGGML_AV
X2=off -DGGML_AVX512=off -DGGML_FMA=off -DGGML_F16C=off -DBUILD_SHARED_LIBS=OFF -DLLAMA_CURL=OFF -DCPPHTTPLIB_OPENSSL_SUPPORT=OFF -DGGML_NATIVE=OFF -DBUILD_SHARED_LIBS=OFF -DLL
AMA_CURL=OFF -DCPPHTTPLIB_OPENSSL_SUPPORT=OFF -DGGML_NATIVE=OFF && cmake --build . --config Release -j 3
```

### Relevant log output

```shell
in function `httplib::SSLClient::process_socket(httplib::ClientImpl::Socket const&, std::chrono::time_point<std
::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::function<bool (httplib::Stream&)>)':
66.22 grpc-server.cpp:(.text._ZN7httplib9SSLClient14process_socketERKNS_10ClientImpl6SocketENSt6chrono10time_pointINS5_3_V212steady_clockENS5_8durationIlSt5ratioILl1ELl10000000
00EEEEEESt8functionIFbRNS_6StreamEEE[_ZN7httplib9SSLClient14process_socketERKNS_10ClientImpl6SocketENSt6chrono10time_pointINS5_3_V212steady_clockENS5_8durationIlSt5ratioILl1ELl1000000000EEEEEESt8functionIFbRNS_6StreamEEE]+0xaa): undefined reference to `SSL_ctrl'                                                                                          66.22 /usr/bin/ld: CMakeFiles/grpc-server.dir/grpc-server.cpp.o: in function `httplib::SSLServer::process_and_close_socket(int)':                                               66.22 grpc-server.cpp:(.text._ZN7httplib9SSLServer24process_and_close_socketEi[_ZN7httplib9SSLServer24process_and_close_socketEi]+0x6b5): undefined reference to `SSL_ctrl'
66.56 collect2: error: ld returned 1 exit status
```

**Comment by angt** [comment]
It’s not clear why your build fails, but adding an `LLAMA_OPENSSL` option makes sense in any case.
You can try it with the following commands:

```
git clone https://github.com/angt/llama.cpp -b add-llama_openssl-option llama.cpp-test
cd llama.cpp-test
cmake -B build -DLLAMA_CURL=OFF -DLLAMA_OPENSSL=OFF
cmake --build build --target llama-server -j$(nproc)
```

**Comment by mudler** [comment]
> It’s not clear why your build fails, but adding an `LLAMA_OPENSSL` option makes sense in any case. You can try it with the following commands:

The problem seems to be because with https://github.com/ggml-org/llama.cpp/pull/16185, now disabling LLAMA_CURL automatically includes the `cpp-httplib`, which links against OpenSSL (full logs https://github.com/mudler/LocalAI/actions/runs/18049973134/job/51369786284 ) . From the PR it looks like it should have been added as link target both ssl and crypto (as cpp-httplib depends on) which eventually worked out when adding it explicitly to my Cmakefile: https://github.com/mudler/LocalAI/pull/6349/commits/33a34ec3fb821679e37b40bc6becf8287888dcec

> 
> ```
> git clone https://github.com/angt/llama.cpp -b add-llama_openssl-option llama.cpp-test
> cd llama.cpp-test
> cmake -B build -DLLAMA_CURL=OFF -DLLAMA_OPENSSL=OFF
> cmake --build build --target llama-server -j$(nproc)
> ```

Going to try and report, but I suspect we should also be explicit in linking ssl when cpp-httplib is selected, which I'm not sure if it's done somewhere else and I'm doing something wrong in my Cmakefile to not inherit that.

**Comment by angt** [comment]
If `CPPHTTPLIB_OPENSSL_SUPPORT` is not defined, `cpp-httplib` does not use OpenSSL, so linking against ssl or crypto should not be necessary. 🤔

**Comment by mudler** [comment]
Small update: master with disabling `LLAMA_OPENSSL=OFF` works ( https://github.com/mudler/LocalAI/pull/6349/commits/9a9ae1f866229f52aa7830ee99ffee9b93b1d6a1 )

> If CPPHTTPLIB_OPENSSL_SUPPORT is not defined, cpp-httplib does not use OpenSSL, so linking against ssl or crypto should not be necessary. 🤔

Sorry, disregard `-DCPPHTTPLIB_OPENSSL_SUPPORT=OFF` from my report, it didn't basically had really any effect (tried with both).
