### PR TITLE
convert : add split() to LoraTorchTensor in LoRA converter

### LINKED ISSUE #21864: Misc. bug: `convert_lora_to_gguf.py`: `LoraTorchTensor` missing `split()` method breaks GraniteMoe LoRA conversion
### Name and Version

version: b8779 (75f3bc94e)

### Operating systems

_No response_

### Which llama.cpp modules do you know to be affected?

Python/Bash scripts

### Command line

```shell

```

### Problem description & steps to reproduce

cc @gabe-l-hart  

Converting a LoRA adapter for a GraniteMoe model (e.g. `granite-4.0-micro`) fails because `LoraTorchTensor` does not implement `split()`.

`GraniteMoeModel.modify_tensors` calls `data_torch.split(ffn_dim, dim=-2)` to separate merged gate/up FFN weights (`input_linear.weight`, `shared_mlp.input_linear.weight`). During LoRA conversion these tensors are `LoraTorchTensor` objects, which implement `reshape`, `permute`, `transpose`, `__getitem__`, etc. but not `split()`. This likely affects any MoE architecture that merges gate/up projections into a single tensor.

## Steps to Reproduce

```bash
# Clone the repo (contains GraniteMoe LoRA adapters)
hf download ibm-granite/granite-lib-rag-r1.0 --local-dir ./granite-lib-rag-r1.0
cd granite-lib-rag-r1.0

# Clone llama.cpp
git clone --single-branch --branch master https://github.com/ggml-org/llama.cpp.git _ollama/llama.cpp

# Create venv and install dependencies
python3 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install huggingface_hub
pip install -r _ollama/llama.cpp/requirements/requirements-convert_lora_to_gguf.txt

# Download base model weights
hf download ibm-granite/granite-4.0-micro --local-dir _ollama/models/granite-4.0-micro

# Convert query_clarification LoRA — this triggers the error
python _ollama/llama.cpp/convert_lora_to_gguf.py \
  query_clarification/granite-4.0-micro/lora \
  --base _ollama/models/granite-4.0-micro \
  --outtype f16
```

### First Bad Commit

_No response_

### Relevant log output

<details>
<summary>Logs</summary>

```console
Traceback (most recent call last):
  File "convert_lora_to_gguf.py", line 502, in <module>
    model_instance.write()
  File "convert_hf_to_gguf.py", line 934, in write
    self.prepare_tensors()
  File "convert_hf_to_gguf.py", line 2983, in prepare_tensors
    super().prepare_tensors()
  File "convert_hf_to_gguf.py", line 794, in prepare_tensors
    for new_name, data_torch in (self.modify_tensors(data_torch, name, bid)):
  File "convert_lora_to_gguf.py", line 459, in modify_tensors
    dest = list(super().modify_tensors(data_torch, name, bid))
  File "convert_hf_to_gguf.py", line 10748, in modify_tensors
    yield from GraniteMoeModel.modify_tensors(self, data_torch, name, bid)
  File "convert_hf_to_gguf.py", line 10648, in modify_tensors
    gate, up = data_torch.split(ffn_dim, dim=-2)
AttributeError: 'LoraTorchTensor' object has no attribute 'split'
```
</details>

### PR DESCRIPTION
**Pull request by jesus-talavera-ibm**
## Overview

Add the missing `split()` method to `LoraTorchTensor` in `convert_lora_to_gguf.py`, fixing LoRA adapter conversion for models that merge gate/up FFN projections into a single tensor (GraniteMoe, Gemma 4, BailingMoe, etc.).

## Additional information

Fixes https://github.com/ggml-org/llama.cpp/issues/21864
~~Added unit tests~~ Tested manually
Ran successfully "Steps to Reproduce" from original issue

## Requirements

- I have read and agree with the [contributing guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md)
- AI usage disclosure: YES — Claude Code was used in an assistive capacity to explore the codebase and assist with the implementation and manual tests of `split()` method. The contributor designed the approach, reviewed all code, and can explain every line.

### CODE REVIEW

File: tests/test_lora_torch_tensor.py [hunk 1]
```diff
@@ -0,0 +1,167 @@
+#!/usr/bin/env python3
```
Comment (gabe-l-hart) [inline tests/test_lora_torch_tensor.py]: It's great to have some unit tests for this functionality, but that doesn't actually line up with the current project testing strategy. These conversion scripts are largely not tested in `tests`. I'm not sure if there's a better place to put this or if it's a new convention we want to establish. At a minimum, I'd think there should be a sub-folder with these conversion tests.

**Review by gabe-l-hart — CHANGES_REQUESTED** [review]
I've pulled in the changes to `convert_lora_to_gguf.py` in my branch to support Granite4 Vision as a test and they do fix the issue I'm seeing there, though I can't yet validate that the resulting tensors work as expected. Were you able to validate results with the models in https://github.com/ggml-org/llama.cpp/issues/21864?

Also, we need to figure out a strategy for the unit tests. Tagging @CISC for thoughts on how/if to support unit tests for conversion scripts.

**Comment by CISC** [comment]
> Also, we need to figure out a strategy for the unit tests. Tagging @CISC for thoughts on how/if to support unit tests for conversion scripts.

I think maybe @bartowski1182 and/or @am17an had some thoughts on this, though for this PR I think just skip the test and verify manually.

File: tests/test_lora_torch_tensor.py (hunk 1 above)
Comment (jesus-talavera-ibm) [reply tests/test_lora_torch_tensor.py]: As @CISC  commented, I will remove the tests and verify things manually.

I was only able to test that the conversion script runs without errors, but I’m not sure how to check whether the resulting tensor works as expected. Do we have a converted version that we could compare against?

Comment (jesus-talavera-ibm) [reply tests/test_lora_torch_tensor.py]: Update: I was able to do a simple end-to-end validation. Converted the LoRA adapter and ran inference on Granite 4.0 Micro with and without the adapter. 
The base model responds directly:
```
> Clarify the following query: What is the capital of France?

The capital of France is Paris.
```
while the LoRA-adapted model produces a task-specific structured output: 
```
> Clarify the following query: What is the capital of France?

{"clarification": "CLEAR"}
```
There were no tensor errors or shape mismatches during loading or inference. How exhaustive should these manual tests be?

Comment (CISC) [reply tests/test_lora_torch_tensor.py]: I think that's probably good enough.

Comment (gabe-l-hart) [reply tests/test_lora_torch_tensor.py]: Agreed, that works for me!

**Review by gabe-l-hart — APPROVED** [review]

**Comment by gabe-l-hart** [comment]
@CISC I'm good with this as is (also verified for Granite Vision on my branch). Can you release CI?

**Comment by gabe-l-hart** [comment]
@jesus-talavera-ibm Let's take this out of Draft

**Comment by bartowski1182** [comment]
I will definitely consider tests in the conversion area for future value-adds, currently my tests were limited purely to llama-quantize, but this would definitely be good coverage as well

**Review by CISC — APPROVED** [review]
