### PR TITLE
Refactor nested if causing error C1061 on MSVC.

### LINKED ISSUE #6093: Compilation fails with Cmake on Windows (since #5970): error C1061
After today's changes, I can no longer build the project with Visual Studio's Cmake. Build fails with compiler [error C1061](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1061?view=msvc-170).
It seems like there is too many nested block scopes for MSVC to handle in `common.cpp`.

```sh
$ cmake --build . --config Release -- "-m:24"
Version MSBuild 17.7.2+d6990bcfa pour .NET Framework

  build_info.vcxproj -> C:\llm\llama.cpp\build\common\build_info.dir\Release\build_info.lib
  ggml.vcxproj -> C:\llm\llama.cpp\build\ggml.dir\Release\ggml.lib
  llama.vcxproj -> C:\llm\llama.cpp\build\Release\llama.lib
  llava.vcxproj -> C:\llm\llama.cpp\build\examples\llava\llava.dir\Release\llava.lib
  gguf.vcxproj -> C:\llm\llama.cpp\build\bin\Release\gguf.exe
  quantize.vcxproj -> C:\llm\llama.cpp\build\bin\Release\quantize.exe
  ggml_static.vcxproj -> C:\llm\llama.cpp\build\Release\ggml_static.lib
  quantize-stats.vcxproj -> C:\llm\llama.cpp\build\bin\Release\quantize-stats.exe
  benchmark.vcxproj -> C:\llm\llama.cpp\build\bin\Release\benchmark.exe
  test-c.vcxproj -> C:\llm\llama.cpp\build\bin\Release\test-c.exe
  llava_static.vcxproj -> C:\llm\llama.cpp\build\examples\llava\Release\llava_static.lib
  common.cpp
C:\llm\llama.cpp\common\common.cpp(899,60): fatal  error C1061: limite du compilateur : blocs imbriqués trop profondément [C:\llm\llama.cpp\build\common\common.vcxproj]
```

using `git bisect` :
```
877b4d0c628cc70dddb5df72ed8fc14d126ca7e8 is the first bad commit
commit 877b4d0c628cc70dddb5df72ed8fc14d126ca7e8
Author: Theia Vogel <theia@vgel.me>
Date:   Fri Mar 15 13:43:02 2024 -0700

    llama : add support for control vectors (#5970)

    * control vector api and implementation

    * control-vectors : minor code style updates

    * disable control vector when data == nullptr

    use -1 for disabled range (also on init) in case we ever support controlling layer 0 (embeddings)

    ---------

    Co-authored-by: Georgi Gerganov <ggerganov@gmail.com>

 common/common.cpp | 215 ++++++++++++++++++++++++++++++++++++++++++++++++++++++
 common/common.h   |  31 +++++++-
 llama.cpp         | 128 ++++++++++++++++++++++++++++++++
 llama.h           |  23 +++++-
 4 files changed, 392 insertions(+), 5 deletions(-)
 ```

### PR DESCRIPTION
**Pull request by dranger003**
This PR refactors the nested if-else using switch-case to resolve error C1061 using MSVC.
Note: there is also a temporary workaround provided by Deacon8 here https://github.com/ggerganov/llama.cpp/pull/6096

Fixes https://github.com/ggerganov/llama.cpp/issues/6093

### CODE REVIEW

File: common/common.cpp [hunk 1]
```diff
@@ -139,6 +139,18 @@ bool gpt_params_parse(int argc, char ** argv, gpt_params & params) {
...
+    std::uint64_t hash = 0xcbf29ce484222325;
+    const std::uint64_t prime = 0x100000001b3;
+
+    for (; *input; ++input) {
+        hash ^= static_cast<std::uint64_t>(*input);
+        hash *= prime;
+    }
+
+    return hash;
+}
```
Comment (ggerganov) [inline common/common.cpp:152]: This is C++14 - we support just C++11 (https://stackoverflow.com/questions/45097171/the-body-of-constexpr-function-not-a-return-statement)

Probably, just remove the `else`s from the if-else chain - this is not performance critical code

**Review by ggerganov — APPROVED** [review]

File: common/common.cpp [hunk 2]
```diff
@@ -151,13 +151,17 @@ bool gpt_params_parse_ex(int argc, char ** argv, gpt_params & params) {
             std::replace(arg.begin(), arg.end(), '_', '-');
         }
 
+        bool arg_found = false;
```
Comment (ggerganov) [inline common/common.cpp:154]: Btw, to avoid this `arg_found` everywhere, we should move this if-chain in a `bool` function and return early on success

Comment (dranger003) [reply common/common.cpp:154]: I'll submit another PR.
