### ISSUE TITLE
Compile bug: invalid use of non-static member function ‘uint32_t llama_hparams::n_layer() const

### ISSUE THREAD

**Issue by simlay** [ggml-org/llama.cpp#24194]
### Git commit

64086f2b2f222f7032611b021b0e1b6c4767b0f1

### Operating systems

Linux

### GGML backends

CUDA

### Problem description & steps to reproduce

I pulled latest master and tried to build. I initially thought it might be https://github.com/ggml-org/llama.cpp/pull/24188, but when I tried all the commits since then, I found it to be https://github.com/ggml-org/llama.cpp/pull/23545. Perhaps a bad rebase/squash/merge?

### First Bad Commit

64086f2b2f222f7032611b021b0e1b6c4767b0f1

### Compile command

```shell
cmake -DGGML_CCACHE=OFF -B build -DGGML_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES="61" -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release -j8
```

### Relevant log output

```shell
In file included from /home/simlay/projects/llama.cpp/src/llama-model.cpp:6:
/home/simlay/projects/llama.cpp/src/llama-model.cpp: In member function ‘void llama_model::print_info() const’:
/home/simlay/projects/llama.cpp/src/llama-model.cpp:1767:36: error: invalid use of non-static member function ‘uint32_t llama_hparams::n_layer() const’
 1767 |                            hparams.n_layer).c_str());
      |                            ~~~~~~~~^~~~~~~
/home/simlay/projects/llama.cpp/src/llama-impl.h:28:71: note: in definition of macro ‘LLAMA_LOG_INFO’
   28 | #define LLAMA_LOG_INFO(...)  llama_log_internal(GGML_LOG_LEVEL_INFO , __VA_ARGS__)
      |                                                                       ^~~~~~~~~~~
In file included from /home/simlay/projects/llama.cpp/src/llama-graph.h:5,
                 from /home/simlay/projects/llama.cpp/src/llama-model.h:5,
                 from /home/simlay/projects/llama.cpp/src/llama-model.cpp:1:
/home/simlay/projects/llama.cpp/src/llama-hparams.h:342:14: note: declared here
  342 |     uint32_t n_layer() const;
      |              ^~~~~~~
```

**Comment by kiwisec** [comment]
Can confirm, both CUDA and Vulkan build. 
I also removed `build/` directory to start fresh, same result

**Comment by lennyhans** [comment]
Same here, apparently there should be a function result instead of the function it self changing this
`hparams.n_layer`
to 
`hparams.n_layer()`

And can compile

**Comment by lennyhans** [comment]
Solved by 
- https://github.com/ggml-org/llama.cpp/pull/24193
