### PR TITLE
Fixes #12823

### LINKED ISSUE #12823: Compile bug: Build failure on ppc64le from simd-mappings.h
### Git commit

995083e

### Operating systems

Linux

### GGML backends

CPU

### Problem description & steps to reproduce

While building llama.cpp on Power (ppc64le) with gcc13, seeing below errors:

llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:395:58: error: lvalue required as unary ‘&’ operand
  395 | #define GGML_ENDIAN_BYTE(i) ((unsigned char *)&(uint16_t){1})[i]
llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:395:58: error: lvalue required as unary ‘&’ operand
  395 | #define GGML_ENDIAN_BYTE(i) ((unsigned char *)&(uint16_t){1})[i]
llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:395:58: error: lvalue required as unary ‘&’ operand
  395 | #define GGML_ENDIAN_BYTE(i) ((unsigned char *)&(uint16_t){1})[i]

### First Bad Commit

_No response_

### Compile command

```shell
cmake –-build build_llama –-config Release
make
```

### Relevant log output

```shell
llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:395:58: error: lvalue required as unary ‘&’ operand
  395 | #define GGML_ENDIAN_BYTE(i) ((unsigned char *)&(uint16_t){1})[i]
llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:395:58: error: lvalue required as unary ‘&’ operand
  395 | #define GGML_ENDIAN_BYTE(i) ((unsigned char *)&(uint16_t){1})[i]
llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:395:58: error: lvalue required as unary ‘&’ operand
  395 | #define GGML_ENDIAN_BYTE(i) ((unsigned char *)&(uint16_t){1})[i]
```

### PR DESCRIPTION
**Pull request by mehendarkarprajwal**
With recent redesign of ggml-cpu we see that it was failing to compile on POWER arch on both ppcle64 and AIX. The changes in this PR is for fixing the compilation issue.

### CODE REVIEW

File: common/arg.cpp
Comment (mehendarkarprajwal) [inline common/arg.cpp:1]: This commit is already merged. Please dont take it. Apologies for the mistake.

File: ggml/src/ggml-cpu/simd-mappings.h [hunk 1]
```diff
@@ -392,7 +392,11 @@ static inline void __avx_f32cx8_store(ggml_fp16_t *x, __m256 y) {
 #define GGML_F16_VEC_LOAD(p, i) (i & 0x1) ?                   \
   vec_extract_fp32_from_shorth(vec_xl(0, p - GGML_F16_EPR)) : \
   vec_extract_fp32_from_shortl(vec_xl(0, p))
-#define GGML_ENDIAN_BYTE(i) ((unsigned char *)&(uint16_t){1})[i]
+static inline unsigned char ggml_endian_byte(int i){
```
Comment (slaren) [inline ggml/src/ggml-cpu/simd-mappings.h:395]:
```suggestion
static inline unsigned char ggml_endian_byte(int i) {
```

**Review by slaren — APPROVED** [review]

File: common/arg.cpp
Comment (mehendarkarprajwal) [inline common/arg.cpp:1]: This commit is already merged. Plz do not take it. My sincere apologies !!

File: ggml/src/ggml-cpu/simd-mappings.h (hunk 1 above)
Comment (mehendarkarprajwal) [reply ggml/src/ggml-cpu/simd-mappings.h]: Updated files according to reviewed suggestions. Thank you!!
