### ISSUE TITLE
Compile bug:

### ISSUE THREAD

**Issue by nnikolov3** [ggml-org/llama.cpp#15044]
### Git commit

niko@dev-machine ~/Dev/llama.cpp master [.venv] [14:43] $ git rev-parse HEAD
5c0eb5ef544aeefd81c303e03208f768e158d93c

### Operating systems

Linux

### GGML backends

BLAS, CUDA, CPU

### Problem description & steps to reproduce

I am not sure if this is on my end or not. 

$  export CXX=/usr/bin/clang && export CC=/usr/bin/clang && cmake -B build -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS  -DGGML_CUDA=ON -DGGML_CUDA_F16=true -DGGML_CUDA_FA_ALL_QUANT=true -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DGGML_CUDA_FA_ALL_QUANTS=true -DCMAKE_CUDA_HOST_COMPILER="/usr/bin/gcc-14"  GGML_CCACHE=OFF 
CMake Warning:
  Ignoring extra path from command line:

   "GGML_CCACHE=OFF"

-- The C compiler identification is Clang 20.1.8
-- The CXX compiler identification is Clang 20.1.8
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.50.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- ccache found, compilation results will be cached. Disable with GGML_CCACHE=OFF.
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- Found OpenMP_C: -fopenmp=libomp (found version "5.1")
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.1")
-- Found OpenMP: TRUE (found version "5.1")
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native 
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib64/libopenblas.so
-- BLAS found, Libraries: /usr/lib64/libopenblas.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.3.0")
-- Checking for module 'openblas64'
--   Package 'openblas64' not found
-- Checking for module 'openblas'
--   Package 'openblas' not found
CMake Warning at ggml/src/ggml-blas/CMakeLists.txt:58 (message):
  BLAS_INCLUDE_DIRS neither been provided nor been automatically detected by
  pkgconfig, trying to find cblas.h from possible paths...

-- BLAS found, Includes: /usr/include
-- Including BLAS backend
-- Found CUDAToolkit: /usr/local/cuda/targets/x86_64-linux/include (found version "12.9.86")
-- CUDA Toolkit found
-- Using CUDA architectures: native
-- The CUDA compiler identification is NVIDIA 12.9.86 with host compiler GNU 14.2.1
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- CUDA host compiler is GNU 14.2.1
-- Including CUDA backend
-- ggml version: 0.0.6075
-- ggml commit:  5c0eb5ef
-- Found CURL: /usr/lib64/libcurl.so (found version "8.11.1")
-- Configuring done (16.2s)
-- Generating done (0.9s)
-- Build files have been written to: /home/niko/Dev/llama.cpp/build

Error after the warning:
/home/niko/Dev/llama.cpp/src/llama-quant.cpp:643:66: warning: absolute value function 'abs' given an argument of type 'const int64_t' (aka 'const long') but has parameter of type 'int' which may cause truncation of value [-Wabsolute-value]
  643 |                 gguf_set_val_u32(ctx_out.get(), o.key, (uint32_t)abs(o.val_i64));
      |                                                                  ^
/home/niko/Dev/llama.cpp/src/llama-quant.cpp:643:66: note: use function 'std::abs' instead
  643 |                 gguf_set_val_u32(ctx_out.get(), o.key, (uint32_t)abs(o.val_i64));
      |                                                                  ^~~
      |                                                                  std::abs
1 warning generated.
/usr/bin/ld: ../src/libllama.a(llama-impl.cpp.o): in function `llama_log_internal(ggml_log_level, char const*, ...)':
llama-impl.cpp:(.text+0x188): undefined reference to `operator new[](unsigned long)'
/usr/bin/ld: llama-impl.cpp:(.text+0x1c1): undefined reference to `operator delete[](void*)'
/usr/bin/ld: ../src/libllama.a(llama-impl.cpp.o): in function `replace_all(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':   

1) OS - Fedora 42 6.15.5-200.fc42.x86_64+debug
2) Hardware 
Sat Aug  2 15:09:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 575.64.05              Driver Version: 575.64.05      CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    Off |   00000000:01:00.0  On |                  N/A |
| N/A   60C    P0             24W /   99W |     299MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            3248      G   /usr/bin/gnome-shell                     42MiB |
|    0   N/A  N/A          443983      C   ...book_expert/.venv/bin/python3        230MiB |
+-----------------------------------------------------------------------------------------+

### First Bad Commit

I have built before with the same command just fine.

### Compile command

```shell
niko@dev-machine ~/Dev/llama.cpp master [.venv] [15:01] $  export CXX=/usr/bin/clang && export CC=/usr/bin/clang && cmake -B build -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS  -DGGML_CUDA=ON -DGGML_CUDA_F16=true -DGGML_CUDA_FA_ALL_QUANT=true -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DGGML_CUDA_FA_ALL_QUANTS=true -DCMAKE_CUDA_HOST_COMPILER="/usr/bin/gcc-14"  GGML_CCACHE=OFF
```

### Relevant log output

```shell
/home/niko/Dev/llama.cpp/src/llama-quant.cpp:643:66: note: use function 'std::abs' instead
  643 |                 gguf_set_val_u32(ctx_out.get(), o.key, (uint32_t)abs(o.val_i64));
      |                                                                  ^~~
      |                                                                  std::abs
1 warning generated.
/usr/bin/ld: ../src/libllama.a(llama-impl.cpp.o): in function `llama_log_internal(ggml_log_level, char const*, ...)':
llama-impl.cpp:(.text+0x188): undefined reference to `operator new[](unsigned long)'
/usr/bin/ld: llama-impl.cpp:(.text+0x1c1): undefined reference to `operator delete[](void*)'
/usr/bin/ld: ../src/libllama.a(llama-impl.cpp.o): in function `replace_all(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
```

**Comment by nnikolov3** [comment]
Modifying: ama-quant.cpp:643:66: 
gguf_set_val_u32(ctx_out.get(), o.key, (uint32_t)abs(o.val_i64));
uint64_t instead of uint32_t
---
Per Perplexity
Redundant null termination: The line buffer2[len] = 0; is unnecessary since vsnprintf() already null-terminates the string when given sufficient buffer size.

va_end() misuse: va_end(args_copy) should only be called if the va_copy() succeeded and the copied va_list was actually used. While this might work on many systems, it's technically incorrect usage.

Magic number: The buffer size of 128 is hardcoded. Consider making it a named constant for better maintainability.

No error handling: vsnprintf() can fail (return negative), but this isn't checked.

---
It compiled fine with:
static void llama_log_internal_v(ggml_log_level level, const char * format, va_list args) {
    constexpr int STACK_BUFFER_SIZE = 128;
    char buffer[STACK_BUFFER_SIZE];
    
    va_list args_copy;
    va_copy(args_copy, args);
    
    int len = vsnprintf(buffer, STACK_BUFFER_SIZE, format, args);
    
    if (len < 0) {
        // Handle vsnprintf error
        va_end(args_copy);
        return;
    }
    
    if (len < STACK_BUFFER_SIZE) {
        g_logger_state.log_callback(level, buffer, g_logger_state.log_callback_user_data);
    } else {
        std::vector<char> buffer2(len + 1);
        vsnprintf(buffer2.data(), len + 1, format, args_copy);
        g_logger_state.log_callback(level, buffer2.data(), g_logger_state.log_callback_user_data);
    }
    
    va_end(args_copy);
}

%] Built target llama-llava-cli
[ 98%] Building CXX object tools/mtmd/CMakeFiles/llama-gemma3-cli.dir/deprecation-warning.cpp.o
[ 98%] Linking CXX executable ../../bin/llama-gemma3-cli
[ 98%] Built target llama-gemma3-cli
[ 98%] Building CXX object tools/mtmd/CMakeFiles/llama-minicpmv-cli.dir/deprecation-warning.cpp.o
[ 99%] Linking CXX executable ../../bin/llama-minicpmv-cli
[ 99%] Built target llama-minicpmv-cli
[100%] Building CXX object tools/mtmd/CMakeFiles/llama-qwen2vl-cli.dir/deprecation-warning.cpp.o
[100%] Linking CXX executable ../../bin/llama-qwen2vl-cli
[100%] Built target llama-qwen2vl-cli
[100%] Building CXX object tools/mtmd/CMakeFiles/llama-mtmd-cli.dir/mtmd-cli.cpp.o
[100%] Linking CXX executable ../../bin/llama-mtmd-cli
[100%] Built target llama-mtmd-cli
[100%] Building CXX object tools/cvector-generator/CMakeFiles/llama-cvector-generator.dir/cvector-generator.cpp.o
[100%] Linking CXX executable ../../bin/llama-cvector-generator
[100%] Built target llama-cvector-generator
[100%] Building CXX object tools/export-lora/CMakeFiles/llama-export-lora.dir/export-lora.cpp.o
[100%] Linking CXX executable ../../bin/llama-export-lora
[100%] Built target llama-export-lora
niko@dev-machine ~/Dev/llama.cpp master [.venv] [15:29] $
