### ISSUE TITLE
Compile bug: function  common_chat_parse(const std::string & input, bool is_partial, const common_chat_syntax & syntax) declared but never defined

### ISSUE THREAD

**Issue by sheldonrobinson** [ggml-org/llama.cpp#17771]
### Git commit

git rev-parse HEAD
da988ee0d3445503157dfda0746a3d2d41027f9a

### Operating systems

Windows

### GGML backends

CPU

### Problem description & steps to reproduce

```
#include "chat-parser.h"
#include "chat.h"
common_chat_syntax syntax;
common_chat_msg_parser parser("Thought about something", false, syntax);
common_chat_parse(parser);
common_chat_msg_t msg = parser.result();
```

Function declaration from $chat.h$, 
```
common_chat_msg           common_chat_parse(const std::string & input, bool is_partial, const common_chat_syntax & syntax);
```

Function definition from $chat-parser.cpp$,
```
static void common_chat_parse(common_chat_msg_parser & builder) {
    LOG_DBG("Parsing input with format %s: %s\n", common_chat_format_name(builder.syntax().format), builder.input().c_str()); 
...
```
Solution:
Function definition should be move to $chat-parser.h$ and change to 
```
static void common_chat_parse(common_chat_msg_parser & builder);
```

### First Bad Commit

git sha: 03914c7ef826caf0b6371a6d1de270cda102b542
git tag: b7192

### Compile command

```shell
cmake -B win-x64 -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DLLAMA_BUILD_COMMON=ON -DLLAMA_BUILD_SERVER=OFF -DLLAMA_CURL=OFF -DGGML_NATIVE=OFF -DGGML_AVX=ON -DGGML_AVX2=ON -DGGML_FMA=ON -DGGML_F16C=ON -DGGML_CPU=ON -DGGML_CUDA=OFF -DGGML_OPENMP=ON -DGGML_VULKAN=OFF -DGGML_CPU_ALL_VARIANTS=OFF -DGGML_LLAMAFILE=OFF -DGGML_KOMPUTE=OFF
```

### Relevant log output

```shell
error C2660: 'common_chat_parse': function does not take 1 arguments
```

**Comment by pwilkin** [comment]
Okay, actually my bad, I looked into it in more detail now. 

The `common_chat_parse` function that you're referring to is an internal function (hence the static) - it's not exported and not visible outside the C++ source file. The other `common_chat_parse` function is the one that's part of the external API.

If there's no actual use case for this then I wouldn't really touch it, as it's potentially going to break more things than it fixes.

**Comment by sheldonrobinson** [comment]
Did a fix see PR #17772 
The issue is `common_chat_parse` declared in  `chat.h` but `static void common_chat_parse(common_chat_msg_parser & builder) ` is  called by `common_chat_msg common_chat_parse(const std::string & input, bool is_partial, const common_chat_syntax & syntax)`.
To handle this, we introduced a code smell, with `common_chat_msg common_chat_parse(const std::string & input, bool is_partial, const common_chat_syntax & syntax)` defined in `chat.h` but implemented in  `chat-parser.cpp`  (not where normally expected `chat.cpp`).

The suggested fix is moving `common_chat_msg common_chat_parse(const std::string & input, bool is_partial, const common_chat_syntax & syntax)` to `chat-parser.h`.

Same applies to `common_chat_peg_parse`

**Comment by pwilkin** [comment]
@sheldonrobinson Yeah, but why is this a bug?

I thought you were saying the single-argument version was visible earlier before the refactoring. But that's not the case, it's always been part of the internal API. 

Why would you want to have visibility for the single-argument version? As in - what's the actual use case here?

**Comment by sheldonrobinson** [comment]
@pwilkin Agreed, not a bug more of a code smell.  For example, the snippet below would seem reasonable but `parser.result()` does not invoke `common_chat_parse(this)` so `result_` is uninitialized.  It is not a bug but a tweak to API design.
```
#include "chat-parser.h"
common_chat_syntax syntax;
common_chat_msg_parser parser("Thought about something", false, syntax);
common_chat_msg_t msg = parser.result();
```
