### ISSUE TITLE
Compile bug: cublasSgemmBatched alias is missing for HIP

### ISSUE THREAD

**Issue by grivera64** [ggml-org/llama.cpp#25038]
### Git commit

I am running on the latest commit as of writing this issue:

```console
$ git rev-parse HEAD
c16c35b8142ac34b4559a5e8584e8daaf3958416
```

### Operating systems

Linux

### GGML backends

HIP

### Problem description & steps to reproduce

I was trying to compile llama.cpp with the latest commit on my Ubuntu 26.04 server, and I ran into a compile error regarding `cublasSgemmBatched` (view relevant log output below).

##### Steps to Reproduce:

1. Configure CMake to compile for HIP backend on `gfx1151`
```console
cmake -B build -DGGML_HIP=ON -DCMAKE_HIP_ARCHITECTURES=gfx1151 -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_BUILD_TYPE=Release
```
2. Build CMake
```console
cmake --build build -j$(nproc) --config Release
```
3. Bug is encountered

I'll write a one-line PR to fix this build issue, since it's just mapping `cublasSgemmBatched` to `hipblasSgemmBatched`.

### First Bad Commit

After running `git bisect`, it came to the conclusion that the problematic PR was #24426: 

```console
$ git bisect good
f818065d753700341b5355ce36ca676ecfb5d139 is the first bad commit
commit f818065d753700341b5355ce36ca676ecfb5d139
Author: leonardHONG <2695316095@qq.com>
Date:   Fri Jun 26 13:51:25 2026 +0800

    CUDA: batch out_prod broadcast (dps2>1) path with cublasSgemmBatched (#24426)

 ggml/src/ggml-cuda/out-prod.cu | 67 +++++++++++++++++++++++++++++++++++++++++++++++++++++++------------
 tests/test-backend-ops.cpp     |  6 ++++++
 2 files changed, 61 insertions(+), 12 deletions(-)
```

### Compile command

```shell
cmake --build build -j$(nproc) --config Release
```

### Relevant log output

```shell
[ 6%] Built target llama-ui/workspace/llama.cpp/ggml/src/ggml-cuda/out-prod.cu:112:13: error: use of undeclared identifier 'cublasSgemmBatched'; did you mean 'hipblasSgemmBatched'?
112 | cublasSgemmBatched(handle, CUBLAS_OP_N, src1_cublas_op,
| ^~~~~~~~~~~~~~~~~~
| hipblasSgemmBatched
/workspace/llama.cpp/ggml/src/ggml-cuda/common.cuh:215:42: note: expanded from macro 'CUBLAS_CHECK'
215 | #define CUBLAS_CHECK(err) CUDA_CHECK_GEN(err, CUBLAS_STATUS_SUCCESS, cublas_get_error_str)
| ^~~
/workspace/llama.cpp/ggml/src/ggml-cuda/common.cuh:185:22: note: expanded from macro 'CUDA_CHECK_GEN'
185 | auto err_ = (err); \
| ^~~
/usr/include/hipblas/hipblas.h:14877:32: note: 'hipblasSgemmBatched' declared here
14877 | HIPBLAS_EXPORT hipblasStatus_t hipblasSgemmBatched(hipblasHandle_t handle,
| ^
1 error generated when compiling for gfx1151.
gmake[2]: *** [ggml/src/ggml-hip/CMakeFiles/ggml-hip.dir/build.make:598: ggml/src/ggml-hip/CMakeFiles/ggml-hip.dir/__/ggml-cuda/out-prod.cu.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2474: ggml/src/ggml-hip/CMakeFiles/ggml-hip.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

**Comment by grivera64** [comment]
This just got fixed 2 minutes ago in https://github.com/ggml-org/llama.cpp/commit/2f18fe13c5dd61e7f069e0c817086cbbce2134dc

Thanks @leonardHONG !
