### ISSUE TITLE
Compile bug: fatal error: '../src/ggml-ext.h' file not found

### ISSUE THREAD

**Issue by yurivict** [ggml-org/llama.cpp#21860]
### Git commit

```
/usr/ports/misc/llama-cpp/work/llama.cpp-b8779/src/llama.cpp:19:10: fatal error: '../src/ggml-ext.h' file not found
   19 | #include "../src/ggml-ext.h"
      |          ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

Version: 8779
FreeBSD 15 STABLE

### Operating systems

BSD

### GGML backends

CPU

### Problem description & steps to reproduce

See above.

### First Bad Commit

n/a

### Compile command

```shell
n/a
```

### Relevant log output

```shell
see above
```
