### ISSUE TITLE
Compile bug: error: use of undeclared identifier 'errno'

### ISSUE THREAD

**Issue by peppergrayxyz** [ggml-org/llama.cpp#28557]
### Git commit

e71b80510c848c00175924ecf3c40333ccae8eb5

### Operating systems

Linux

### GGML backends

CPU, CUDA, AMX, BLAS, CANN, Hexagon, HIP, Metal, Musa, OpenCL, OpenVINO, RPC, SYCL, VirtGPU, Vulkan, WebGPU, zDNN, ZenDNN

### Problem description & steps to reproduce

I'm on Gentoo arm64 using clang+musl

```
$ git clone https://github.com/ggml-org/llama.cpp
$ cd llama.cpp
$ cmake -B build
$ cmake --build build --config Release
```

### First Bad Commit

37c35f0e1c625831687b146cbb0a57654ef88ca2

### Compile command

```shell
cmake --build build --config Release
```

### Relevant log output

```shell
[29/896] /usr/lib/llvm/22/bin/clang++ -DGGML_BUILD -DGGML_SCHED_MAX_COPIES=4 -DGGML_SHARED -DGGML_USE_OPENMP -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -Dggml_base_EXPORTS -I/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/. -I/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999_build/ggml/src -I/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/../include  -mcpu=neoverse-n1 -O2 -pipe -std=gnu++17 -fPIC -Wmissing-declarations -Wmissing-noreturn -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi -fopenmp=libomp -MD -MT ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o -MF ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o.d -o ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o -c /var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/gguf.cpp
FAILED: [code=1] ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o
/usr/lib/llvm/22/bin/clang++ -DGGML_BUILD -DGGML_SCHED_MAX_COPIES=4 -DGGML_SHARED -DGGML_USE_OPENMP -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -Dggml_base_EXPORTS -I/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/. -I/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999_build/ggml/src -I/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/../include  -mcpu=neoverse-n1 -O2 -pipe -std=gnu++17 -fPIC -Wmissing-declarations -Wmissing-noreturn -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi -fopenmp=libomp -MD -MT ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o -MF ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o.d -o ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o -c /var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/gguf.cpp
/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/gguf.cpp:996:94: error: use of undeclared identifier 'errno'
  996 |         GGML_LOG_ERROR("%s: failed to open GGUF file '%s' (%s)\n", __func__, fname, strerror(errno));
      |                                                                                              ^~~~~
1 error generated.
```

**Comment by peppergrayxyz** [comment]
`#include <cerrno>` is missing in `ggml/src/gguf.cpp`
