### PR TITLE
Fix for LLAMA_WIN_VER default value, fixes #5158

### LINKED ISSUE #5158: Help: when "cmake  --build . --config Release" ,    error: unknown type name 'FINDEX_INFO_LEVELS'
cmake --build . --config Release
[  1%] Building C object CMakeFiles/ggml.dir/ggml.c.obj
In file included from C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/winbase.h:18,
                 from C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/windows.h:70,
                 from D:\wuwei\LLM\LLAMA\llama.cpp\ggml.c:43:
C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/fileapi.h:168:65: error: unknown type name 'FINDEX_INFO_LEVELS'; did you mean 'GET_FILEEX_INFO_LEVELS'?
  168 |   WINBASEAPI HANDLE WINAPI FindFirstFileExA (LPCSTR lpFileName, FINDEX_INFO_LEVELS fInfoLevelId, LPVOID lpFindFileData, FINDEX_SEARCH_OPS fSearchOp, LPVOID lpSearchFilter, DWORD dwAdditionalFlags);
      |                                                                 ^~~~~~~~~~~~~~~~~~
      |                                                                 GET_FILEEX_INFO_LEVELS
C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/fileapi.h:168:121: error: unknown type name 'FINDEX_SEARCH_OPS'
  168 |   WINBASEAPI HANDLE WINAPI FindFirstFileExA (LPCSTR lpFileName, FINDEX_INFO_LEVELS fInfoLevelId, LPVOID lpFindFileData, FINDEX_SEARCH_OPS fSearchOp, LPVOID lpSearchFilter, DWORD dwAdditionalFlags);
      |
        ^~~~~~~~~~~~~~~~~
C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/fileapi.h:169:66: error: unknown type name 'FINDEX_INFO_LEVELS'; did you mean 'GET_FILEEX_INFO_LEVELS'?
  169 |   WINBASEAPI HANDLE WINAPI FindFirstFileExW (LPCWSTR lpFileName, FINDEX_INFO_LEVELS fInfoLevelId, LPVOID lpFindFileData, FINDEX_SEARCH_OPS fSearchOp, LPVOID lpSearchFilter, DWORD dwAdditionalFlags);
      |                                                                  ^~~~~~~~~~~~~~~~~~
      |                                                                  GET_FILEEX_INFO_LEVELS
C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/fileapi.h:169:122: error: unknown type name 'FINDEX_SEARCH_OPS'
  169 |   WINBASEAPI HANDLE WINAPI FindFirstFileExW (LPCWSTR lpFileName, FINDEX_INFO_LEVELS fInfoLevelId, LPVOID lpFindFileData, FINDEX_SEARCH_OPS fSearchOp, LPVOID lpSearchFilter, DWORD dwAdditionalFlags);
      |
         ^~~~~~~~~~~~~~~~~
In file included from C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/windows.h:76:
C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/winreg.h:200:59: error: unknown type name 'PVALENTA'
  200 |   WINADVAPI LONG WINAPI RegQueryMultipleValuesA(HKEY hKey,PVALENTA val_list,DWORD num_vals,LPSTR lpValueBuf,LPDWORD ldwTotsize);
      |                                                           ^~~~~~~~
C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/winreg.h:201:59: error: unknown type name 'PVALENTW'
  201 |   WINADVAPI LONG WINAPI RegQueryMultipleValuesW(HKEY hKey,PVALENTW val_list,DWORD num_vals,LPWSTR lpValueBuf,LPDWORD ldwTotsize);
      |                                                           ^~~~~~~~
In file included from C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/objbase.h:14,
                 from C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/ole2.h:17,
                 from C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/wtypes.h:13,
                 from C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/winscard.h:10,
                 from C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/windows.h:97:
C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/combaseapi.h:232:79: error: unknown type name 'SOLE_AUTHENTICATION_SERVICE'
  232 | WINOLEAPI CoInitializeSecurity (PSECURITY_DESCRIPTOR pSecDesc, LONG cAuthSvc, SOLE_AUTHENTICATION_SERVICE *asAuthSvc, void *pReserved1, DWORD dwAuthnLevel, DWORD dwImpLevel, void *pAuthList, DWORD dwCapabilities, void *pReserved3);
      |                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/amywe/scoop/apps/mingw/13.2.0-rt_v11-rev1/x86_64-w64-mingw32/include/combaseapi.h:257:60: error: unknown type name 'SOLE_AUTHENTICATION_SERVICE'
  257 | WINOLEAPI CoQueryAuthenticationServices (DWORD *pcAuthSvc, SOLE_AUTHENTICATION_SERVICE **asAuthSvc);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
mingw32-make[2]: *** [CMakeFiles\ggml.dir\build.make:76: CMakeFiles/ggml.dir/ggml.c.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:719: CMakeFiles/ggml.dir/all] Error 2
mingw32-make: *** [Makefile:145: all] Error 2

### PR DESCRIPTION
**Pull request by crimsonmagick**
Fix for #5158 

Updated CMakeLists.txt to set the default value for `LLAMA_WIN_VER` with `set()` instead of `option()` (which is specifically for booleans).

I encountered the issue when I updated [my Java JNI project](https://github.com/crimsonmagick/jllama) to tag b2050, and [my MinGW build broke](https://github.com/crimsonmagick/jllama/actions/runs/7764646615/job/21178345971#step:4:828).

Confirmed the bug with this diagnostic in CMakeLists.txt:

```
if (WIN32)
    option(LLAMA_WIN_VER                     "llama: Windows Version"                           0x602)
    message(WARNING "LLAMA_WIN_VER set to: ${LLAMA_WIN_VER}")
endif()
```

Which resulted in:

5158-default-message-before

So, unless `LLAMA_WIN_VER` is supplied by a user def, this value defaults to `OFF` instead of the intended `0x602`. Since I wasn't specifying the def, the MinGW build failed.

The [`option()`](https://cmake.org/cmake/help/v3.28/command/option.html#option) command is for boolean values, and it looks like cmake defaults to `OFF` if it can't parse the parameter.

Switching from `option()` to `set()` fixed the issue:

5158-default-message-after

I also confirmed that specifying `LLAMA_WIN_VER` still works after my update by passing `-DLLAMA_WIN_VER=0x400`:

5158-definition-message-after

### CODE REVIEW

**Comment by slaren** [comment]
Looks correct, but do you know why it wasn't caught when `LLAMA_WIN_VER` was first introduced in https://github.com/ggerganov/llama.cpp/pull/3419?

**Comment by crimsonmagick** [comment]
> Looks correct, but do you know why it wasn't caught when `LLAMA_WIN_VER` was first introduced in #3419?

My guess is that it's because of a difference in how the MinGW and MSVC toolchains handle an unsupported `_WIN32_WINNT` value. 

MinGW likely either defaults to an older set of headers, or excludes certain headers altogether, resulting in the error `include/fileapi.h:168:65: error: unknown type name 'FINDEX_INFO_LEVELS'; did you mean 'GET_FILEEX_INFO_LEVELS'?` [Here's a relevant forum post from back in 1999](https://forums.codeguru.com/showthread.php?72772-Making-a-directory-list-FindFirstFileEx-unrecognized-by-the-compiler):

```
 FindFirstFileEx() is only available on Windows NT 4.0+ (not on Win95/98). It's declared in winbase.h as 
 
 #if(_WIN32_WINNT &gt;= 0x0400)
   typedef enum _FINDEX_INFO_LEVELS {
   ...
 ```

If MinGW defaults to a version before 0x0400, we'd expect to get the error in issue #5158. MSVC likely defaults to a newer version of _WIN32_WINNT, probably the the latest version of Windows that the SDK supports. Since the Windows builds in `build.yml` use MSVC, this issue would not be readily apparent.

Do you think it would be worthwhile to add a check for MinGW?

**Comment by slaren** [comment]
As far as I understand the `CMakeLists.txt`, `LLAMA_WIN_VER` is only used when building with MinGW:
https://github.com/ggerganov/llama.cpp/blob/ed6b91d57c422cc28a0f1dc236be934f954964ef/CMakeLists.txt#L956-L959
So I don't think this is related to MSVC, but maybe something changed in MinGW since that was merged.

**Review by slaren — APPROVED** [review]

**Comment by crimsonmagick** [comment]
Ah, you're right. So not a difference between toolchains, but the issue still wouldn't be caught by the pipeline, unless there's a MinGW action I've missed in `build.yml`

**Comment by guilt** [comment]
> Looks correct, but do you know why it wasn't caught when `LLAMA_WIN_VER` was first introduced in #3419?

That would be me. My bad. I was explictly testing it with -DLLAMA_WIN_VER=0x501 and it was working fine. Apparently it's a Boolean option and yet CMake overrides it? That is some unintuitive bug. 

The idea was to ensure we explictly define the version for older OSes and catch unintended compile time and runtime issues through explicit compiler guards, as quoted above. Did not catch this one. Sorry, and thank you for this patch.

**Comment by crimsonmagick** [comment]
> > Looks correct, but do you know why it wasn't caught when `LLAMA_WIN_VER` was first introduced in #3419?
> 
> That would be me. My bad. I was explictly testing it with -DLLAMA_WIN_VER=0x501 and it was working fine. Apparently it's a Boolean option and yet CMake overrides it with a working int value? That is some unintuitive bug.
> 
> The idea was to ensure we explictly define the version for older OSes and catch unintended compile time and runtime issues through explicit compiler guards, as quoted above. Did not catch this one. Sorry, and thank you for this patch.

Yeah agreed, the CMake behavior is really unintuitive - I would hope that OPTION() would throw an error when set with a non boolean value. Moreover, when left at the default `OFF`, the MinGW toolchain didn't complain about an invalid `_WIN32_WINNT ` value, at least not at default logging levels.
