### PR TITLE
common : add missing <fstream> include in common.h

### LINKED ISSUE #25046: Compile bug: ifstream import missing from common.h
### Git commit

$git rev-parse HEAD 3ac3c20c968cc6d485d89382f202ec440767875a

### Operating systems

Linux

### GGML backends

CPU

### Problem description & steps to reproduce

I'm trying to compile Llama.cpp on a Graviton4 with GCC trunk, during the build I get the following error:
```cmake
    859 | std::ifstream fs_open_ifstream(const std::string & fname, std::ios_base::openmode mode);
            |      ^~~~~~~~
/opt/buildAgent/work/c7eaf0c2fd2fe166/common/common.h:17:1: note: 'std::ifstream' is defined in header '<fstream>'; this is probably fixable by adding '#include <fstream>'
     16 | #include <algorithm>
  +++ |+#include <fstream>
``` 
It seems there is an include header missing from 'common/common.h' which is causing errors for numerous files in 'common/'

### First Bad Commit

 I believe the culprit is this commit: e475fa2b5f9fb50c3d6fc3e7c6fdf1e004465b62

### Compile command

```shell
cmake -S %teamcity.build.checkoutDir% \
  -B . \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_C_FLAGS="$CFLAGS" \
  -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
  -DLLAMA_OPENSSL=ON \
  -DLLAMA_CURL=OFF \
  -DGGML_NATIVE=OFF \
  -DGGML_CPU_AARCH64=ON \
  -DGGML_CPU_ARM_ARCH="%CPU_ARM_ARCH_OPTS%" \
  -DGGML_CPU_KLEIDIAI="%CPU_KLEIDIAI_OPTS%" \
  -DLLAMA_LLGUIDANCE=OFF
cmake --build . --config Release -j --verbose --target llama-batched-bench llama-quantize
```

### Relevant log output

```shell
12:00:11   In file included from /opt/buildAgent/work/c7eaf0c2fd2fe166/common/sampling.h:5,
12:00:11                    from /opt/buildAgent/work/c7eaf0c2fd2fe166/common/llguidance.cpp:1:
12:00:11   /opt/buildAgent/work/c7eaf0c2fd2fe166/common/common.h:859:6: error: 'ifstream' in namespace 'std' does not name a type
12:00:11     859 | std::ifstream fs_open_ifstream(const std::string & fname, std::ios_base::openmode mode);
12:00:11         |      ^~~~~~~~
12:00:11   /opt/buildAgent/work/c7eaf0c2fd2fe166/common/common.h:17:1: note: 'std::ifstream' is defined in header '<fstream>'; this is probably fixable by adding '#include <fstream>'
12:00:11      16 | #include <algorithm>
12:00:11     +++ |+#include <fstream>
12:00:11      17 |
12:00:11   In file included from /opt/buildAgent/work/c7eaf0c2fd2fe166/common/ngram-map.cpp:1:
12:00:11   /opt/buildAgent/work/c7eaf0c2fd2fe166/common/common.h:859:6: error: 'ifstream' in namespace 'std' does not name a type
12:00:11     859 | std::ifstream fs_open_ifstream(const std::string & fname, std::ios_base::openmode mode);
12:00:11         |      ^~~~~~~~
12:00:11   /opt/buildAgent/work/c7eaf0c2fd2fe166/common/common.h:17:1: note: 'std::ifstream' is defined in header '<fstream>'; this is probably fixable by adding '#include <fstream>'
12:00:11      16 | #include <algorithm>
12:00:11     +++ |+#include <fstream>
12:00:11      17 |
12:00:11   In file included from /opt/buildAgent/work/c7eaf0c2fd2fe166/common/speculative.h:4,
12:00:11                    from /opt/buildAgent/work/c7eaf0c2fd2fe166/common/speculative.cpp:1:
12:00:11   /opt/buildAgent/work/c7eaf0c2fd2fe166/common/common.h:859:6: error: 'ifstream' in namespace 'std' does not name a type
12:00:11     859 | std::ifstream fs_open_ifstream(const std::string & fname, std::ios_base::openmode mode);
12:00:11         |      ^~~~~~~~
12:00:11   /opt/buildAgent/work/c7eaf0c2fd2fe166/common/common.h:17:1: note: 'std::ifstream' is defined in header '<fstream>'; this is probably fixable by adding '#include <fstream>'
12:00:11      16 | #include <algorithm>
12:00:11     +++ |+#include <fstream>
12:00:11      17 |
12:00:11   In file included from /opt/buildAgent/work/c7eaf0c2fd2fe166/common/reasoning-budget.cpp:2:
12:00:11   /opt/buildAgent/work/c7eaf0c2fd2fe166/common/common.h:859:6: error: 'ifstream' in namespace 'std' does not name a type
12:00:11     859 | std::ifstream fs_open_ifstream(const std::string & fname, std::ios_base::openmode mode);
12:00:11         |      ^~~~~~~~
12:00:11   /opt/buildAgent/work/c7eaf0c2fd2fe166/common/common.h:17:1: note: 'std::ifstream' is defined in header '<fstream>'; this is probably fixable by adding '#include <fstream>'
12:00:11      16 | #include <algorithm>
12:00:11     +++ |+#include <fstream>
12:00:11      17 |
```

### PR DESCRIPTION
**Pull request by zhangrunda**
## Overview
`common/common.h` declares `fs_open_ifstream()` which returns `std::ifstream`, but the header does not `#include <fstream>`. 
The type was previously available only transitively through other includes. 

On stricter toolchains (e.g. GCC trunk on aarch64/Graviton4) that transitive include is not present, so compilation fails with:error: 'ifstream' in namespace 'std' does not name a type

This adds the  `#include <fstream>`, following the include-what-you-use principle.

## Additional information
Fixes #25046

## Requirements
- [x] I have read and agree with the [contributing guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md)
- AI usage disclosure: YES — used an AI assistant to help diagnose the root cause (transitive-include breakage) and review the fix. The one-line change and all decisions are my own, and I take responsibility for the submitted change.

### CODE REVIEW

**Comment by zhangrunda** [comment]
> Hi @zhangrunda, thanks for your contribution!
> 
> Per our [contribution guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md), the automated PR checker found the following issue(s) that need your attention:
> 
> - **AI-generated content**: This project does not accept PRs, descriptions or commit messages that are fully or predominantly AI-generated. If you have used AI to assist you in writing code, please make sure to disclose that explicitly.
> 
> ---
> 
> _Please note that maintainers reserve the right to make final decisions on PRs. If you believe there is a mistake, please comment below._

Thanks for the note. To clarify: this is a one-line change (adding a missing `#include <fstream>`). I used AI to help confirm the include reasoning; the change and decisions are mine. 
Happy to adjust the wording if the disclosure isn't clear enough.

**Review by ngxson — APPROVED** [review]
