### ISSUE TITLE
llama.cpp fails to compile in ../ggml/src/ggml-cpu/simd-mappings.h with: 45:9: error: unknown type name '__fp16'

### ISSUE THREAD

**Issue by stefson** [ggml-org/llama.cpp#26677]
### Git commit

I'm on 74ade52741203e5c8f81eaf06a96cb1cfe15f2a3

### Operating systems

Linux

### GGML backends

CPU

### Problem description & steps to reproduce

hi, I want to compile firefox-nightly on linux and it fails very early with an error from third_party/llama.cpp 

```
 .deps/gmp-fake-openh264.o.pp  -fdiagnostics-color  /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/dom/media/gmp-plugin-openh264/gmp-fake-openh264.cpp
 0:52.09 E /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:45:9: error: unknown type name '__fp16'; did you mean '__bf16'?
 0:52.09 E    45 |         __fp16 tmp;
 0:52.10 E       |         ^~~~~~
 0:52.10 E       |         __bf16
 0:52.10 E /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:52:9: error: unknown type name '__fp16'; did you mean '__bf16'?
 0:52.10 E    52 |         __fp16 tmp = f;
 0:52.11 E       |         ^~~~~~
 0:52.11 E       |         __bf16
```

this is a neon build for armv7a, using gcc

non-neon works with gcc

### First Bad Commit

I will fill this out later, once I've found a standalone build script for llama.cpp

### Compile command

```shell
I believe this is all: 

 
 0:50.94 gmake[4]: Entering directory '/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/third_party/llama.cpp'
 0:50.98 third_party/llama.cpp/ggml-alloc.o
 0:50.99 third_party/llama.cpp/ggml-c.o
 0:51.01 /usr/bin/armv7a-unknown-linux-gnueabihf-gcc --sysroot /usr/armv7a-unknown-linux-gnueabihf -o ggml-alloc.o -c  -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/system_wrappers -include /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/config/gcc_hidden.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstrict-flex-arrays=1 -DNDEBUG=1 -DTRIMMED=1 -D_GNU_SOURCE=1 -DGGML_USE_CPU=1 '-DGGML_VERSION="GGML_VERSION"' '-DGGML_COMMIT="GGML_COMMIT"' -DGGML_SHARED=1 -DLLAMA_SHARED=1 -DGGML_BUILD=1 -DLLAMA_BUILD=1 -DGGML_BACKEND_SHARED=1 -DGGML_BACKEND_BUILD=1 -DMOZ_HAS_MOZGLUE -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/third_party/llama.cpp -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/include -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/include -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/src -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/include -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nspr -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nss -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nspr -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/include/nss -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/libpng16 -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/pixman-1 -DMOZILLA_CLIENT -include /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/mozilla-config.h -mthumb -mfpu=neon -mfloat-abi=hard -mno-thumb-interwork -pthread -ffunction-sections -fdata-sections -fno-math-errno -pipe -fPIC -pipe -fomit-frame-pointer -O2 -fno-omit-frame-pointer -funwind-tables -Wall -Wempty-body -Wignored-qualifiers -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Winvalid-utf8 -Wduplicated-cond -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=free-nonheap-object -Wno-multistatement-macros -Wno-error=class-memaccess -Wformat -Wformat-security -Wformat-overflow=2 -Werror=implicit-function-declaration -Wno-psabi -Wno-error=builtin-macro-redefined -Wno-sign-compare -Wno-unused-function -Wno-unreachable-code -Wno-tautological-unsigned-enum-zero-compare -fno-strict-aliasing -ffp-contract=off  -MD -MP -MF .deps/ggml-alloc.o.pp  -fdiagnostics-color  /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-alloc.c
 0:51.64 /usr/bin/armv7a-unknown-linux-gnueabihf-gcc --sysroot /usr/armv7a-unknown-linux-gnueabihf -o ggml-c.o -c  -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/system_wrappers -include /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/config/gcc_hidden.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstrict-flex-arrays=1 -DNDEBUG=1 -DTRIMMED=1 -D_GNU_SOURCE=1 -DGGML_USE_CPU=1 '-DGGML_VERSION="GGML_VERSION"' '-DGGML_COMMIT="GGML_COMMIT"' -DGGML_SHARED=1 -DLLAMA_SHARED=1 -DGGML_BUILD=1 -DLLAMA_BUILD=1 -DGGML_BACKEND_SHARED=1 -DGGML_BACKEND_BUILD=1 -DMOZ_HAS_MOZGLUE -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/third_party/llama.cpp -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/include -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/include -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/src -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/include -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nspr -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nss -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nspr -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/include/nss -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/libpng16 -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/pixman-1 -DMOZILLA_CLIENT -include /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/mozilla-config.h -mthumb -mfpu=neon -mfloat-abi=hard -mno-thumb-interwork -pthread -ffunction-sections -fdata-sections -fno-math-errno -pipe -fPIC -pipe -fomit-frame-pointer -O2 -fno-omit-frame-pointer -funwind-tables -Wall -Wempty-body -Wignored-qualifiers -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Winvalid-utf8 -Wduplicated-cond -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=free-nonheap-object -Wno-multistatement-macros -Wno-error=class-memaccess -Wformat -Wformat-security -Wformat-overflow=2 -Werror=implicit-function-declaration -Wno-psabi -Wno-error=builtin-macro-redefined -Wno-sign-compare -Wno-unused-function -Wno-unreachable-code -Wno-tautological-unsigned-enum-zero-compare -fno-strict-aliasing -ffp-contract=off  -MD -MP -MF .deps/ggml-c.o.pp  -fdiagnostics-color  /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-c.c
 0:51.64 third_party/llama.cpp/quants-arm.o
 0:51.77 third_party/llama.cpp/ggml-cpu-c.o
 0:51.83 /usr/bin/armv7a-unknown-linux-gnueabihf-gcc --sysroot /usr/armv7a-unknown-linux-gnueabihf -o quants-arm.o -c  -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/system_wrappers -include /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/config/gcc_hidden.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstrict-flex-arrays=1 -DNDEBUG=1 -DTRIMMED=1 -D_GNU_SOURCE=1 -DGGML_USE_CPU=1 '-DGGML_VERSION="GGML_VERSION"' '-DGGML_COMMIT="GGML_COMMIT"' -DGGML_SHARED=1 -DLLAMA_SHARED=1 -DGGML_BUILD=1 -DLLAMA_BUILD=1 -DGGML_BACKEND_SHARED=1 -DGGML_BACKEND_BUILD=1 -DMOZ_HAS_MOZGLUE -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/third_party/llama.cpp -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/include -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/include -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/src -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/include -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nspr -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nss -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nspr -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/include/nss -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/libpng16 -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/pixman-1 -DMOZILLA_CLIENT -include /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/mozilla-config.h -mthumb -mfpu=neon -mfloat-abi=hard -mno-thumb-interwork -pthread -ffunction-sections -fdata-sections -fno-math-errno -pipe -fPIC -pipe -fomit-frame-pointer -O2 -fno-omit-frame-pointer -funwind-tables -Wall -Wempty-body -Wignored-qualifiers -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Winvalid-utf8 -Wduplicated-cond -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=free-nonheap-object -Wno-multistatement-macros -Wno-error=class-memaccess -Wformat -Wformat-security -Wformat-overflow=2 -Werror=implicit-function-declaration -Wno-psabi -Wno-error=builtin-macro-redefined -Wno-sign-compare -Wno-unused-function -Wno-unreachable-code -Wno-tautological-unsigned-enum-zero-compare -fno-strict-aliasing -ffp-contract=off  -MD -MP -MF .deps/quants-arm.o.pp  -fdiagnostics-color  /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu/arch/arm/quants-arm.c
 0:52.09 E /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:45:9: error: unknown type name '__fp16'; did you mean '__bf16'?
 0:52.10 E /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:52:9: error: unknown type name '__fp16'; did you mean '__bf16'?
 0:55.40 gmake[4]: Leaving directory '/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/third_party/llama.cpp'
 0:55.41 E gmake[3]: *** [/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/config/recurse.mk:79: third_party/llama.cpp/target-objects] Error 2
```

### Relevant log output

```shell
I will attach the full build log later.
```

**Comment by stefson** [comment]
here is the full build log, it was not possible to attach it in the bug prompt: [build.log.gz](https://github.com/user-attachments/files/30791999/build.log.gz)

**Comment by ServeurpersoCom** [comment]
Please try this tiny patch :

```
diff --git a/ggml/src/ggml-cpu/simd-mappings.h b/ggml/src/ggml-cpu/simd-mappings.h
index fca5119e1..4179605d5 100644
--- a/ggml/src/ggml-cpu/simd-mappings.h
+++ b/ggml/src/ggml-cpu/simd-mappings.h
@@ -29,13 +29,14 @@ extern "C" {
 // FP16 to FP32 conversion

 // 16-bit float
-// on Arm, we use __fp16
+// on Arm, we use __fp16, which requires the IEEE fp16 format: implied on AArch64, selected by
+//     -mfp16-format=ieee on 32-bit Arm, where the compiler may otherwise reject the type
 // on x86, we use uint16_t
 //
 // for old CUDA compilers (<= 11), we use uint16_t: ref https://github.com/ggml-org/llama.cpp/pull/10616
 // for     MUSA compilers        , we use uint16_t: ref https://github.com/ggml-org/llama.cpp/pull/11843
 //
-#if defined(__ARM_NEON) && !(defined(__CUDACC__) && __CUDACC_VER_MAJOR__ <= 11) && !defined(__MUSACC__)
+#if defined(__ARM_NEON) && defined(__ARM_FP16_FORMAT_IEEE) && !(defined(__CUDACC__) && __CUDACC_VER_MAJOR__ <= 11) && !defined(__MUSACC__)
     #define GGML_CPU_COMPUTE_FP16_TO_FP32(x) neon_compute_fp16_to_fp32(x)
     #define GGML_CPU_COMPUTE_FP32_TO_FP16(x) neon_compute_fp32_to_fp16(x)

```

__ARM_NEON only signals NEON availability, while __fp16 additionally requires the IEEE half format, which is implied on AArch64 but must be selected with -mfp16-format=ieee on 32 bit Arm, so gating the block on __ARM_FP16_FORMAT_IEEE restores the generic lookup path for that one configuration and leaves every toolchain that already provides the type on the exact same code.

**Comment by stefson** [comment]
I've tested the patch with my cross setup and it seems to work, however I feel I need to test it with a native compile before this can be merged. This will need a few days, native compile is slow. 

Maybe you can draft a pullrequest? I can comment there once testing is completed, or ping you here.

**Comment by stefson** [comment]
@ServeurpersoCom

patch works, all test compiles with gcc/clang and with/without neon optimization on arm were successfull.

**Comment by ServeurpersoCom** [comment]
Don't hesitate to ping me, I sometimes miss messages in the flood of notifications :) Thanks for testing
