### ISSUE TITLE
Misc. bug UI: symbolic math tool JS sandbox prompt contains mistakes

### ISSUE THREAD

**Issue by kimdedeyn** [ggml-org/llama.cpp#26071]
### Name and Version

PS C:\llama.cpp> .\llama-server.exe --version
version: 10103 (c588c4f47)
built with Clang 20.1.8 for Windows x86_64

### Operating systems

Windows

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
PS C:\llama.cpp> .\llama-server.exe -m "D:\Models\bottlecapai\ThinkingCap-Qwen3.6-27B-GGUF\ThinkingCap-Qwen3.6-27B-Q6_K.gguf" --mmproj "D:\Models\bottlecapai\ThinkingCap-Qwen3.6-27B-GGUF\mmproj-ThinkingCap-Qwen3.6-27B-f16.gguf" --ctx-size 92000 --jinja --host 127.0.0.1 --port 8080 --alias "Qwen3.6-27B" --temp 0.6 --top-p 0.95 --top-k 20 --min-p 0.00 --repeat-penalty 1.0 --presence_penalty 0.0 --image-min-tokens 1024 -np 1 --no-kv-unified -ngl all --webui-mcp-proxy --spec-type draft-mtp --spec-draft-ngl all --spec-draft-n-max 4 --tools all
```

### Problem description & steps to reproduce

PR https://github.com/ggml-org/llama.cpp/pull/25948 added support for symbolic math in the JS toolbox of the llama-server webui using the nerdamer library. I noticed that the model had trouble using it because the tool prompt contains instructions that aren't valid?

Current tool prompt:

const NERDAMER_DESCRIPTION = `
Symbolic/numeric math via \`nerdamer\` (pre-loaded, do not require, use it directly).
nerdamer('diff(sin(x)/x,x)') or nerdamer.diff('sin(x)/x','x') → Expression; convert with .toString()/.text()/.toTeX(), or .evaluate() (→ still Expression, then .toString()).
nerdamer(expr,{x:2}) substitutes only; chain .evaluate() or pass 'numer' for numeric result.
solve(expr,var)→Symbol[]; solveEquations([eq1,..])→[[var,val],..] pairs.
Functions: simplify/expand/factor(expr), diff(expr,var[,n]), integrate(expr,var), defint(expr,from,to,var), limit(expr,var,to), laplace(expr,t,s), ilt(expr,s,t), gcd/lcm(a,b), roots/coeffs/partfrac(expr,var), pfactor(n), numer/decimals/erf(expr), product/sum(expr,var,from,to), mean/median/stdev/variance(...vals).
Object.keys(nerdamer).filter(k=>typeof nerdamer[k]==='function') lists all available functions. If you need a function not documented above, list them first — do not guess function names.`;

numer/decimals -> these aren't functions, confusing the model

Object.keys(nerdamer).filter(k => typeof nerdamer[k] === 'function');

Outputs:

[
  "rpn", "convertToLaTeX", "convertFromLaTeX", "version", "getWarnings", 
  "setConstant", "getConstant", "clearConstants", "setFunction", "clearFunctions", 
  "getCore", "getEquation", "getExpression", "reserved", "clear", "flush", 
  "expressions", "functions", "register", "validateName", "validVarName", 
  "supported", "numExpressions", "numEquations", "setVar", "getVar", "clearVars", 
  "load", "getVars", "set", "get", "updateAPI", "replaceFunction", "setOperator", 
  "getOperator", "aliasOperator", "tree", "htmlTree", "addPeeker", "removePeeker", 
  "parse", "cos", "sin", "tan", "sec", "csc", "cot", "acos", "asin", "atan", 
  "arccos", "arcsin", "arctan", "asec", "acsc", "acot", "atan2", "acoth", "asech", 
  "acsch", "sinh", "cosh", "tanh", "asinh", "sech", "csch", "coth", "acosh", 
  "atanh", "log10", "log2", "log1p", "exp", "radians", "degrees", "min", "max", 
  "erf", "floor", "ceil", "trunc", "Si", "step", "rect", "sinc", "tri", "sign", 
  "Ci", "Ei", "Shi", "Chi", "Li", "fib", "fact", "factorial", "continuedFraction", 
  "dfactorial", "gamma_incomplete", "round", "scientific", "mod", "pfactor", 
  "vector", "matrix", "NerdamerSet", "imatrix", "parens", "sqrt", "cbrt", "nthroot", 
  "log", "expand", "abs", "invert", "determinant", "size", "transpose", "dot", 
  "cross", "vecget", "vecset", "vectrim", "matget", "matset", "matgetrow", 
  "matsetrow", "matgetcol", "matsetcol", "rationalize", "IF", "isIn", "realpart", 
  "imagpart", "conjugate", "arg", "polarform", "rectform", "sort", "integer_part", 
  "union", "contains", "intersection", "difference", "intersects", "isSubset", 
  "primes", "print", "diff", "sum", "product", "integrate", "defint", "S", "C", 
  "limit", "useAlgebraDiv", "useParserDiv", "coeffs", "factor", "simplify", "gcd", 
  "lcm", "roots", "divide", "div", "partfrac", "deg", "line", "sqcomp", 
  "solveEquations", "solve", "setEquation", "laplace", "ilt", "mean", "median", 
  "mode", "smpvar", "variance", "smpstdev", "stdev", "zscore"
]

Example correct use:

// Numer is an option to the main object
// https://nerdamer.com/functions/nerdamer.html
var x = nerdamer('(x^2+2*x)*x+1+x+cos(y)', {y: '7'}, ['expand', 'numer']);
var x = nerdamer('(x^2+2*x)*x+1+x+cos(y)', {y: '7'}, ['expand', 'numer']);

// Decimals is a option for the text method
// https://nerdamer.com/functions/Expression.text.html
var x = nerdamer('1/12+1/2*cos(x)-0.5');
console.log(x.text('decimals'));
console.log(x.text('decimals', 1));
console.log(x.text('decimals', 7));

### First Bad Commit

https://github.com/ggml-org/llama.cpp/pull/25948

### Relevant log output

Prompt
What does 'numer' and 'decimals' do in the JS toolbox? Test it and give examples.

Reasoning
The user wants to know what the numer and decimals functions do in the provided JavaScript toolbox (which seems to be the nerdamer library).
I need to:

Explain what numer and decimals do based on the tool description or general knowledge of nerdamer.
Test these functions using the run_javascript tool.
Provide examples of their usage.
From the tool description:

numer(expr): likely returns the numerator of an expression.
decimals(expr): likely returns the decimal representation of an expression.
Let's verify this by running some code.

Plan:

Call run_javascript to test nerdamer.numer and nerdamer.decimals.
Synthesize the explanation and examples from the test results.
Test cases:

numer: Try with a fraction like 3/4 or x/(x+1).
decimals: Try with a fraction like 1/3 or pi.
Let's execute the code.

TypeError: nerdamer.numer is not a function

**Comment by rankaiyx** [comment]
Let me take a look.
