### ISSUE TITLE
Not able to convert hf models to gguf anymore

### ISSUE THREAD

**Issue by DigitalRudeness** [ggml-org/llama.cpp#14315]
### Name and Version

version: 5731 (bb16041c)
built with cc (Gentoo 14.3.0 p8) 14.3.0 for x86_64-pc-linux-gnu

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

Other (Please specify in the next section)

### Command line

```shell
#huggingface-to-gguf is a symlink to the real file
./huggingface-to-gguf models/aya-expanse-8b/ --outtype q8_0
```

### Problem description & steps to reproduce

I'm not able to convert huggingface models to gguf anymore via convert_hf_to_gguf.py.

I tried the last few commits of the file but always get errors like:

`Traceback (most recent call last):
  File "/opt/ggml/./huggingface-to-gguf", line 2020, in <module>
    class ArceeModel(LlamaModel):
  File "/opt/ggml/./huggingface-to-gguf", line 2021, in ArceeModel
    model_arch = gguf.MODEL_ARCH.ARCEE
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'MODEL_ARCH' has no attribute 'ARCEE'`

at going back to older versions i got the same regarding the 'DOTS1' arch.

Occurred at trying with aya-expanse, command-r-plus

### First Bad Commit

https://github.com/ggml-org/llama.cpp/commit/9ae4143bc6ecb4c2f0f0301578f619f6c201b857

### Relevant log output

```shell

```

**Comment by CISC** [comment]
Your `gguf` package is outdated.

**Comment by CISC** [comment]
Also note that if you want to convert any newly added model you should run `convert_hf_to_gguf.py` directly from the repository (out-of-repo symlink won't work) so that it uses `gguf-py` from the repo instead of your installed `gguf` package.

**Comment by DigitalRudeness** [comment]
@CISC: thanks a lot! i even didn't think about the gguf package! now it works again! :-)

if anyone else will have this issue: i was at gguf-0.17.0, from gguf-0.17.1 upwards it worked again
