### PR TITLE
ggml : fix missing reference to std::filesystem #10978

### LINKED ISSUE #10978: Compile bug: undefined reference to std::filesystem
### Git commit

9ba399dfa7f115effc63d48e6860a94c9faa31b2

### Operating systems

Linux

### GGML backends

CPU

### Problem description & steps to reproduce

When compiling with gcc8 in Linux, a linking error occurred.
undefined reference to std::filesystem

### First Bad Commit

_No response_

### Relevant log output

```shell
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `vtable for std::filesystem::__cxx11::filesystem_error'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `typeinfo for std::filesystem::__cxx11::filesystem_error'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::path::_M_find_extension() const'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::filesystem_error::~filesystem_error()'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::filesystem_error::_M_gen_what()'
```

### PR DESCRIPTION
**Pull request by JordanNanos**
resolves #10978

*Make sure to read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md) before submitting a PR*

### CODE REVIEW

**Comment by ggerganov** [comment]
This is needed for old compilers. With new compilers you don't have to add this flag, so it is better to simply upgrade your `gcc`.
