### ISSUE TITLE
Compile bug: CMake Error - "CMakeCUDACompilerId.cu" failed.

### ISSUE THREAD

**Issue by djubre7** [ggml-org/llama.cpp#22714]
### Git commit

EDIT: Compiling this same version (b9030) for CPU worked without issues with the command:
`cmake -B build -DGGML_NATIVE=ON -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS -DCMAKE_BUILD_TYPE=Release`

First compilation error ever, always using the same command - my previous build from 3 days ago compiled without issues. 

System:
```
Operating System: CachyOS Linux 
KDE Plasma Version: 6.6.4
KDE Frameworks Version: 6.25.0
Qt Version: 6.11.0
Kernel Version: 7.0.3-1-cachyos (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 9950X 16-Core Processor
Memory: 96 GiB of RAM (91.9 GiB usable)
Graphics Processor 1: NVIDIA GeForce RTX 4060 Ti
Graphics Processor 2: AMD Ryzen 9 9950X 16-Core Processor
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7E49
System Version: 1.0
```

### Operating systems

Linux

### GGML backends

CUDA

### Problem description & steps to reproduce

Compiling llama.cpp on cachyOS with command
`cmake -B build -DGGML_NATIVE=ON -DGGML_CUDA=ON -DGGML_CUDA_FORCE_CUBLAS=ON -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS -DCMAKE_BUILD_TYPE=Release`

### First Bad Commit

b9030

### Compile command

```shell
cmake -B build -DGGML_NATIVE=ON -DGGML_CUDA=ON -DGGML_CUDA_FORCE_CUBLAS=ON -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS -DCMAKE_BUILD_TYPE=Release
```

### Relevant log output

```shell
-- The C compiler identification is GNU 16.1.1
-- The CXX compiler identification is GNU 16.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE=Release
-- Found Git: /usr/bin/git (found version "2.54.0")
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- Found OpenMP_C: -fopenmp (found version "5.2")
-- Found OpenMP_CXX: -fopenmp (found version "5.2")
-- Found OpenMP: TRUE (found version "5.2")
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib/libopenblas.so
-- BLAS found, Libraries: /usr/lib/libopenblas.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.5.1")
-- Checking for module 'openblas64'
--   Found openblas64, version 0.3.33
-- BLAS found, Includes: /usr/include/openblas64
-- Including BLAS backend
-- Found CUDAToolkit: /opt/cuda/targets/x86_64-linux/include;/opt/cuda/targets/x86_64-linux/include/cccl (found version "13.2.78")
-- CUDA Toolkit found
CMake Error at /usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:934 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /opt/cuda/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp -v



  The output was:

  4

  #$ _NVVM_BRANCH_=nvvm

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ CUDA_ROOT=/opt/cuda/bin

  #$ _HERE_=/opt/cuda/bin

  #$ _THERE_=/opt/cuda/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_DIR_=targets/x86_64-linux

  #$ TOP=/opt/cuda/bin/..

  #$ CICC_PATH=/opt/cuda/bin/../nvvm/bin

  #$ NVVMIR_LIBRARY_DIR=/opt/cuda/bin/../nvvm/libdevice

  #$ LD_LIBRARY_PATH=/opt/cuda/bin/../lib:

  #$
  PATH=/opt/cuda/bin/../nvvm/bin:/opt/cuda/bin:/home/predrag/.brv-cli/bin:/home/predrag/miniforge3/bin:/home/predrag/miniforge3/condabin:/home/predrag/.config/emacs/bin:/home/predrag/.config/carapace/bin:/home/predrag.config/emacs/bin:/home/predrag/.local/bin:/home/predrag/.brv-cli/bin:/home/predrag/.config/emacs/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/predrag/.lmstudio/bin:/home/predrag/.fzf/bin:/home/predrag/.lmstudio/bin

  #$ INCLUDES="-I/opt/cuda/bin/../targets/x86_64-linux/include"

  #$ SYSTEM_INCLUDES="-isystem"
  "/opt/cuda/bin/../targets/x86_64-linux/include/cccl"

  #$ LIBRARIES= "-L/opt/cuda/bin/../targets/x86_64-linux/lib/stubs"
  "-L/opt/cuda/bin/../targets/x86_64-linux/lib"

  #$ CUDAFE_FLAGS=

  #$ PTXAS_FLAGS=

  #$ rm tmp/a_dlink.reg.c

  #$ "/usr/bin"/g++ -D__CUDA_ARCH_LIST__=750 -E -x c++ -D__CUDACC__
  -D__NVCC__ "-I/opt/cuda/bin/../targets/x86_64-linux/include" "-isystem"
  "/opt/cuda/bin/../targets/x86_64-linux/include/cccl"
  -D__CUDACC_VER_MAJOR__=13 -D__CUDACC_VER_MINOR__=2
  -D__CUDACC_VER_BUILD__=78 -D__CUDA_API_VER_MAJOR__=13
  -D__CUDA_API_VER_MINOR__=2 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1
  -D__CUDACC_DEVICE_ATOMIC_BUILTINS__=1 -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" -o "tmp/CMakeCUDACompilerId.cpp4.ii"

  #$ cudafe++ --c++17 --static-host-stub --device-hidden-visibility
  --gnu_version=160101 --display_error_number --orig_src_file_name
  "CMakeCUDACompilerId.cu" --orig_src_path_name
  "/home/predrag/ai/llama_cpp_env/llama.cpp/build/CMakeFiles/4.3.2/CompilerIdCUDA/CMakeCUDACompilerId.cu"
  --allow_managed --m64 --parse_templates --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.cpp" --stub_file_name
  "CMakeCUDACompilerId.cudafe1.stub.c" --gen_module_id_file
  --module_id_file_name "tmp/CMakeCUDACompilerId.module_id"
  "tmp/CMakeCUDACompilerId.cpp4.ii"

  /usr/include/c++/16.1.1/type_traits(393): error: identifier "char8_t" is
  undefined

        struct __is_integral_helper<char8_t>
                                    ^



  /usr/include/c++/16.1.1/type_traits(1448): error: identifier "__f" is
  undefined

          = requires (void(&__f)(_Tp)) { __f({}); };
                            ^



  /usr/include/c++/16.1.1/type_traits(1448): error: expression preceding
  parentheses of apparent call must have (pointer-to-) function type

          = requires (void(&__f)(_Tp)) { __f({}); };
                      ^



  /usr/include/c++/16.1.1/type_traits(1448): error: type name is not allowed

          = requires (void(&__f)(_Tp)) { __f({}); };
                                 ^



  /usr/include/c++/16.1.1/type_traits(1448): error: identifier "requires" is
  undefined

          = requires (void(&__f)(_Tp)) { __f({}); };
            ^



  /usr/include/c++/16.1.1/type_traits(1448): error: expected a ";"

          = requires (void(&__f)(_Tp)) { __f({}); };
                                       ^



  /usr/include/c++/16.1.1/type_traits(2071): error: identifier "char8_t" is
  undefined

        struct __make_unsigned<char8_t>
                               ^



  /usr/include/c++/16.1.1/type_traits(2074): error: identifier "char8_t" is
  undefined

     = typename __make_unsigned_selector<char8_t, false, true>::__type;
                                         ^



  /usr/include/c++/16.1.1/type_traits(2074): error: incomplete type
  "std::__make_unsigned_selector<<error-type>, false, true>" is not allowed

     = typename __make_unsigned_selector<char8_t, false, true>::__type;
                ^



  /usr/include/c++/16.1.1/type_traits(2209): error: identifier "char8_t" is
  undefined

        struct __make_signed<char8_t>
                             ^



  /usr/include/c++/16.1.1/type_traits(2212): error: identifier "char8_t" is
  undefined

     = typename __make_signed_selector<char8_t, false, true>::__type;
                                       ^



  /usr/include/c++/16.1.1/type_traits(2212): error: incomplete type
  "std::__make_signed_selector<<error-type>, false, true>" is not allowed

     = typename __make_signed_selector<char8_t, false, true>::__type;
                ^



  /usr/include/c++/16.1.1/type_traits(2986): error: "requires" is not a type
  name

        requires requires { typename _Op<_Args...>; }
        ^



  /usr/include/c++/16.1.1/type_traits(2986): error: a class or namespace
  qualified name is required

        requires requires { typename _Op<_Args...>; }
                                     ^



  /usr/include/c++/16.1.1/type_traits(2986): error: type name is not allowed

        requires requires { typename _Op<_Args...>; }
                            ^



  /usr/include/c++/16.1.1/type_traits(2986): error: expected a "}"

        requires requires { typename _Op<_Args...>; }
                                                  ^



  /usr/include/c++/16.1.1/type_traits(2987): error: __detected_or is not a
  template

        struct __detected_or<_Def, _Op, _Args...>
               ^



  /usr/include/c++/16.1.1/type_traits(2987): error: identifier "_Def" is
  undefined

        struct __detected_or<_Def, _Op, _Args...>
                             ^



  /usr/include/c++/16.1.1/type_traits(2987): error: identifier "_Op" is
  undefined

        struct __detected_or<_Def, _Op, _Args...>
                                   ^



  /usr/include/c++/16.1.1/type_traits(2987): error: identifier "_Args" is
  undefined

        struct __detected_or<_Def, _Op, _Args...>
                                        ^



  /usr/include/c++/16.1.1/type_traits(2987): error: expected a ">"

        struct __detected_or<_Def, _Op, _Args...>
                                             ^



  /usr/include/c++/16.1.1/type_traits(2989): error: expected a ">"

          using type = _Op<_Args...>;
                                ^



  /usr/include/c++/16.1.1/type_traits(2990): error: identifier "true_type" is
  undefined

          using __is_detected = true_type;
                                ^



  /usr/include/c++/16.1.1/type_traits(3020): error: __detected_or is not a
  template

          = typename __detected_or<_Default, _Op, _Args...>::type;
                     ^



  /usr/include/c++/16.1.1/type_traits(3043): error: not a class or struct
  name

        struct __is_tuple_like_impl : false_type
                                      ^



  /usr/include/c++/16.1.1/type_traits(3049): error: __remove_cvref_t is not a
  template

        : public __is_tuple_like_impl<__remove_cvref_t<_Tp>>::type
                                      ^



  /usr/include/c++/16.1.1/type_traits(3056): error: _Require is not a
  template

        _Require<__not_<__is_tuple_like<_Tp>>,
        ^



  /usr/include/c++/16.1.1/type_traits(3056): error: identifier "__not_" is
  undefined

        _Require<__not_<__is_tuple_like<_Tp>>,
                 ^



  /usr/include/c++/16.1.1/type_traits(3056): error: type name is not allowed

        _Require<__not_<__is_tuple_like<_Tp>>,
                        ^



  /usr/include/c++/16.1.1/type_traits(3054): error: "constexpr" is not valid
  here

        constexpr
        ^



  /usr/include/c++/16.1.1/type_traits(3056): error: expected a ";"

        _Require<__not_<__is_tuple_like<_Tp>>,
                                             ^



  /usr/include/c++/16.1.1/type_traits(3066): error: __enable_if_t is not a
  template

        __enable_if_t<__is_swappable<_Tp>::value>
        ^



  /usr/include/c++/16.1.1/type_traits(3072): error: namespace "std" has no
  member "swap"

        using std::swap;
                   ^



  /usr/include/c++/16.1.1/type_traits(3078): error: identifier "true_type" is
  undefined

            static true_type __test(int);
                   ^



  /usr/include/c++/16.1.1/type_traits(3081): error: identifier "false_type"
  is undefined

            static false_type __test(...);
                   ^



  /usr/include/c++/16.1.1/type_traits(3087): error: __bool_constant is not a
  template

            static __bool_constant<
                   ^



  /usr/include/c++/16.1.1/type_traits(3092): error: identifier "false_type"
  is undefined

            static false_type __test(...);
                   ^



  /usr/include/c++/16.1.1/type_traits(3130): error: identifier
  "__type_identity" is undefined

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                                                        ^



  /usr/include/c++/16.1.1/type_traits(3130): error: type name is not allowed

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                                                                        ^



  /usr/include/c++/16.1.1/type_traits(3130): error: expected an expression

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                                                                            ^



  /usr/include/c++/16.1.1/type_traits(3130): error: no instance of overloaded
  function "std::__is_complete_or_unbounded" matches the argument list

              argument types are: (<error-type>)
          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                        ^

  /usr/include/c++/16.1.1/type_traits(319): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(_TypeIdentity)" failed deduction

        __is_complete_or_unbounded(_TypeIdentity)
        ^

  /usr/include/c++/16.1.1/type_traits(311): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(std::__type_identity<_Tp>)"
  failed deduction

        __is_complete_or_unbounded(__type_identity<_Tp>)
        ^



  /usr/include/c++/16.1.1/type_traits(3139): error: identifier
  "__type_identity" is undefined

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                                                        ^



  /usr/include/c++/16.1.1/type_traits(3139): error: type name is not allowed

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                                                                        ^



  /usr/include/c++/16.1.1/type_traits(3139): error: expected an expression

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                                                                            ^



  /usr/include/c++/16.1.1/type_traits(3139): error: no instance of overloaded
  function "std::__is_complete_or_unbounded" matches the argument list

              argument types are: (<error-type>)
          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                        ^

  /usr/include/c++/16.1.1/type_traits(319): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(_TypeIdentity)" failed deduction

        __is_complete_or_unbounded(_TypeIdentity)
        ^

  /usr/include/c++/16.1.1/type_traits(311): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(std::__type_identity<_Tp>)"
  failed deduction

        __is_complete_or_unbounded(__type_identity<_Tp>)
        ^



  /usr/include/c++/16.1.1/type_traits(3157): error: namespace "std" has no
  member "swap"

        using std::swap;
                   ^



  /usr/include/c++/16.1.1/type_traits(3165): error: identifier "true_type" is
  undefined

            static true_type __test(int);
                   ^



  /usr/include/c++/16.1.1/type_traits(3168): error: identifier "false_type"
  is undefined

            static false_type __test(...);
                   ^



  /usr/include/c++/16.1.1/type_traits(3174): error: __bool_constant is not a
  template

            static __bool_constant<
                   ^



  /usr/include/c++/16.1.1/type_traits(3181): error: identifier "false_type"
  is undefined

            static false_type __test(...);
                   ^



  /usr/include/c++/16.1.1/type_traits(3222): error: identifier
  "__type_identity" is undefined

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                                                        ^



  /usr/include/c++/16.1.1/type_traits(3222): error: type name is not allowed

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                                                                        ^



  /usr/include/c++/16.1.1/type_traits(3222): error: expected an expression

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                                                                            ^



  /usr/include/c++/16.1.1/type_traits(3222): error: no instance of overloaded
  function "std::__is_complete_or_unbounded" matches the argument list

              argument types are: (<error-type>)
          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                        ^

  /usr/include/c++/16.1.1/type_traits(319): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(_TypeIdentity)" failed deduction

        __is_complete_or_unbounded(_TypeIdentity)
        ^

  /usr/include/c++/16.1.1/type_traits(311): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(std::__type_identity<_Tp>)"
  failed deduction

        __is_complete_or_unbounded(__type_identity<_Tp>)
        ^



  /usr/include/c++/16.1.1/type_traits(3224): error: type name is not allowed

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Up>{}),
                                                                        ^



  /usr/include/c++/16.1.1/type_traits(3224): error: expected an expression

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Up>{}),
                                                                            ^



  /usr/include/c++/16.1.1/type_traits(3224): error: no instance of overloaded
  function "std::__is_complete_or_unbounded" matches the argument list

              argument types are: (<error-type>)
          static_assert(std::__is_complete_or_unbounded(__type_identity<_Up>{}),
                        ^

  /usr/include/c++/16.1.1/type_traits(319): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(_TypeIdentity)" failed deduction

        __is_complete_or_unbounded(_TypeIdentity)
        ^

  /usr/include/c++/16.1.1/type_traits(311): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(std::__type_identity<_Tp>)"
  failed deduction

        __is_complete_or_unbounded(__type_identity<_Tp>)
        ^



  /usr/include/c++/16.1.1/type_traits(3233): error: identifier
  "__type_identity" is undefined

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                                                        ^



  /usr/include/c++/16.1.1/type_traits(3233): error: type name is not allowed

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                                                                        ^



  /usr/include/c++/16.1.1/type_traits(3233): error: expected an expression

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                                                                            ^



  /usr/include/c++/16.1.1/type_traits(3233): error: no instance of overloaded
  function "std::__is_complete_or_unbounded" matches the argument list

              argument types are: (<error-type>)
          static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
                        ^

  /usr/include/c++/16.1.1/type_traits(319): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(_TypeIdentity)" failed deduction

        __is_complete_or_unbounded(_TypeIdentity)
        ^

  /usr/include/c++/16.1.1/type_traits(311): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(std::__type_identity<_Tp>)"
  failed deduction

        __is_complete_or_unbounded(__type_identity<_Tp>)
        ^



  /usr/include/c++/16.1.1/type_traits(3235): error: type name is not allowed

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Up>{}),
                                                                        ^



  /usr/include/c++/16.1.1/type_traits(3235): error: expected an expression

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Up>{}),
                                                                            ^



  /usr/include/c++/16.1.1/type_traits(3235): error: no instance of overloaded
  function "std::__is_complete_or_unbounded" matches the argument list

              argument types are: (<error-type>)
          static_assert(std::__is_complete_or_unbounded(__type_identity<_Up>{}),
                        ^

  /usr/include/c++/16.1.1/type_traits(319): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(_TypeIdentity)" failed deduction

        __is_complete_or_unbounded(_TypeIdentity)
        ^

  /usr/include/c++/16.1.1/type_traits(311): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(std::__type_identity<_Tp>)"
  failed deduction

        __is_complete_or_unbounded(__type_identity<_Tp>)
        ^



  /usr/include/c++/16.1.1/type_traits(3259): error: identifier "is_void" is
  undefined

        bool = is_void<_Ret>::value, typename = void>
               ^



  /usr/include/c++/16.1.1/type_traits(3259): error: type name is not allowed

        bool = is_void<_Ret>::value, typename = void>
                       ^



  /usr/include/c++/16.1.1/type_traits(3259): error: expected a ";"

        bool = is_void<_Ret>::value, typename = void>
                                   ^



  /usr/include/c++/16.1.1/type_traits(3270): error: identifier "__void_t" is
  undefined

              __void_t<typename _Result::type>>
              ^



  /usr/include/c++/16.1.1/type_traits(3270): error: type name is not allowed

              __void_t<typename _Result::type>>
                       ^



  /usr/include/c++/16.1.1/type_traits(3268): error: __is_invocable_impl is
  not a template

        struct __is_invocable_impl<_Result, _Ret,
               ^



  /usr/include/c++/16.1.1/type_traits(3270): error: expected a ";"

              __void_t<typename _Result::type>>
                                             ^



  /usr/include/c++/16.1.1/type_traits(3282): error: identifier "__void_t" is
  undefined

              __void_t<typename _Result::type>>
              ^



  /usr/include/c++/16.1.1/type_traits(3282): error: type name is not allowed

              __void_t<typename _Result::type>>
                       ^



  /usr/include/c++/16.1.1/type_traits(3280): error: __is_invocable_impl is
  not a template

        struct __is_invocable_impl<_Result, _Ret,
               ^



  /usr/include/c++/16.1.1/type_traits(3282): error: expected a ";"

              __void_t<typename _Result::type>>
                                             ^



  /usr/include/c++/16.1.1/type_traits(3310): error: identifier "false_type"
  is undefined

     static false_type
            ^



  /usr/include/c++/16.1.1/type_traits(3313): error: expected a declaration

        public:
        ^



  /usr/include/c++/16.1.1/type_traits(3318): error: identifier "_Ret" is
  undefined

          using __nothrow_conv = decltype(_S_test<_Ret>(1));
                                                  ^



  /usr/include/c++/16.1.1/type_traits(3325): error: __bool_constant is not a
  template

        : __bool_constant<__is_invocable(_Fn, _ArgTypes...)>
          ^



  /usr/include/c++/16.1.1/type_traits(3332): error: identifier
  "__invoke_memfun_ref" is undefined

        constexpr bool __call_is_nt(__invoke_memfun_ref)
                                    ^



  /usr/include/c++/16.1.1/type_traits(3333): error: expected a ";"

        {
        ^



  /usr/include/c++/16.1.1/type_traits(3374): error: __call_is_nothrow is not
  a template

          = __call_is_nothrow<__invoke_result<_Fn, _Args...>, _Fn, _Args...>;
            ^



  /usr/include/c++/16.1.1/type_traits(3374): error: identifier
  "__invoke_result" is undefined

          = __call_is_nothrow<__invoke_result<_Fn, _Args...>, _Fn, _Args...>;
                              ^



  /usr/include/c++/16.1.1/type_traits(3374): error: type name is not allowed

          = __call_is_nothrow<__invoke_result<_Fn, _Args...>, _Fn, _Args...>;
                                              ^



  /usr/include/c++/16.1.1/type_traits(3374): error: expected a ";"

          = __call_is_nothrow<__invoke_result<_Fn, _Args...>, _Fn, _Args...>;
                                                            ^



  /usr/include/c++/16.1.1/type_traits(3380): error: __bool_constant is not a
  template

        : __bool_constant<__is_nothrow_invocable(_Fn, _Args...)>
          ^



  /usr/include/c++/16.1.1/type_traits(3402): error: __invoke_result is not a
  template

        : public __invoke_result<_Functor, _ArgTypes...>
                 ^



  /usr/include/c++/16.1.1/type_traits(3404): error: identifier
  "__type_identity" is undefined

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Functor>{}),
                                                        ^



  /usr/include/c++/16.1.1/type_traits(3404): error: type name is not allowed

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Functor>{}),
                                                                        ^



  /usr/include/c++/16.1.1/type_traits(3404): error: expected an expression

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Functor>{}),
                                                                                 ^



  /usr/include/c++/16.1.1/type_traits(3404): error: no instance of overloaded
  function "std::__is_complete_or_unbounded" matches the argument list

              argument types are: (<error-type>)
          static_assert(std::__is_complete_or_unbounded(__type_identity<_Functor>{}),
                        ^

  /usr/include/c++/16.1.1/type_traits(319): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(_TypeIdentity)" failed deduction

        __is_complete_or_unbounded(_TypeIdentity)
        ^

  /usr/include/c++/16.1.1/type_traits(311): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(std::__type_identity<_Tp>)"
  failed deduction

        __is_complete_or_unbounded(__type_identity<_Tp>)
        ^



  /usr/include/c++/16.1.1/type_traits(3407): error: type name is not allowed

     __type_identity<_ArgTypes>{}) && ...),
                     ^



  /usr/include/c++/16.1.1/type_traits(3407): error: expected an expression

     __type_identity<_ArgTypes>{}) && ...),
                               ^



  /usr/include/c++/16.1.1/type_traits(3406): error: no instance of overloaded
  function "std::__is_complete_or_unbounded" matches the argument list

              argument types are: (<error-type>)
          static_assert((std::__is_complete_or_unbounded(
                         ^

  /usr/include/c++/16.1.1/type_traits(319): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(_TypeIdentity)" failed deduction

        __is_complete_or_unbounded(_TypeIdentity)
        ^

  /usr/include/c++/16.1.1/type_traits(311): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(std::__type_identity<_Tp>)"
  failed deduction

        __is_complete_or_unbounded(__type_identity<_Tp>)
        ^



  /usr/include/c++/16.1.1/type_traits(3419): error: __bool_constant is not a
  template

        : public __bool_constant<__is_invocable(_Fn, _ArgTypes...)>
                 ^



  /usr/include/c++/16.1.1/type_traits(3424): error: identifier
  "__type_identity" is undefined

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Fn>{}),
                                                        ^



  /usr/include/c++/16.1.1/type_traits(3424): error: type name is not allowed

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Fn>{}),
                                                                        ^



  /usr/include/c++/16.1.1/type_traits(3424): error: expected an expression

          static_assert(std::__is_complete_or_unbounded(__type_identity<_Fn>{}),
                                                                            ^



  /usr/include/c++/16.1.1/type_traits(3424): error: no instance of overloaded
  function "std::__is_complete_or_unbounded" matches the argument list

              argument types are: (<error-type>)
          static_assert(std::__is_complete_or_unbounded(__type_identity<_Fn>{}),
                        ^

  /usr/include/c++/16.1.1/type_traits(319): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(_TypeIdentity)" failed deduction

        __is_complete_or_unbounded(_TypeIdentity)
        ^

  /usr/include/c++/16.1.1/type_traits(311): note #3327-D: candidate function
  template "std::__is_complete_or_unbounded(std::__type_identity<_Tp>)"
  failed deduction

        __is_complete_or_unbounded(__type_identity<_Tp>)
        ^



  /usr/include/c++/16.1.1/type_traits(3427): error: type name is not allowed

     __type_identity<_ArgTypes>{}) && ...),
                     ^



  Error limit reached.

  100 errors detected in the compilation of "CMakeCUDACompilerId.cu".

  Compilation terminated.

  # --error 0x4 --





Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  /usr/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:163 (CMAKE_DETERMINE_COMPILER_ID)
  ggml/src/ggml-cuda/CMakeLists.txt:58 (enable_language)


-- Configuring incomplete, errors occurred!
```

**Comment by CISC** [comment]
CUDA toolkit does not support GCC 16.

**Comment by djubre7** [comment]
> CUDA toolkit does not support GCC 16.

Thank you, that was it! I wasn't paying attention on the system upgrade, I downgraded the gcc packages and it succeeded. Will mark this SOLVED.

**Comment by djubre7** [comment]
This is on GCC update, not on llama.cpp. If you upgraded to 16.1.1, revert back to 15.2 until CUDA fixes this.

**Comment by moraisaugusto** [comment]
There's no have to uninstall the version `16.1.1`. You can just install `15.2` alongside it and explicitly point to it using the correct 

example:
```
cmake \
  -DCMAKE_C_COMPILER=gcc-15 \
  -DCMAKE_CXX_COMPILER=g++-15 \
  -DCMAKE_CUDA_HOST_COMPILER=g++-15 \
  -B build \
  -DGGML_CUDA=ON
```
