### ISSUE TITLE
Compile bug: error: use of undeclared identifier 'EXIT_FAILURE'

### ISSUE THREAD

**Issue by peppergrayxyz** [ggml-org/llama.cpp#28562]
### Git commit

e71b80510c848c00175924ecf3c40333ccae8eb5

### Operating systems

Linux

### GGML backends

AMX, BLAS, CANN, CPU, CUDA, Hexagon, HIP, Metal, Musa, OpenCL, OpenVINO, RPC, SYCL, VirtGPU, Vulkan, WebGPU, zDNN, ZenDNN

### Problem description & steps to reproduce

I'm on Gentoo arm64 using clang+musl

```
$ git clone https://github.com/ggml-org/llama.cpp
$ cd llama.cpp
$ cmake -B build
$ cmake --build build --config Release
```

### First Bad Commit

84a9bf2fc2875205f0806fbbfbb66dc67204094c

### Compile command

```shell
cmake --build build --config Release
```

### Relevant log output

```shell
/home/pepper/dev/ghrepos/llama.cpp/tools/mtmd/deprecation-warning.cpp:24:12: error: use of undeclared identifier 'EXIT_FAILURE'
   24 |     return EXIT_FAILURE;
      |            ^~~~~~~~~~~~
1 error generated.
```

**Comment by peppergrayxyz** [comment]
`#include <cstdlib>` is missing in `tools/mtmd/deprecation-warning.cpp`
