### PR TITLE
Overlap cmdbuffer creation and cmdbuffer execution in Vulkan backend by submitting smaller cmdbuffers early.

### PR DESCRIPTION
**Pull request by mtavenrath**
By overlapping cmdbuffer creation and cmdbuffer submissing the GPU is less time idle resulting in a 10% perf increase for stablelm 3B Q8_0 on a RTX 6000 Ada.

```
master:
| model                          |       size |     params | backend    | ngl | mmap |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---: | ------------: | ---------------: |
| stablelm 3B Q8_0               |   2.77 GiB |     2.80 B | Vulkan     | 100 |    0 |         pp512 |   3255.25 ± 7.62 |
| stablelm 3B Q8_0               |   2.77 GiB |     2.80 B | Vulkan     | 100 |    0 |         tg512 |    133.49 ± 0.42 |

master async:
| model                          |       size |     params | backend    | ngl | mmap |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---: | ------------: | ---------------: |
| stablelm 3B Q8_0               |   2.77 GiB |     2.80 B | Vulkan     | 100 |    0 |         pp512 |   3289.29 ± 5.79 | 1.01x
| stablelm 3B Q8_0               |   2.77 GiB |     2.80 B | Vulkan     | 100 |    0 |         tg512 |    146.49 ± 2.24 | 1.10x
```

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Comment by mtavenrath** [comment]
The Vulkan documentation states:
>When [vkCmdPipelineBarrier](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdPipelineBarrier.html) is submitted to a queue, it defines a memory dependency between commands that were submitted to the same queue before it, and those submitted to the same queue after it.

Thus there is no need for pipeline barriers between multiple submits to the same queue which happens here. The change is ready to submit.

**Comment by MaggotHATE** [comment]
Trying to compile on w64devkit (Win10, Vulkan SDK 1.3.280.0), getting errors:
```
base/ggml/ggml-vulkan.cpp:5860:13: error: 'bool ggml_vk_compute_forward(ggml_backend_vk_context*, ggml_tensor*, int, bool)' was declared 'extern' and later 'static' [-fpermissive]
 5860 | static bool ggml_vk_compute_forward(ggml_backend_vk_context * ctx, ggml_tensor * tensor, int tensor_idx, bool use_fence = true){
      |             ^~~~~~~~~~~~~~~~~~~~~~~
base/ggml/ggml-vulkan.cpp:5620:6: note: previous declaration of 'bool ggml_vk_compute_forward(ggml_backend_vk_context*, ggml_tensor*, int, bool)'
 5620 | bool ggml_vk_compute_forward(ggml_backend_vk_context* ctx, ggml_tensor* tensor, int tensor_idx, bool use_fence);
      |      ^~~~~~~~~~~~~~~~~~~~~~~
base/ggml/ggml-vulkan.cpp: In function 'bool ggml_vk_compute_forward(ggml_backend_vk_context*, ggml_tensor*, int, bool)':
base/ggml/ggml-vulkan.cpp:5932:31: error: operands to '?:' have different types 'vk::Fence' and 'VkFence' {aka 'VkFence_T*'}
 5932 |     VkFence fence = use_fence ? ctx->fence : VkFence{};
      |                     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
base/ggml/ggml-vulkan.cpp:5932:31: note:   and each type can be converted to the other
```

While the first ones can be fixed by moving `static bool ggml_vk_compute_forward(...` above `static bool ggml_vk_build_graph(...`, I'm not sure how to work with `VkFence`.

**Comment by mtavenrath** [comment]
I fixed the forward declaration and type of the fence.

**Comment by MaggotHATE** [comment]
@mtavenrath Thank you! It compiles now, however, it is crashing after:
```
ggml_vulkan memory: ggml_vk_preallocate_buffers(x_size: 0)
ggml_vulkan memory: ggml_vk_preallocate_buffers(y_size: 0)
ggml_vulkan memory: ggml_vk_preallocate_buffers(split_k_size: 0)
ggml_backend_vk_graph_compute: error: failed to enqueue cmdbuffer
```

Testing setup:
* GPU - 1060 3GB
* model -  Mistral-Nemo-Instruct-2407.q5_k.gguf
* n_gpu_layers = 2 (can fit more, just for testing)
* flash_attn = false
* no_kv_offload = true

Previous version works correctly on these settings and model.

**Comment by mtavenrath** [comment]
@MaggotHATE I've rewrote the portion of the code which handles the 'last node' of a graph which resulted in the failures you mentioned. I'm no longer able to reproduce the crash with no_kv_offload = true.

**Comment by MaggotHATE** [comment]
@mtavenrath works now, thank you! Tested with DonutHole-8x7B.Q4_K_S.gguf, can fit 2 layers.

File: ggml/src/ggml-vulkan.cpp [hunk 1]
```diff
@@ -6441,31 +6464,26 @@ GGML_CALL static ggml_status ggml_backend_vk_graph_compute(ggml_backend_t backen
...
         }
 
-        bool ok = ggml_vk_compute_forward(ctx, node, i);
-        if (!ok) {
-            if (node->op == GGML_OP_UNARY) {
-                std::cerr << __func__ << ": error: op not supported UNARY " << node->name << " (" << ggml_unary_op_name(static_cast<ggml_unary_op>(node->op_params[0])) << ")" << std::endl;
-            } else {
-                std::cerr << __func__ << ": error: op not supported " << node->name << " (" << ggml_op_name(node->op) << ")" << std::endl;
-            }
+        // TODO probably it's better to move the submit conter to ggml_vk_build_graph since a lot of nodes might not contain actual vulkan work
```
Comment (0cc4m) [inline ggml/src/ggml-vulkan.cpp:6477]: I think we should try this, maybe count only if not `ggml_vk_is_empty(node)`.

Did you try a few values for `submit_count`?

Comment (mtavenrath) [reply ggml/src/ggml-vulkan.cpp:6477]: I gave a few values a try and smaller values are better. As long as submit + cmdbuffer creation doesn't get more expensive than GPU execution time smaller values will always win since GPU execution starts more early.

I was wondering about counting the return values being true as well. In the end the logic is more complicated now the logic to submit is distributed across two functions now. It'd be better to keep the logic at a single place.

Comment (0cc4m) [reply ggml/src/ggml-vulkan.cpp:6477]: I also tested a few values and 100 was very slightly better than 50, but the difference was negligible. Only counting actual submissions also made no difference. So it's probably fine as it is.

File: ggml/src/ggml-vulkan.cpp [hunk 2]
```diff
@@ -6441,31 +6464,26 @@ GGML_CALL static ggml_status ggml_backend_vk_graph_compute(ggml_backend_t backen
...
+        bool submit = i && ((i % submit_count) == 0);
+        bool enqueued = ggml_vk_build_graph(ctx, cgraph->nodes[i], i, cgraph->nodes[submit_node_idx], submit_node_idx, false, i == last_node, submit);
+
+        if (first_node_in_batch && enqueued) {
+            first_node_in_batch = false;
         }
-#ifdef GGML_VULKAN_CHECK_RESULTS
-        else {
-            ggml_vk_check_results_1(node);
```
Comment (0cc4m) [inline ggml/src/ggml-vulkan.cpp:6465]: You have to place this call somewhere else if you remove it, otherwise the operator results checker breaks.

File: ggml/src/ggml-vulkan.cpp [hunk 3]
```diff
@@ -5910,9 +5937,12 @@ static bool ggml_vk_compute_forward(ggml_backend_vk_context * ctx, ggml_tensor *
...
 
-#ifdef GGML_VULKAN_PERF
-    std::chrono::steady_clock::time_point start;
-#endif // GGML_VULKAN_PERF
+    // always wait for the GPU work to be done for the last submit
+    if (tensor_idx == subctx->exit_tensor_idx) {
+        use_fence = true;
+    }
+
+    vk::Fence fence = use_fence ? ctx->fence : vk::Fence{};
```
Comment (0cc4m) [inline ggml/src/ggml-vulkan.cpp:5945]: Is this variable needed? Can't we always use `ctx->fence`?

File: ggml/src/ggml-vulkan.cpp [hunk 4]
```diff
@@ -5921,23 +5951,16 @@ static bool ggml_vk_compute_forward(ggml_backend_vk_context * ctx, ggml_tensor *
...
 
-#ifdef GGML_VULKAN_PERF
-        auto duration = std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now() - start);
-        ctx->device->perf_logger->log_timing(tensor, duration.count());
-#endif // GGML_VULKAN_PERF
-
         ctx->device->device.resetFences({ ctx->fence });
+    }
 
+    if (tensor_idx == subctx->exit_tensor_idx) {
```
Comment (0cc4m) [inline ggml/src/ggml-vulkan.cpp:5963]: The outgoing staging buffer memcpys should only happen after the GPU operations are completed, which is after the `waitForFences` call. Since you submit work, but don't wait for it to be completed, the memcpys shouldn't be done.

However, this memcpy system might be leftover from when copying data to and back from the GPU was still the task of the backend, not the program.

Might be enough to replace the in_memcpys and out_memcpys execution with an assertion that they are empty.

Comment (mtavenrath) [reply ggml/src/ggml-vulkan.cpp:5963]: around line 5941 there is
```
    // always wait for the GPU work to be done for the last submit
    if (tensor_idx == subctx->exit_tensor_idx) {
        use_fence = true;
    }
```

if `use_fence` is true the code waits for the fence and after waiting for the fence the memcpy logic is executed. Thus the behaviour is the same as before.

File: ggml/src/ggml-vulkan.cpp (hunk 2 above)
Comment (mtavenrath) [reply ggml/src/ggml-vulkan.cpp:6465]: Do you have a recommended place where to put it?

I haven't tried to fully understand the check_results_0 / check_results_1 code yet. At a first glance it looks like check_results_0 executes the op on the CPU and check_results_1 downloads the result from the GPU and compares the results.

If that's true I'd put a loop at the end which calls check_results_0 and check_results_1 for each node that returned true and / or add a new check_boolean to the compute_forward_function which executed both checks. Still, a 2nd loop is required to run the check on each node.

Comment (0cc4m) [reply ggml/src/ggml-vulkan.cpp:6465]: That is true, yeah. It had to be this way because of inplace tensor operations. The mode forces each Vulkan operator to run in its own command buffer so that it can grab the inputs and run the operation on CPU in the first function, and compare the result in the second function afterwards.

I can take a closer look later if you don't find a good place for it first.

Comment (mtavenrath) [reply ggml/src/ggml-vulkan.cpp:6465]: With this description it's quite simple to fix the issue moving the check into `ggml_vk_compute_forward` and set `use_fence = true` always if error checking is enabled.

Testing with GGML_VULKAN_CHECKS_ENABLED I found an error as well for `stable-code-instruct-3b-Q8_0.gguf`. At a first glance it looks like a multiply by 2 is missing here.

```
ERROR: avg_err=0.542829 in ADD (check 76)
tensor=000001AB88C68A20 tensor->name=l_out-2 tensor->type: f32 ne0=2560 nb0=4 ne1=2 nb1=10240 ne2=1 nb2=20480 ne3=1 nb3=20480 offset=0
src0=000001AB88C688B0 op=MUL_MAT type=f32 ne0=2560 nb0=4 ne1=2 nb1=10240 ne2=1 nb2=20480 ne3=1 nb3=20480 offset=0
src1=000001AB88C67D30 op=ADD type=f32 ne0=2560 nb0=4 ne1=2 nb1=10240 ne2=1 nb2=20480 ne3=1 nb3=20480 offset=0
First error: result=0.711832 correct=1.41905 i3=0 i2=0 i1=0 i0=1

Result:
               0       1       2       3       4       5       6       7       8       9
      0:    0.05    0.05
      1:    0.71    0.71
      2:    1.39    1.39
      3:   -0.26   -0.26
      4:    0.39    0.39
      5:   -0.64   -0.64
      6:    0.00    0.00
      7:   -0.16   -0.16
      8:   -0.04   -0.04
      9:    0.35    0.35

Correct:
               0       1       2       3       4       5       6       7       8       9
      0:    0.09    0.09
      1:    1.42    1.42
      2:    2.77    2.77
      3:   -0.51   -0.51
      4:    0.78    0.78
      5:   -1.28   -1.28
      6:    0.01    0.01
      7:   -0.32   -0.32
      8:   -0.08   -0.08
      9:    0.69    0.69

**Comment by MaggotHATE** [comment]
Everything works correctly so far, prompt processing is very good, especially with short prompts now.

Unrelated, but I forgot to mention earlier - tedious initialization is back, it takes quite a lot of time on each launch - and it barely uses GPU. I believe it was fixed in https://github.com/ggerganov/llama.cpp/commit/befddd0f15de6efb15d7e7f5b527dfb671f4196f , but I'm not sure when exactly it broke back. It's definitely not RAM issue now since I've upgraded to 64GB. VRAM utilization is also low.

File: ggml/src/ggml-vulkan.cpp (hunk 2 above)
Comment (0cc4m) [reply ggml/src/ggml-vulkan.cpp:6465]: It does run now, but it only catches very few ops.
```
9 norm-0 op=RMS_NORM avg_err=1.44221e-08
10 v_cache_view-4 (copy of Vcur-4 (transposed)) op=CPY avg_err=0
11 ffn_gate-8 op=MUL_MAT avg_err=3.40353e-06
12 Qcur-13 op=ROPE avg_err=2.74683e-09
13 kqv_merged_cont-17 op=CONT avg_err=0
14 ffn_out-21 op=MUL_MAT avg_err=0.00043354
15 k_cache_view-26 (copy of Kcur-26) op=CPY avg_err=0
16 ffn_norm-30 op=MUL avg_err=0
```
On master it looks like this (just the first layer shown):
```
742 norm-0 op=RMS_NORM avg_err=1.44221e-08
743 attn_norm-0 op=MUL avg_err=0
744 Qcur-0 op=MUL_MAT avg_err=0.00217402
745 Qcur-0 op=ROPE avg_err=4.619e-06
746 Kcur-0 op=MUL_MAT avg_err=0.00230008
747 Kcur-0 op=ROPE avg_err=4.54624e-06
748 Vcur-0 op=MUL_MAT avg_err=0.000835142
749 k_cache_view-0 (copy of Kcur-0) op=CPY avg_err=0
750 v_cache_view-0 (copy of Vcur-0 (transposed)) op=CPY avg_err=0
751 kq-0 op=MUL_MAT avg_err=1.81626e-06
752 kq_soft_max_ext-0 op=SOFT_MAX avg_err=1.65106e-10
753 kqv-0 op=MUL_MAT avg_err=5.40341e-10
754 kqv_merged_cont-0 op=CONT avg_err=0
755 kqv_out-0 op=MUL_MAT avg_err=1.16777e-05
756 ffn_inp-0 op=ADD avg_err=0
757 norm-0 op=RMS_NORM avg_err=1.36306e-08
758 ffn_norm-0 op=MUL avg_err=0
759 ffn_gate-0 op=MUL_MAT avg_err=0.000427647
760 ffn_silu-0 op=UNARY avg_err=1.54837e-09
761 ffn_up-0 op=MUL_MAT avg_err=0.000405687
762 ffn_gate_par-0 op=MUL avg_err=0
763 ffn_out-0 op=MUL_MAT avg_err=3.88136e-05
764 l_out-0 op=ADD avg_err=0
```

Comment (0cc4m) [reply ggml/src/ggml-vulkan.cpp:6465]: @mtavenrath I found the issue, here's a possible fix:
```diff
diff --git a/ggml/src/ggml-vulkan.cpp b/ggml/src/ggml-vulkan.cpp
index 411a13c8..81fc6922 100644
--- a/ggml/src/ggml-vulkan.cpp
+++ b/ggml/src/ggml-vulkan.cpp
@@ -6483,9 +6483,11 @@ GGML_CALL static ggml_status ggml_backend_vk_graph_compute(ggml_backend_t backen
         if (enqueued) {
             ++submitted_nodes;

+#ifndef GGML_VULKAN_CHECK_RESULTS
             if (first_node_in_batch) {
                 first_node_in_batch = false;
             }
+#endif
         }

         if (submit) {
```
`first_node_in_batch` has to be true for the checks to work.

**Comment by 0cc4m** [comment]
@MaggotHATE Long initialization means it's compiling the shaders to driver-internal representations. That should only happen once after updates and after driver updates, if it happens on each launch there's an issue with your driver.

**Comment by MaggotHATE** [comment]
@0cc4m Is there a way to debug that? I'm pretty sure it was fixed at some point on the same machine I use now, no driver update since then. The only change I might think of is switching to iGPU as the main display device and updating its driver - but Vulkan detects and uses the external one, not iGPU (judging from logs, at least).

**Comment by 0cc4m** [comment]
@MaggotHATE You can build with `GGML_VULKAN_DEBUG` and check which calls are taking so long.

File: ggml/src/ggml-vulkan.cpp (hunk 2 above)
Comment (mtavenrath) [reply ggml/src/ggml-vulkan.cpp:6465]: This shouldn't be required and splatters the check results logic over multiple functions where it'd be great if it is as local as possible.

To get to `ggml_vk_compute_forward` I am setting `last_node_ to true. The main difference between working and non-working is that last_node sets the `exit_node` while submit doesn't. Can you check if changing `last_node` to `submit` solves the issue as well?

```
#if defined(GGML_VULKAN_CHECK_RESULTS) || defined(GGML_VULKAN_PERF)
    // Force context reset on each node so that each tensor ends up in its own context
    // and can be run and compared to its CPU equivalent separately
    last_node = true;
#endif
```

**Comment by mtavenrath** [comment]
I'd be quite surprised if this has been fixed unless someone added a pipeline cache. On NVIDIA drivers the pipelines are cached by the driver and thus there is a one-time cost after each driver change / shader change only. On Intel systems there doesn't seem to be a driver cache. I am having to wait a few seconds on each launch to recompile the shaders.

This time could be reduced by adding a pipeline cache and/or compiling only the pipelines which are required and/or using multiple threads for pipeline compilation.

**Comment by 0cc4m** [comment]
AMD and Intel also cache the pipelines, at least on Linux. But multithreading the pipeline compilation and adding a manual cache would be good.

File: ggml/src/ggml-vulkan.cpp (hunk 2 above)
Comment (0cc4m) [reply ggml/src/ggml-vulkan.cpp:6465]: It does not. The issue is that it only submits `node_begin`, not `node` and the logic in `ggml_backend_vk_graph_compute` only resets `node_begin` if `first_node_in_batch` is true. My fix is the easiest one, but there's probably a smarter way to make it submit each node separately for the result checker.

Comment (mtavenrath) [reply ggml/src/ggml-vulkan.cpp:6465]: Okay. I have added your fix to resolve the issue. Thank you for debugging.

**Comment by MaggotHATE** [comment]
> build with `GGML_VULKAN_DEBUG` and check which calls are taking so long

It seems like shaders are compiled over and over. From:

```
...
llm_load_print_meta: model ftype      = Q5_K - Medium
llm_load_print_meta: model params     = 12.25 B
llm_load_print_meta: model size       = 9.68 GiB (6.79 BPW)
llm_load_print_meta: general.name     = Mistral Nemo Instruct 2407
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 1196 '├Д'
llm_load_print_meta: max token length = 150
ggml_vk_instance_init()
ggml_vulkan: Found 1 Vulkan devices:
ggml_vk_print_gpu_info(1)
Vulkan0: NVIDIA GeForce GTX 1060 3GB (NVIDIA) | uma: 0 | fp16: 0 | warp size: 32
ggml_vk_get_device(0)
Initializing new vk_device
ggml_vk_find_queue_family_index()
ggml_vk_find_queue_family_index()
ggml_vk_create_queue()
ggml_vk_load_shaders(NVIDIA GeForce GTX 1060 3GB)
ggml_vk_create_pipeline(NVIDIA GeForce GTX 1060 3GB, matmul_f32_l, main, 3, 56, (128,128,1), specialization_constants, 1)
ggml_vk_create_pipeline(NVIDIA GeForce GTX 1060 3GB, matmul_f32_m, main, 3, 56, (64,64,1), specialization_constants, 1)
ggml_vk_create_pipeline(NVIDIA GeForce GTX 1060 3GB, matmul_f32_s, main, 3, 56, (32,32,1), specialization_constants, 1)
ggml_vk_create_pipeline(NVIDIA GeForce GTX 1060 3GB, matmul_f32_aligned_l, main, 3, 56, (128,128,1), specialization_constants, 128)
ggml_vk_create_pipeline(NVIDIA GeForce GTX 1060 3GB, matmul_f32_aligned_m, main, 3, 56, (64,64,1), specialization_constants, 64)
ggml_vk_create_pipeline(NVIDIA GeForce GTX 1060 3GB, matmul_f32_aligned_s, main, 3, 56, (32,32,1), specialization_constants, 32)
...
```
And it goes on each time I start my program. I suspect it has something to do with my Intel iGPU being the primary device. However, this is mainline Vulkan as I haven't got the time to merge this PR into the recent updates.

**Comment by 0cc4m** [comment]
> And it goes on each time I start my program. I suspect it has something to do with my Intel iGPU being the primary device. However, this is mainline Vulkan as I haven't got the time to merge this PR into the recent updates.

No, it shouldn't be related to your Intel iGPU. But let's not sidetrack this PR, you could open a separate issue for the compilation time and at a future point me or someone else can implement one of the improvements mtavenrath proposed.

**Review by 0cc4m — APPROVED** [review]

**Comment by jeffbolznv** [comment]
> But multithreading the pipeline compilation and adding a manual cache would be good.

I've created https://github.com/ggerganov/ggml/pull/963 to multithread vulkan pipeline compilation.

**Comment by netrunnereve** [comment]
Is it possible to get GGML_VULKAN_PERF working again after this change? If not we should probably remove that flag altogether.

**Comment by 0cc4m** [comment]
> Is it possible to get GGML_VULKAN_PERF working again after this change? If not we should probably remove that flag altogether.

It works the same way that CHECK_RESULTS works, and that is still fine. I haven't tried it in a long time, but it's fixable if it's broken.

**Comment by netrunnereve** [comment]
Oh it doesn't work now since the code that records the timing information got removed in this PR. I'll probably look into this eventually but I'm not sure if this new overlapping logic makes it difficult to see how long each op takes.

github

**Comment by 0cc4m** [comment]
> Oh it doesn't work now since the code that records the timing information got removed in this PR. I'll probably look into this eventually but I'm not sure if this new overlapping logic makes it difficult to see how long each op takes.

CHECK_RESULTS works by disabling the overlapping and batched submissions, it goes back to submitting each op on its own and comparing the result to the CPU backend. The same thing should work for perf, if someone puts it back in. I forgot it had been removed.
