### ISSUE TITLE
Compile bug: [Bug] server-http.h: missing #include <unordered_map> breaks build on macOS Catalina (10.15) with Clang 14

### ISSUE THREAD

**Issue by kanedev** [ggml-org/llama.cpp#22920]
### Git commit

Latest master (tested on 2026-05-10), last working commit: a290ce626 (b9046)

### Operating systems

Mac

### GGML backends

CPU

### Problem description & steps to reproduce

Build fails on macOS Catalina (10.15) with Clang 14 when compiling tools/server/server-context.cpp.

The file server-http.h uses std::unordered_map but is missing the explicit #include <unordered_map>.
On recent macOS SDKs this header is pulled in transitively, but on the MacOSX10.15.sdk with Clang 14
it must be included explicitly, causing a hard build error.

Steps to reproduce:
1. Clone the latest master on a Mac running macOS 10.15.7 (Intel)
2. Use Clang 14 with MacOSX10.15.sdk
3. Run the cmake command below and build with ninja

Proposed fix: add the following line at the top of tools/server/server-http.h:
#include <unordered_map>

### First Bad Commit

The bug was not present in commit a290ce626 (version b9046).
It was introduced sometime after that commit during the server refactoring
(split into server-context.cpp / server-http.h).

### Compile command

```shell
cmake .. -DGGML_METAL=OFF -DGGML_RPC=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -DCMAKE_OSX_ARCHITECTURES=x86_64 -DBUILD_SHARED_LIBS=OFF -G Ninja
```

### Relevant log output

```shell
[265/501] Building CXX object tools/server/CMakeFiles/server-context.dir/server-context.cpp.o
FAILED: tools/server/CMakeFiles/server-context.dir/server-context.cpp.o
In file included from /Users/walid/DEV/llama.cpp/tools/server/server-context.cpp:2:
In file included from /Users/walid/DEV/llama.cpp/tools/server/server-context.h:3:
/Users/walid/DEV/llama.cpp/tools/server/server-http.h:72:18: error: no template named 'unordered_map' in namespace 'std'
    mutable std::unordered_map<std::string, handler_t> handlers;
            ~~~~~^
1 warning and 1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by abawany** [comment]
I am seeing a similar break on macos 15.7.x using the following build command: `cmake -B build && cmake --build build --config Release`. 

```
[ 59%] Building CXX object tools/server/CMakeFiles/server-context.dir/server-context.cpp.o
In file included from .../github.com/ggerganov/llama.cpp/tools/server/server-context.cpp:2:
In file included from .../github.com/ggerganov/llama.cpp/tools/server/server-context.h:3:
.../github.com/ggerganov/llama.cpp/tools/server/server-http.h:72:18: error: no template named 'unordered_map' in namespace 'std'
   72 |     mutable std::unordered_map<std::string, handler_t> handlers;
      |             ~~~~~^
```

edit: in my case, the last tag that compiles is `b9076` - `b9077` and onwards seem to fail as above.

**Comment by kanedev** [comment]
I solved the problem by adding the following line at the top of tools/server/server-http.h:
#include <unordered_map>

**Comment by abawany** [comment]
yes, this also fixed it for me .
