### PR TITLE
common: add `subproc.h` wrapper, disabled on android/ios

### PR DESCRIPTION
**Pull request by ngxson**
## Overview

Ref comment: https://github.com/ggml-org/llama.cpp/pull/26061#issuecomment-5074729197 , PTAL @max-krasnyansky 

Subprocess is now disabled on android and ios, as sandboxed env will block spawn() call anyway. Also blocked on wasm as it doesn't make much sense.

Note: disabling subprocess will also disable MTMD_VIDEO, as it needs to spawn ffmpeg to work

## Requirements

- I have read and agree with the [contributing guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md)
- AI usage disclosure: most of the code is AI-generated, but I validated and reviewed it manually

### CODE REVIEW

**Comment by ngxson** [comment]
@ggml-gh-bot review

**Review by max-krasnyansky — APPROVED** [review]
Looks good to me.

**Comment by max-krasnyansky** [comment]
@ggml-org/maintainers folks let's merge this otherwise the Android builds will keep failing

**Review by ServeurpersoCom — APPROVED** [review]

**Comment by ngxson** [comment]
running another review just in case I missed smth, will merge if there is no major problems

/bot review

**Comment by marcoStocchi** [comment]
Afaiu that call to 'posix_spawn_file_actions_addchdir_np' is also responsible for failing the build of llama.cpp on systems with GLIBC < 2.29 (tested this morning on a machine with RHEL 8.1 and gcc-toolset-14 installed). 

llama.cpp/tools/mtmd/../../vendor/sheredom/subprocess.h: In function ‘int subprocess_create_ex(const char* const*, int, const char* const*, const char*, subprocess_s*)’:
llama.cpp/tools/mtmd/../../vendor/sheredom/subprocess.h:1215:19: error: ‘posix_spawn_file_actions_addchdir_np’ was not declared in this scope; did you mean ‘posix_spawn_file_actions_addopen’?
 1215 |     posix_error = posix_spawn_file_actions_addchdir_np(&actions, process_cwd);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by catap** [comment]
I'd like to add that it brokes building on OpenBSD as well because here no `posix_spawn_file_actions_addchdir_np`.

**Comment by ngxson** [comment]
seems like most of the problems already have fixes on upstream, just not yet merged: https://github.com/sheredom/subprocess.h/pulls

**Comment by InconsolableCellist** [comment]
Also reporting `posix_spawn_file_actions_addchdir_np` required glibc >= 2.29 so it failed to build in my older sysroot (conda-forge 2.17). I was going to put in a `__GLIBC_PREREQ(2, 29)` and a fork+chdir+exec fallback but managed to upgrade my toolchain after hitting a time-wasting CPU-type issue in proxmox.

**Comment by ngxson** [comment]
@InconsolableCellist it should be fixed on latest master

**Comment by catap** [comment]
@ngxson the problem that `posix_spawn_file_actions_addchdir_np` and `posix_spawn_file_actions_addchdir` may not be supported by OS and without it, here no way to ask llama.cpp to use ffmpeg for example.

**Comment by catap** [comment]
I mean that OpenBSD hasn't got posix_spawn_file_actions_addchdir or friend and for now I see the only way to disable all subproccesses.

**Comment by ngxson** [comment]
@catap sorry I'm not familiar with openbsd. I took the fix from upstream PR: https://github.com/sheredom/subprocess.h/pull/102

if you have a better solution, please push as a PR upstream, and I'll temporary apply it to the version here

**Comment by catap** [comment]
@ngxson so far I see only one way to fix it is implement `posix_spawn_file_actions_addchdir`. Unfortently I have no capacity to do it. So, I can't promise.

From another hand, I think it is good idea to add a check that `posix_spawn_file_actions_addchdir` or `posix_spawn_file_actions_addchdir_np` exists, and use subprocess.h only when it does.
