### ISSUE TITLE
Compile bug:  llama.cpp does not build with VULKAN backend

### ISSUE THREAD

**Issue by clort81** [ggml-org/llama.cpp#16054]
### Git commit

Git commit

git clone https://github.com/ggml-org/llama.cpp.git
Operating systems

Linux
GGML backends
Vulkan

Problem description & steps to reproduce

I'm trying to compile llama.cpp with vulkan support.  Multiple linux distros, but mainly debian sid-based without systemd.

cmake -B build -DGGML_VULKAN=ON
cmake --build build

First Bad Commit

No response

Compile command

cmake -B build -DGGML_VULKAN=ON
cmake --build build

`~/Projects/llama.cpp/build$ make
[  3%] Built target ggml-base
[  4%] Performing build step for 'vulkan-shaders-gen'
[100%] Built target vulkan-shaders-gen
[  4%] Performing install step for 'vulkan-shaders-gen'
-- Up-to-date: /home/lavurn/Projects/llama.cpp/build/Release/./vulkan-shaders-gen
[  4%] Completed 'vulkan-shaders-gen'
[  6%] Built target vulkan-shaders-gen
[  6%] Building CXX object ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp: In function ‘void ggml_vk_print_gpu_info(size_t)’:
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4361:5: error: ‘VkPhysicalDeviceCooperativeMatrixFeaturesKHR’ was not declared in this scope; did you mean ‘VkPhysicalDeviceCooperativeMatrixFeaturesNV’?
 4361 |     VkPhysicalDeviceCooperativeMatrixFeaturesKHR coopmat_features;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     VkPhysicalDeviceCooperativeMatrixFeaturesNV
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4362:5: error: ‘coopmat_features’ was not declared in this scope
 4362 |     coopmat_features.pNext = nullptr;
      |     ^~~~~~~~~~~~~~~~
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4363:30: error: ‘VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR’ was not declared in this scope; did you mean ‘VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_NV’?
 4363 |     coopmat_features.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_NV
make[2]: *** [ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/build.make:223: ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2279: ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
`

llama.cpp does not build with vulkan backend on multiple tested current linux distros.  

### Operating systems

Linux

### GGML backends

Vulkan

### Problem description & steps to reproduce

git clone https://github.com/ggml-org/llama.cpp.git
Operating systems

Linux
GGML backends
Vulkan

Problem description & steps to reproduce

I'm trying to compile llama.cpp with vulkan support.  Multiple linux distros, but mainly debian sid-based without systemd.

cmake -B build -DGGML_VULKAN=ON
cmake --build build

First Bad Commit

No response

Compile command

cmake -B build -DGGML_VULKAN=ON
cmake --build build

`~/Projects/llama.cpp/build$ make
[  3%] Built target ggml-base
[  4%] Performing build step for 'vulkan-shaders-gen'
[100%] Built target vulkan-shaders-gen
[  4%] Performing install step for 'vulkan-shaders-gen'
-- Up-to-date: /home/lavurn/Projects/llama.cpp/build/Release/./vulkan-shaders-gen
[  4%] Completed 'vulkan-shaders-gen'
[  6%] Built target vulkan-shaders-gen
[  6%] Building CXX object ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp: In function ‘void ggml_vk_print_gpu_info(size_t)’:
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4361:5: error: ‘VkPhysicalDeviceCooperativeMatrixFeaturesKHR’ was not declared in this scope; did you mean ‘VkPhysicalDeviceCooperativeMatrixFeaturesNV’?
 4361 |     VkPhysicalDeviceCooperativeMatrixFeaturesKHR coopmat_features;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     VkPhysicalDeviceCooperativeMatrixFeaturesNV
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4362:5: error: ‘coopmat_features’ was not declared in this scope
 4362 |     coopmat_features.pNext = nullptr;
      |     ^~~~~~~~~~~~~~~~
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4363:30: error: ‘VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR’ was not declared in this scope; did you mean ‘VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_NV’?
 4363 |     coopmat_features.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_NV
make[2]: *** [ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/build.make:223: ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2279: ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
`

### Compile command

```shell
git clone https://github.com/ggml-org/llama.cpp.git
Operating systems

Linux
GGML backends
Vulkan

Problem description & steps to reproduce

I'm trying to compile llama.cpp with vulkan support.  Multiple linux distros, but mainly debian sid-based without systemd.

cmake -B build -DGGML_VULKAN=ON
cmake --build build

First Bad Commit

No response

Compile command

cmake -B build -DGGML_VULKAN=ON
cmake --build build

`~/Projects/llama.cpp/build$ make
[  3%] Built target ggml-base
[  4%] Performing build step for 'vulkan-shaders-gen'
[100%] Built target vulkan-shaders-gen
[  4%] Performing install step for 'vulkan-shaders-gen'
-- Up-to-date: /home/lavurn/Projects/llama.cpp/build/Release/./vulkan-shaders-gen
[  4%] Completed 'vulkan-shaders-gen'
[  6%] Built target vulkan-shaders-gen
[  6%] Building CXX object ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp: In function ‘void ggml_vk_print_gpu_info(size_t)’:
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4361:5: error: ‘VkPhysicalDeviceCooperativeMatrixFeaturesKHR’ was not declared in this scope; did you mean ‘VkPhysicalDeviceCooperativeMatrixFeaturesNV’?
 4361 |     VkPhysicalDeviceCooperativeMatrixFeaturesKHR coopmat_features;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     VkPhysicalDeviceCooperativeMatrixFeaturesNV
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4362:5: error: ‘coopmat_features’ was not declared in this scope
 4362 |     coopmat_features.pNext = nullptr;
      |     ^~~~~~~~~~~~~~~~
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4363:30: error: ‘VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR’ was not declared in this scope; did you mean ‘VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_NV’?
 4363 |     coopmat_features.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_NV
make[2]: *** [ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/build.make:223: ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2279: ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
`
```

### Relevant log output

```shell
git clone https://github.com/ggml-org/llama.cpp.git
Operating systems

Linux
GGML backends
Vulkan

Problem description & steps to reproduce

I'm trying to compile llama.cpp with vulkan support.  Multiple linux distros, but mainly debian sid-based without systemd.

cmake -B build -DGGML_VULKAN=ON
cmake --build build

First Bad Commit

No response

Compile command

cmake -B build -DGGML_VULKAN=ON
cmake --build build

`~/Projects/llama.cpp/build$ make
[  3%] Built target ggml-base
[  4%] Performing build step for 'vulkan-shaders-gen'
[100%] Built target vulkan-shaders-gen
[  4%] Performing install step for 'vulkan-shaders-gen'
-- Up-to-date: /home/lavurn/Projects/llama.cpp/build/Release/./vulkan-shaders-gen
[  4%] Completed 'vulkan-shaders-gen'
[  6%] Built target vulkan-shaders-gen
[  6%] Building CXX object ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp: In function ‘void ggml_vk_print_gpu_info(size_t)’:
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4361:5: error: ‘VkPhysicalDeviceCooperativeMatrixFeaturesKHR’ was not declared in this scope; did you mean ‘VkPhysicalDeviceCooperativeMatrixFeaturesNV’?
 4361 |     VkPhysicalDeviceCooperativeMatrixFeaturesKHR coopmat_features;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     VkPhysicalDeviceCooperativeMatrixFeaturesNV
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4362:5: error: ‘coopmat_features’ was not declared in this scope
 4362 |     coopmat_features.pNext = nullptr;
      |     ^~~~~~~~~~~~~~~~
/home/lavurn/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4363:30: error: ‘VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR’ was not declared in this scope; did you mean ‘VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_NV’?
 4363 |     coopmat_features.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_NV
make[2]: *** [ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/build.make:223: ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2279: ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
`
```

**Comment by clort81** [comment]
Grabbed the vulkan sdk 1.4.321.1
https://vulkan.lunarg.com/doc/sdk/1.4.321.1/linux/getting_started.html
du -sh . // 1.8G

Out of that 1.8G, what header files do i need to put, where?

**Comment by clort81** [comment]
Copied vulkan sdk include/* to /usr/local/include

Building now works.  Closing
