### PR TITLE
Fix for issue #13170

### LINKED ISSUE #13170: Compile bug: Build fails on ppc64le
### Git commit

commit 5f5e39e1ba5dbea814e41f2a15e035d749a520bc (HEAD -> master, tag: b5215, origin/master, origin/HEAD)

### Operating systems

Mac, Linux

### GGML backends

CPU

### Problem description & steps to reproduce

While trying to build llama.cpp on ppc64le, build fails with compilation errors. 

### First Bad Commit

commit c6e8cc28c15166dba15629dba6a7366d4d5955ca
Author: Acly <aclysia@gmail.com>
Date:   Thu Apr 17 14:16:45 2025 +0200

    ggml : Depthwise 2D convolution (ggml/1152)
    
    * ggml-cpu : kernels for faster depthwise 2D convolution
    
    * fix compile: remove static after moving to ops.cpp
    
    * add dilation for depthwise_conv_2d
    
    * review: rename to ggml_conv_2d_dw_direct, remove redundant struct keywords, pass by ref, whitespace
    
    * review: rename depthwise_conv_2d -> conv_2d_dw everywhere

### Compile command

```shell
cmake -B <build_dir> -DLLAMA_CURL=OFF
cmake --build <build_dir>
```

### Relevant log output

```shell
lama.cpp/ggml/src/ggml-cpu/simd-mappings.h:344:33: error: cannot convert ‘float’ to ‘__vector float’ {aka ‘__vector(4) float’} in initialization
  344 | #define GGML_F32x4_ZERO         0.0f
      |                                 ^~~~
      |                                 |
      |                                 float
llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:372:29: note: in expansion of macro ‘GGML_F32x4_ZERO’
  372 | #define GGML_F32_VEC_ZERO   GGML_F32x4_ZERO
      |                             ^~~~~~~~~~~~~~~
llama.cpp/ggml/src/ggml-cpu/ops.cpp:6120:36: note: in expansion of macro ‘GGML_F32_VEC_ZERO’
 6120 |                 GGML_F32_VEC sum = GGML_F32_VEC_ZERO;
      |                                    ^~~~~~~~~~~~~~~~~
gmake[2]: *** [ggml/src/CMakeFiles/ggml-cpu.dir/build.make:233: ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ops.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2154: ggml/src/CMakeFiles/ggml-cpu.dir/all] Error 2
```

### PR DESCRIPTION
**Pull request by shalinib-ibm**
Build fails with compilation error on power pc.
This patch fixes the same.

Tested with unit tests run via
 cmake --build <build_dir> && cd <build_dir> && make test

*Make sure to read the [contributing guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md) before submitting a PR*

### CODE REVIEW

**Comment by shalinib-ibm** [comment]
@slaren After the addition of faster depth wise 2D kernels in ggml-cpu with this commit, https://github.com/ggml-org/llama.cpp/commit/c6e8cc28c15166dba15629dba6a7366d4d5955ca, we see that build fails with compilation error on power pc . This patch fixes the same. can you please review this PR ?

**Comment by CISC** [comment]
@shalinib-ibm Any chance of adding PPC to the CI build to more easily catch this in the future?

**Comment by shalinib-ibm** [comment]
@CISC agree that it would be nice to have some sort of CI for power arch. Will have to work on it.

**Review by slaren — COMMENTED** [review]
Can you explain why this change is necessary? There are other cases where `GGML_F32_VEC` is used as a single scalar instead of an array, so it is not clear to me why this is necessary here.

**Comment by slaren** [comment]
> GGML_F32_VEC sum[GGML_F32_ARR] = { GGML_F32_VEC_ZERO };

With AVX2 this expands to `__mm256 sum[4] = { _mm256_setzero_ps() };`, which does not look right to me, it is only initializing the first element with `_mm256_setzero_ps()`.

In any case, it seems to me that the solution would to define `GGML_F32_VEC_ZERO` to `{0.0f}` for this architecture, rather than just `0`, since it is meant to initialize entire vectors.

**Comment by shalinib-ibm** [comment]
Hi slaren, 
{ __m256_setzero_ps() } : This is the initializer  for the sum[4] array.  In C/C++, when an array is partially initialised, the remaining elements are automatically set to zero.  With AVX2, sum[0]  is explicitly initialised to a 256 bit register with all 8 floats set to 0.0f. The remaining elements sum[1], sum[2], sum[3] are implicitly initialized to zero. 

As per your suggestion,  I have defined GGML_F32_VEC_ZERO to {0.0f} for power. Can you please review ?

**Review by slaren — APPROVED** [review]
