### PR TITLE
CUDA: fix sm_70 tile compilation error

### LINKED ISSUE #29222: Compile bug: Build error with sm_70 on Windows 11
### Git commit

1884824fdaeb19af27cd8ba0ca50fcbed28eca44

### Operating systems

Windows

### GGML backends

CUDA

### Problem description & steps to reproduce

Compiling with CUDA sm_70 on Windows 11 fails (V100, CUDA 12.9). The failing target is fattn.cu.obj; the error is reported in fattn-mma-f16.cuh, which is included by fattn.cu. load_ldmatrix has no matching overload for the Volta tile tile<8, 4, half2, I_MAJOR_MIRRORED>. The 5-argument load_ldmatrix overload added in 1884824fd is only defined for tile<16, 8>, so the Volta tile<8, 4> does not match. Before that commit, the wrapper in fattn-swizzle.cuh handled any tile shape on the non-swizzled path, and the refactor in 1884824fd dropped that path. I checked the other architectures and only sm70 is affected. CI does not build sm70, so it was not caught.

### First Bad Commit

1884824fdaeb19af27cd8ba0ca50fcbed28eca44

### Compile command

```shell
cmake -S . -B build -G "Ninja Multi-Config" -DGGML_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES="70-real;89-real" -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_EXAMPLES=OFF
cmake --build build --config Release --target llama-server
```

### Relevant log output

```shell
FAILED: [code=1] ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/Release/fattn.cu.obj
D:\...\ggml\src\ggml-cuda\fattn-mma-f16.cuh(683): error: no instance of overloaded function "load_ldmatrix" matches the argument list
            argument types are: (ggml_cuda_mma::tile<8, 4, half2, ggml_cuda_mma::DATA_LAYOUT_I_MAJOR_MIRRORED>, half2 *const __restrict__, const int, int, const int)
                      load_ldmatrix<swz>(K_A, tile_K, i_KQ_0, k_KQ_0 - k0_start, stride_tile_K);
                      ^
D:\...\ggml\src\ggml-cuda\mma.cuh(877): note #3327-D: candidate function template "ggml_cuda_mma::load_ldmatrix<swz,T,dl>(tile<16, 8, T, dl> &, const T *, int, int, int)" failed deduction
```

### LINKED ISSUE #29223: Compile bug: Cant build current git 6f41ac59e0a49a00483a316a22ada6b04edd2950
### Git commit

6f41ac59e0a49a00483a316a22ada6b04edd2950

### Operating systems

Linux

### GGML backends

CUDA

### Problem description & steps to reproduce

I'm trying to build commit listed, and it has 96 errors and stops/errors out

### First Bad Commit

_No response_

### Compile command

```shell
cmake -B build -DGGML_CUDA=ON -DGGML_CUDA_FA_QUANTS=all -DGGML_VULKAN=ON -DBUILD_SHARED_LIBS=OFF -DLLAMA_BUILD_UI=ON -DGGML_CUDA_NCCL=ON -DCMAKE_CUDA_FLAGS=-Wno-deprecated-gpu-targets
cmake --build build --config Release -j 16

Building on Linux Mint 22.3 (Ubuntu 24.04 based) GPU is a Nvidia Tesla V100 32GB (Volta)
```

### Relevant log output

```shell
/home/lemonzest/Temp/llama.cpp/ggml/src/ggml-cuda/mma.cuh(877): note #3327-D: candidate function template "ggml_cuda_mma::load_ldmatrix<swz,T,dl>(ggml_cuda_mma::tile<16, 8, T, dl> &, const T *, int, int, int)" failed deduction
                                       void load_ldmatrix(
                                            ^
          detected during:
            instantiation of "void flash_attn_ext_f16_iter<DKQ,DV,ncols1,ncols2,nwarps,use_logit_softcap,V_is_K_view,use_sparse,needs_fixup,is_fixup,last_iter,oob_check,T_A_KQ,T_B_KQ,T_C_KQ,T_A_VKQ,T_B_VKQ,T_C_VKQ>(const float2 *, const half2 *, const half2 *, const half *, const int32_t *, float2 *, float2 *, float, float, float, uint3, int, int, int, int, half2 *, half2 *, half2 *, half *, T_B_KQ *, T_C_VKQ *, float *, float *, int, int, int) [with DKQ=576, DV=512, ncols1=2, ncols2=4, nwarps=2, use_logit_softcap=true, V_is_K_view=true, use_sparse=false, needs_fixup=false, is_fixup=true, last_iter=true, oob_check=false, T_A_KQ=ggml_cuda_mma::tile<8, 4, half2, ggml_cuda_mma::DATA_LAYOUT_I_MAJOR_MIRRORED>, T_B_KQ=ggml_cuda_mma::tile<32, 4, half2, ggml_cuda_mma::DATA_LAYOUT_I_MAJOR>, T_C_KQ=ggml_cuda_mma::tile<32, 8, float, ggml_cuda_mma::DATA_LAYOUT_I_MAJOR>, T_A_VKQ=ggml_cuda_mma::tile<8, 4, half2, ggml_cuda_mma::DATA_LAYOUT_J_MAJOR_MIRRORED>, T_B_VKQ=ggml_cuda_mma::tile<32, 4, half2, ggml_cuda_mma::DATA_LAYOUT_I_MAJOR>, T_C_VKQ=ggml_cuda_mma::tile<32, 4, half2, ggml_cuda_mma::DATA_LAYOUT_I_MAJOR>]" at line 1398
            instantiation of "void flash_attn_ext_f16_process_tile<DKQ,DV,ncols1,ncols2,nwarps,use_logit_softcap,V_is_K_view,use_sparse,needs_fixup,is_fixup>(const float2 *, const half2 *, const half2 *, const half *, const int32_t *, const float *, float2 *, float2 *, float, float, float, uint3, int, int, int, int, int, int, int, int, int, int, int, int) [with DKQ=576, DV=512, ncols1=2, ncols2=4, nwarps=2, use_logit_softcap=true, V_is_K_view=true, use_sparse=false, needs_fixup=false, is_fixup=true]" at line 1999
            instantiation of "void flash_attn_ext_f16<DKQ,DV,ncols1,ncols2,use_logit_softcap,V_is_K_view,use_sparse>(const char *, const char *, const char *, const char *, const char *, const int *, float *, float2 *, float, float, float, float, uint32_t, float, int32_t, uint3, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int64_t, int32_t, int32_t, int64_t, int32_t, int32_t, int32_t, int32_t, int32_t, int64_t) [with DKQ=576, DV=512, ncols1=2, ncols2=4, use_logit_softcap=true, V_is_K_view=true, use_sparse=false]" at line 2105
            instantiation of "void ggml_cuda_flash_attn_ext_mma_f16_case<DKQ,DV,ncols1,ncols2>(ggml_backend_cuda_context &, ggml_tensor *) [with DKQ=576, DV=512, ncols1=2, ncols2=4]" at line 160 of /home/lemonzest/Temp/llama.cpp/ggml/src/ggml-cuda/fattn.cu
            instantiation of "void ggml_cuda_flash_attn_ext_mma_f16_switch_ncols1<DKQ,DV,ncols2>(ggml_backend_cuda_context &, ggml_tensor *) [with DKQ=576, DV=512, ncols2=4]" at line 362 of /home/lemonzest/Temp/llama.cpp/ggml/src/ggml-cuda/fattn.cu

96 errors detected in the compilation of "/home/lemonzest/Temp/llama.cpp/ggml/src/ggml-cuda/fattn.cu".
```

### PR DESCRIPTION
**Pull request by lingyezhixing**
## Overview

Fixes #29222.

The 5-argument `load_ldmatrix` added in 1884824fd only defined `tile<16, 8>`, so the Volta `tile<8, 4>` used by sm_70 had no matching overload and `fattn.cu` failed to compile.

This PR generalizes the 5-argument `load_ldmatrix` tile shape from `<16, 8>` to `<I, J>`. The non-swizzle branch forwards to the 3-argument loader, so any tile shape works. The swizzle branch is restricted to `<16, 8>` with newly added `static_assert(I == 16)` / `static_assert(J == 8)`.

This follows the existing pattern of `load_ldmatrix_trans` in the same file, which is already shape-generic plus `static_assert(I == 16)`.

Only sm70 was affected; other architectures were checked. CI does not build sm70, so this was not caught.

Local compile and test passed.

## Requirements

- I have read and agree with the [contributing guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md)
- AI usage disclosure: YES — Used DeepSeek V4.1 Flash (OpenCode) for code assistance. I have manually reviewed and fully understand every line of the submitted code.

### CODE REVIEW

**Review by JohannesGaessler — APPROVED** [review]

**Comment by lingyezhixing** [comment]
@ggml-bot AI assisted me with troubleshooting and code changes, but the issue, PR description, and PR commit were written by me. My native language is not English, so I used AI for translation.
