### ISSUE TITLE
Compile bug: error: use of undeclared identifier 'getenv'/'atoi'

### ISSUE THREAD

**Issue by peppergrayxyz** [ggml-org/llama.cpp#28559]
### Git commit

e71b80510c848c00175924ecf3c40333ccae8eb5

### Operating systems

Linux

### GGML backends

AMX, BLAS, CANN, CPU, CUDA, Hexagon, HIP, Metal, Musa, OpenCL, OpenVINO, RPC, SYCL, Vulkan, VirtGPU, WebGPU, zDNN, ZenDNN

### Problem description & steps to reproduce

I'm on Gentoo arm64 using clang+musl

```
$ git clone https://github.com/ggml-org/llama.cpp
$ cd llama.cpp
$ cmake -B build
$ cmake --build build --config Release
```

### First Bad Commit

fb15d649ed14ab447eeab911e0c9d21e35fb243e

### Compile command

```shell
cmake --build build --config Release
```

### Relevant log output

```shell
In file included from /home/pepper/dev/ghrepos/llama.cpp/src/llama.cpp:7:
In file included from /home/pepper/dev/ghrepos/llama.cpp/src/llama-context.h:6:
/home/pepper/dev/ghrepos/llama.cpp/src/llama-graph.h:103:48: error: use of undeclared identifier 'getenv'
  103 |         const char * LLAMA_GRAPH_INPUT_DEBUG = getenv("LLAMA_GRAPH_INPUT_DEBUG");
      |                                                ^~~~~~
/home/pepper/dev/ghrepos/llama.cpp/src/llama-graph.h:104:43: error: use of undeclared identifier 'atoi'
  104 |         debug = LLAMA_GRAPH_INPUT_DEBUG ? atoi(LLAMA_GRAPH_INPUT_DEBUG) : 0;
      |                                           ^~~~
2 errors generated.
```

**Comment by peppergrayxyz** [comment]
`#include <cstdlib>` is missing in `src/llama-graph.h`
