### ISSUE TITLE
Compile bug: llama.cpp/common/../vendor/sheredom/subprocess.h:234:10: fatal error: 'spawn.h' file not found

### ISSUE THREAD

**Issue by Matmat3659** [ggml-org/llama.cpp#19388]
### Git commit

❯ git rev-parse HEAD
1946e46f4c29da7b9294d702756969839e922bb8

### Operating systems

Other? (Please let us know in description)

### GGML backends

CPU

### Problem description & steps to reproduce

I am trying to build llama.cpp on termux, android 9 pie, armv8l(emulated armv7 on armv8 cpu)
``` fastfetch
OS: Android REL 9 armv8l
Host: Samsung tablet
Kernel: Linux 3.18.91
Packages: 144 (dpkg)
Shell: zsh 5.9
DE: Android build
WM: WindowManager
Terminal: Termux 0.118.3
CPU: 2 x Cortex-A53*8 (8)
GPU: Mali-T830 [Integrated]
Locale: en_US.UTF-8
```
The problem is Platform specific by what it looks like
```
[ 60%] Linking CXX executable ../bin/test-chat-parser
[ 60%] Built target test-chat-parser
[ 61%] Building CXX object tests/CMakeFiles/test-chat-peg-parser.dir/peg-parser/simple-tokenize.cpp.o
[ 61%] Building CXX object tests/CMakeFiles/test-jinja.dir/test-jinja.cpp.o
23 warnings generated.
[ 62%] Building CXX object tests/CMakeFiles/test-chat-template.dir/get-model.cpp.o
[ 62%] Linking CXX executable ../bin/test-chat-template
[ 62%] Built target test-chat-template
[ 62%] Building CXX object tests/CMakeFiles/test-chat-peg-parser.dir/get-model.cpp.o
[ 62%] Building CXX object tests/CMakeFiles/test-jinja.dir/get-model.cpp.o
[ 62%] Building CXX object tests/CMakeFiles/test-json-partial.dir/test-json-partial.cpp.o
In file included from /data/data/com.termux/files/home/skyex/temp/llama.cpp/tests/test-jinja.cpp:7:
/data/data/com.termux/files/home/skyex/temp/llama.cpp/common/../vendor/sheredom/subprocess.h:234:10: fatal error: 'spawn.h' file not found
  234 | #include <spawn.h>
      |          ^~~~~~~~~
1 error generated.
make[2]: *** [tests/CMakeFiles/test-jinja.dir/build.make:79: tests/CMakeFiles/test-jinja.dir/test-jinja.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2991: tests/CMakeFiles/test-jinja.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 63%] Building CXX object tests/CMakeFiles/test-json-partial.dir/get-model.cpp.o
[ 63%] Linking CXX executable ../bin/test-json-partial
[ 63%] Built target test-json-partial
[ 63%] Linking CXX executable ../bin/test-chat-peg-parser
[ 63%] Built target test-chat-peg-parser
[ 64%] Linking CXX executable ../bin/test-chat
[ 64%] Built target test-chat
make: *** [Makefile:146: all] Error 2
```

### First Bad Commit

Unknow

### Compile command

```shell
(I tried to turn of tests but i dont know which or how to)
cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=softfp -O3 -funsafe-math-optimizations -funroll-loops -ftree-vectorize -fomit-frame-pointer -fstrict-aliasing -fopenmp=libomp" -DCMAKE_CXX_FLAGS="-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=softfp -O3 -funsafe-math-optimizations -funroll-loops -ftree-vectorize -fomit-frame-pointer -fstrict-aliasing -fopenmp=libomp" -DCMAKE_EXE_LINKER_FLAGS="-Wl,--gc-sections -fopenmp=libomp" -DGGML_OPENMP=ON -DGGML_STATIC_OPENMP=ON -DGGML_BUILD_TESTS=OFF
```

### Relevant log output

```shell
❯ cmake --build build --config Release -j4
[  0%] Built target build_info
[  0%] Built target sha256                                                                                                                                                            [  0%] Built target cpp-httplib                                                                                                                                                       [  1%] Built target xxhash                                                                                                                                                            [  1%] Built target sha1                                                                                                                                                              [  3%] Built target ggml-base                                                                                                                                                         [  4%] Built target llama-llava-cli
[  4%] Built target llama-gemma3-cli
[  5%] Built target llama-minicpmv-cli
[  6%] Built target llama-qwen2vl-cli
[ 10%] Built target ggml-cpu
[ 11%] Built target ggml
[ 12%] Built target llama-gguf-hash
[ 12%] Built target llama-gguf
[ 43%] Built target llama
[ 44%] Built target test-c
[ 45%] Built target llama-simple
[ 45%] Built target llama-simple-chat
[ 49%] Built target mtmd
[ 56%] Built target common
[ 56%] Built target test-sampling
[ 56%] Built target test-tokenizer-0
[ 57%] Built target test-grammar-parser
[ 58%] Built target test-grammar-integration
[ 59%] Built target test-chat
[ 60%] Built target test-llama-grammar
[ 60%] Built target test-json-schema-to-grammar
[ 60%] Built target test-quantize-stats
[ 60%] Built target test-tokenizer-1-spm
[ 60%] Built target test-gbnf-validator
[ 61%] Built target test-tokenizer-1-bpe
[ 61%] Built target test-chat-parser
[ 61%] Building CXX object tests/CMakeFiles/test-jinja.dir/test-jinja.cpp.o
[ 62%] Built target test-chat-template
[ 63%] Built target test-chat-peg-parser
[ 64%] Built target test-json-partial
[ 65%] Building CXX object tests/CMakeFiles/test-log.dir/test-log.cpp.o
[ 65%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/test-peg-parser.cpp.o
[ 66%] Building CXX object tests/CMakeFiles/test-regex-partial.dir/test-regex-partial.cpp.o
[ 66%] Building CXX object tests/CMakeFiles/test-log.dir/get-model.cpp.o
[ 66%] Linking CXX executable ../bin/test-log
[ 66%] Built target test-log
[ 66%] Building CXX object tests/CMakeFiles/test-thread-safety.dir/test-thread-safety.cpp.o
In file included from /data/data/com.termux/files/home/skyex/temp/llama.cpp/tests/test-jinja.cpp:7:
/data/data/com.termux/files/home/skyex/temp/llama.cpp/common/../vendor/sheredom/subprocess.h:234:10: fatal error: 'spawn.h' file not found
  234 | #include <spawn.h>
      |          ^~~~~~~~~
1 error generated.
make[2]: *** [tests/CMakeFiles/test-jinja.dir/build.make:79: tests/CMakeFiles/test-jinja.dir/test-jinja.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2991: tests/CMakeFiles/test-jinja.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 66%] Building CXX object tests/CMakeFiles/test-regex-partial.dir/get-model.cpp.o
[ 67%] Building CXX object tests/CMakeFiles/test-thread-safety.dir/get-model.cpp.o
[ 68%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/peg-parser/simple-tokenize.cpp.o
[ 68%] Linking CXX executable ../bin/test-regex-partial
[ 68%] Built target test-regex-partial
[ 68%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/peg-parser/test-basic.cpp.o
[ 68%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/peg-parser/test-gbnf-generation.cpp.o
[ 68%] Linking CXX executable ../bin/test-thread-safety
[ 68%] Built target test-thread-safety
[ 68%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/peg-parser/test-json-parser.cpp.o
[ 69%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/peg-parser/test-json-serialization.cpp.o
[ 69%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/peg-parser/test-unicode.cpp.o
[ 69%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/get-model.cpp.o
```

**Comment by taronaeo** [comment]
This problem originates from a vendor file. Please file a report upstream instead.

https://github.com/sheredom/subprocess.h

**Comment by ardorleo** [comment]
[ 80%] Built target llama-simple-chat
In file included from /extdatas/systools/build_workpace/llama.cpp/llama.cpp/common/subproc.h:9,
                 from /extdatas/systools/build_workpace/llama.cpp/llama.cpp/common/subproc.cpp:1:
/extdatas/systools/build_workpace/llama.cpp/llama.cpp/common/../vendor/sheredom/subprocess.h: In function ‘int subprocess_create_ex(const char* const*, int, const char* const*, const char*, subprocess_s*)’:
/extdatas/systools/build_workpace/llama.cpp/llama.cpp/common/../vendor/sheredom/subprocess.h:1215:19: error: ‘posix_spawn_file_actions_addchdir_np’ was not declared in this scope; did you mean ‘posix_spawn_file_actions_adddup2’?
 1215 |     posix_error = posix_spawn_file_actions_addchdir_np(&actions, process_cwd);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   posix_spawn_file_actions_adddup2
make[2]: *** [common/CMakeFiles/llama-common.dir/build.make:412：common/CMakeFiles/llama-common.dir/subproc.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1192：common/CMakeFiles/llama-common.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
In file included from /extdatas/systools/build_workpace/llama.cpp/llama.cpp/tools/mtmd/mtmd-helper.cpp:40:
/extdatas/systools/build_workpace/llama.cpp/llama.cpp/tools/mtmd/../../vendor/sheredom/subprocess.h: In function ‘int subprocess_create_ex(const char*const*, int, const char* const*, const char*, subprocess_s*)’:
/extdatas/systools/build_workpace/llama.cpp/llama.cpp/tools/mtmd/../../vendor/sheredom/subprocess.h:1215:19: error: ‘posix_spawn_file_actions_addchdir_np’ was not declared in this scope; did you mean ‘posix_spawn_file_actions_adddup2’?
 1215 |     posix_error = posix_spawn_file_actions_addchdir_np(&actions, process_cwd);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   posix_spawn_file_actions_adddup2
make[2]: *** [tools/mtmd/CMakeFiles/mtmd.dir/build.make:118：tools/mtmd/CMakeFiles/mtmd.dir/mtmd-helper.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:2928：tools/mtmd/CMakeFiles/mtmd.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2
