### PR TITLE
[SYCL] Fix compilation error from GGML_ASSERT

### PR DESCRIPTION
**Pull request by AidanBeltonS**
A small typo prevents compilation of the SYCL backend due to a missing " this was introduced in https://github.com/ggerganov/ggml/pull/814

### CODE REVIEW

**Review by abhilash1910 — APPROVED** [review]
LGTM!

**Review by airMeng — APPROVED** [review]
