### ISSUE TITLE
Misc. bug: llama-quant "found point XXX not on grid: XXXX"

### ISSUE THREAD

**Issue by Bobchenyx** [ggml-org/llama.cpp#14798]
### Name and Version

version: 5927 (349ea79f)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu

Apologize if I'm not using things correctly. 
I tried to play around with Qwen3 MoE using files from unsloth 
`unsloth/Qwen3-235B-A22B-GGUF` BF16 and imatrix

However I run into error when running IQ2_M. `Oops: found point 16712 not on grid: 0 2 0 1 1 0 0 1`

I would like to kindly ask if this is issue related to `Qwen` or is this `llama.cpp` issue? 

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-quantize

### Command line

```shell
build/bin/llama-quantize \
    --imatrix /home/user1/workspace/bobchenyx/unsloth/Qwen3-235B-A22B-GGUF/imatrix_unsloth.dat \
    --token-embedding-type Q8_0 \
    --output-tensor-type Q8_0 \
    /home/user1/workspace/bobchenyx/unsloth/Qwen3-235B-A22B-GGUF/BF16/Qwen3-235B-A22B-BF16-00001-of-00010.gguf \
    /home/user1/workspace/bobchenyx/Qwen3-235B-A22B-IQ2_M/Qwen3-235B-A22B-IQ2_M.gguf \
    IQ2_M \
    48 2>&1 | tee Qwen-MOE-IQ2_M.log
```

### Problem description & steps to reproduce

quantizing Qwen3 MoE with unsloth BF16 & imatrix

### First Bad Commit

Not sure

### Relevant log output

```shell
[ 254/1131]           blk.21.ffn_gate_inp.weight - [ 4096,   128,     1,     1], type =    f32, size =    2.000 MB
[ 255/1131]            blk.21.attn_k_norm.weight - [  128,     1,     1,     1], type =    f32, size =    0.000 MB
[ 256/1131]                 blk.21.attn_k.weight - [ 4096,   512,     1,     1], type =   bf16, converting to q4_K .. size =     4.00 MiB ->     1.12 MiB
[ 257/1131]            blk.21.attn_output.weight - [ 8192,  4096,     1,     1], type =   bf16, converting to q5_K .. size =    64.00 MiB ->    22.00 MiB
[ 258/1131]            blk.21.attn_q_norm.weight - [  128,     1,     1,     1], type =    f32, size =    0.000 MB
[ 259/1131]                 blk.21.attn_q.weight - [ 4096,  8192,     1,     1], type =   bf16, converting to iq2_s .. size =    64.00 MiB ->    10.25 MiB
[ 260/1131]                 blk.21.attn_v.weight - [ 4096,   512,     1,     1], type =   bf16, converting to q4_K .. size =     4.00 MiB ->     1.12 MiB
[ 261/1131]              blk.21.attn_norm.weight - [ 4096,     1,     1,     1], type =    f32, size =    0.016 MB
[ 262/1131]          blk.21.ffn_down_exps.weight - [ 1536,  4096,   128,     1], type =   bf16, converting to iq2_s .. Oops: found point 16712 not on grid: 0 2 0 1 1 0 0 1
/home/user1/workspace/llm-work/bobchenyx/llama.cpp/ggml/src/ggml-quants.c:4881: fatal error
[New LWP 1839493]
[New LWP 1839515]
[New LWP 1839521]
[New LWP 1839527]
[New LWP 1839528]
[New LWP 1839529]
[New LWP 1839530]
[New LWP 1839531]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x000070cb300ea42f in __GI___wait4 (pid=1942468, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
#0  0x000070cb300ea42f in __GI___wait4 (pid=1942468, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x000059bddc36988b in ggml_print_backtrace ()
#2  0x000059bddc369a1e in ggml_abort ()
#3  0x000059bddc3a5aa0 in quantize_row_iq2_s_impl ()
#4  0x000059bddc3c0091 in quantize_iq2_s ()
#5  0x000059bddc37d0c6 in ggml_quantize_chunk ()
#6  0x000059bddbed8929 in llama_model_quantize_impl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, llama_model_quantize_params const*) ()
#7  0x000059bddbedaf44 in llama_model_quantize ()
#8  0x000059bddbdddc00 in main ()
[Inferior 1 (process 1839491) detached]
Aborted (core dumped)
```

**Comment by MengAiDev** [comment]
Maybe you can use: Q4_K_M ?

**Comment by danielhanchen** [comment]
Yes unfortunately we encountered the same issue for https://huggingface.co/unsloth/Qwen3-235B-A22B-GGUF as well

In the end, we had to delete broken GGUFs.

The only ones supported at https://huggingface.co/unsloth/Qwen3-235B-A22B-Instruct-2507-GGUF are the below:

<img width="978" height="939" alt="Image" src="https://github.com/user-attachments/assets/f4c9c2d9-78ba-4c90-b2e9-e0e4c1bb361a" />

Note all use the dynamic 2 methodology and all uses the imatrix calibration process.

**Comment by MengAiDev** [comment]
I tried to use qwen3 0.6B, but there isn't any bugs. Here are two logs. It seemed that the error only work on MOE model? 

[quantize_iq2m.log](https://github.com/user-attachments/files/21377525/quantize_iq2m.log)
[quantize_q4km.log](https://github.com/user-attachments/files/21377526/quantize_q4km.log)

**Comment by Bobchenyx** [comment]
@danielhanchen Thanks for this reply and for confirming the "bug". 

I'm not sure if this is related to the new update they have with this `imatrix` stuff recently. I remember encountering this issue last week.

**Comment by danielhanchen** [comment]
Nah it's not the `imatrix` changes since the old path also has this issue. Yes it's an inherent issue of MoEs it seems
