### ISSUE TITLE
Compile bug: vulkan set_rows seems broken

### ISSUE THREAD

**Issue by 414n** [ggml-org/llama.cpp#14971]
### Git commit

a118d80233d3bf92569c051346fd2638f87bf202

### Operating systems

Linux

### GGML backends

Vulkan

### Problem description & steps to reproduce

I'm trying to compile llama.cpp with vulkan support on a Slackware64-15.0 system with updated kernel (6.14.9), mesa (25.1.2) and vulkan-sdk (1.4.313).

[CMakeCache.txt](https://github.com/user-attachments/files/21513365/CMakeCache.txt)

### First Bad Commit

b3ad3a0191994d6c47b2bd389d5c7431526ecd2c

### Compile command

```shell
make -C build
```

### Relevant log output

```shell
/data/toshi/ai/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:11403:37: error: too few arguments to function ‘ggml_tensor* ggml_set_rows(ggml_context*, ggml_tensor*, ggml_tensor*, ggml_tensor*)’
11403 |         tensor_clone = ggml_set_rows(ggml_ctx, src_clone[0], src_clone[1]);
      |                        ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /data/toshi/ai/llama.cpp/ggml/src/../include/ggml-vulkan.h:3,
                 from /data/toshi/ai/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:1:
/data/toshi/ai/llama.cpp/ggml/src/../include/ggml.h:1514:35: note: declared here
 1514 |     GGML_API struct ggml_tensor * ggml_set_rows(
      |                                   ^~~~~~~~~~~~~
```

**Comment by jeffbolznv** [comment]
This is being resolved in https://github.com/ggml-org/llama.cpp/pull/14899, but shouldn't affect "normal" builds.

**Comment by 414n** [comment]
I can confirm that applying the changes from #14899 fixes the original compilation issue.
Can't vouch for its correctness, though.

**Comment by 0cc4m** [comment]
Why are you compiling with debug flags?

**Comment by 414n** [comment]
I'm sorry, what debug flags are you referring to?

**Comment by jeffbolznv** [comment]
That code is only built if you enable the GGML_VULKAN_CHECK_RESULTS cmake setting, which is only meant for debugging (and is extremely slow)

**Comment by 414n** [comment]
You’re right, I likely enabled that build option by mistake and forgot about it.

Now that it’s turned off, everything seems to be working fine on my system.

**Comment by 0cc4m** [comment]
Great!
