### ISSUE TITLE
Compile bug: error: use of undeclared identifier 'posix_memalign'/'free'

### ISSUE THREAD

**Issue by peppergrayxyz** [ggml-org/llama.cpp#28560]
### Git commit

e71b80510c848c00175924ecf3c40333ccae8eb5

### Operating systems

Linux

### GGML backends

AMX, BLAS, CANN, CPU, CUDA, Hexagon, HIP, Metal, Musa, OpenCL, OpenVINO, SYCL, RPC, VirtGPU, Vulkan, WebGPU, zDNN, ZenDNN

### Problem description & steps to reproduce

I'm on Gentoo arm64 using clang+musl

```
$ git clone https://github.com/ggml-org/llama.cpp
$ cd llama.cpp
$ cmake -B build
$ cmake --build build --config Release
```

### First Bad Commit

4d4f4cacd1c18975e5a97f20369fc30a225dc51f

### Compile command

```shell
cmake --build build --config Release
```

### Relevant log output

```shell
/home/pepper/dev/ghrepos/llama.cpp/src/llama-mmap.cpp:326:19: error: use of undeclared identifier 'posix_memalign'
  326 |         int ret = posix_memalign(&raw_buffer, alignment, bytes_to_read);
      |                   ^~~~~~~~~~~~~~
/home/pepper/dev/ghrepos/llama.cpp/src/llama-mmap.cpp:332:47: error: use of undeclared identifier 'free'
  332 |             void operator()(void * p) const { free(p); }
      |                                               ^~~~
2 errors generated.
```

**Comment by peppergrayxyz** [comment]
`#include <cstdlib>` is missing in `src/llama-mmap.cpp`
