### ISSUE TITLE
Compile bug: server compilation broken after common rename

### ISSUE THREAD

**Issue by JohannesGaessler** [ggml-org/llama.cpp#22062]
### Git commit

45cac7ca703fb9085e

### Operating systems

Linux

### GGML backends

CPU

### Problem description & steps to reproduce

Compilation of the server is broken. Deleting ccache makes no difference.

[Full compilation log which is too long to be uploaded as a post.](https://github.com/user-attachments/files/26838706/tmp.txt)

### First Bad Commit

6990e2f1f7581d332a6

### Compile command

```shell
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build . -j 32
```

### Relevant log output

```shell
/home/johannesg/Projects/llama.cpp/tools/server/server-task.cpp: In member function ‘json server_task_result_cmpl_final::to_json_oaicompat()’:
/home/johannesg/Projects/llama.cpp/tools/server/server-task.cpp:795:44: error: ‘llama_build_info’ was not declared in this scope
  795 |         {"system_fingerprint", std::string(llama_build_info())},
      |                                            ^~~~~~~~~~~~~~~~
/home/johannesg/Projects/llama.cpp/tools/server/server-task.cpp:799:5: error: no matching function for call to ‘nlohmann::json_abi_v3_12_0::basic_json<nlohmann::json_abi_v3_12_0::ordered_map>::basic_json(<brace-enclosed initializer list>)’
  799 |     };
      |     ^
/home/johannesg/Projects/llama.cpp/tools/server/server-task.cpp:799:5: note: there are 10 candidates
In file included from /home/johannesg/Projects/llama.cpp/tools/server/server-common.h:10,
                 from /home/johannesg/Projects/llama.cpp/tools/server/server-task.h:12,
                 from /home/johannesg/Projects/llama.cpp/tools/server/server-task.cpp:1:
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:21163:5: note: candidate 1: ‘template<class JsonRef, typename std::enable_if<nlohmann::json_abi_v3_12_0::detail::conjunction<nlohmann::json_abi_v3_12_0::detail::is_json_ref<JsonRef>, std::is_same<typename JsonRef::value_type, nlohmann::json_abi_v3_12_0::basic_json<nlohmann::json_abi_v3_12_0::ordered_map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::json_abi_v3_12_0::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> > >::value, int>::type <anonymous> > nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::basic_json(const JsonRef&) [with typename std::enable_if<nlohmann::json_abi_v3_12_0::detail::conjunction<nlohmann::json_abi_v3_12_0::detail::is_json_ref<JsonRef>, std::is_same<typename JsonRef::value_type, nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass> > >::value, int>::type <anonymous> = JsonRef; ObjectType = nlohmann::json_abi_v3_12_0::ordered_map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_12_0::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void]’
21163 |     basic_json(const JsonRef& ref) : basic_json(ref.moved_or_copied()) {}
      |     ^~~~~~~~~~
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:21163:5: note: candidate expects 1 argument, 7 provided
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:21054:5: note: candidate 2: ‘template<class InputIT, typename std::enable_if<(std::is_same<IterImpl, nlohmann::json_abi_v3_12_0::detail::iter_impl<nlohmann::json_abi_v3_12_0::basic_json<nlohmann::json_abi_v3_12_0::ordered_map> > >::value || std::is_same<IterImpl, nlohmann::json_abi_v3_12_0::detail::iter_impl<const nlohmann::json_abi_v3_12_0::basic_json<nlohmann::json_abi_v3_12_0::ordered_map> > >::value), int>::type <anonymous> > nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::basic_json(InputIT, InputIT) [with typename std::enable_if<(std::is_same<InputIT, nlohmann::json_abi_v3_12_0::detail::iter_impl<nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass> > >::value || std::is_same<InputIT, nlohmann::json_abi_v3_12_0::detail::iter_impl<const nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass> > >::value), int>::type <anonymous> = InputIT; ObjectType = nlohmann::json_abi_v3_12_0::ordered_map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_12_0::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void]’
21054 |     basic_json(InputIT first, InputIT last) // NOLINT(performance-unnecessary-value-param)
      |     ^~~~~~~~~~
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:21054:5: note: candidate expects 2 arguments, 7 provided
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:20866:5: note: candidate 3: ‘template<class BasicJsonType, typename std::enable_if<(nlohmann::json_abi_v3_12_0::detail::is_basic_json<BasicJsonType>::value && (! std::is_same<nlohmann::json_abi_v3_12_0::basic_json<nlohmann::json_abi_v3_12_0::ordered_map>, BasicJsonType>::value)), int>::type <anonymous> > nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::basic_json(const BasicJsonType&) [with typename std::enable_if<(nlohmann::json_abi_v3_12_0::detail::is_basic_json<BasicJsonType>::value && (! std::is_same<nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>, BasicJsonType>::value)), int>::type <anonymous> = BasicJsonType; ObjectType = nlohmann::json_abi_v3_12_0::ordered_map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_12_0::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void]’
20866 |     basic_json(const BasicJsonType& val)
      |     ^~~~~~~~~~
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:20866:5: note: candidate expects 1 argument, 7 provided
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:20852:5: note: candidate 4: ‘template<class CompatibleType, class U, typename std::enable_if<((! nlohmann::json_abi_v3_12_0::detail::is_basic_json<T>::value) && nlohmann::json_abi_v3_12_0::detail::is_compatible_type<nlohmann::json_abi_v3_12_0::basic_json<nlohmann::json_abi_v3_12_0::ordered_map>, U>::value), int>::type <anonymous> > nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::basic_json(CompatibleType&&) [with U = CompatibleType; typename std::enable_if<((! nlohmann::json_abi_v3_12_0::detail::is_basic_json<U>::value) && nlohmann::json_abi_v3_12_0::detail::is_compatible_type<nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>, U>::value), int>::type <anonymous> = U; ObjectType = nlohmann::json_abi_v3_12_0::ordered_map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_12_0::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void]’
20852 |     basic_json(CompatibleType && val) noexcept(noexcept( // NOLINT(bugprone-forwarding-reference-overload,bugprone-exception-escape)
      |     ^~~~~~~~~~
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:20852:5: note: candidate expects 1 argument, 7 provided
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:21240:5: note: candidate 5: ‘nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::basic_json(nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>&&) [with ObjectType = nlohmann::json_abi_v3_12_0::ordered_map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_12_0::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void]’
21240 |     basic_json(basic_json&& other) noexcept
      |     ^~~~~~~~~~
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:21240:5: note: candidate expects 1 argument, 7 provided
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:21167:5: note: candidate 6: ‘nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::basic_json(const nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>&) [with ObjectType = nlohmann::json_abi_v3_12_0::ordered_map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_12_0::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void]’
21167 |     basic_json(const basic_json& other)
      |     ^~~~~~~~~~
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:21167:5: note: candidate expects 1 argument, 7 provided
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:21042:5: note: candidate 7: ‘nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::basic_json(size_type, const nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>&) [with ObjectType = nlohmann::json_abi_v3_12_0::ordered_map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_12_0::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void; size_type = long unsigned int]’
21042 |     basic_json(size_type cnt, const basic_json& val):
      |     ^~~~~~~~~~
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:21042:5: note: candidate expects 2 arguments, 7 provided
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:20924:5: note: candidate 8: ‘nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::basic_json(initializer_list_t, bool, value_t) [with ObjectType = nlohmann::json_abi_v3_12_0::ordered_map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_12_0::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void; initializer_list_t = std::initializer_list<nlohmann::json_abi_v3_12_0::detail::json_ref<nlohmann::json_abi_v3_12_0::basic_json<nlohmann::json_abi_v3_12_0::ordered_map> > >; value_t = nlohmann::json_abi_v3_12_0::detail::value_t]’
20924 |     basic_json(initializer_list_t init,
      |     ^~~~~~~~~~
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:20924:5: note: candidate expects 3 arguments, 7 provided
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:20840:5: note: candidate 9: ‘nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::basic_json(std::nullptr_t) [with ObjectType = nlohmann::json_abi_v3_12_0::ordered_map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_12_0::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void; std::nullptr_t = std::nullptr_t]’
20840 |     basic_json(std::nullptr_t = nullptr) noexcept // NOLINT(bugprone-exception-escape)
      |     ^~~~~~~~~~
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:20840:5: note: candidate expects 1 argument, 7 provided
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:20832:5: note: candidate 10: ‘nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::basic_json(value_t) [with ObjectType = nlohmann::json_abi_v3_12_0::ordered_map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_12_0::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void; value_t = nlohmann::json_abi_v3_12_0::detail::value_t]’
20832 |     basic_json(const value_t v)
      |     ^~~~~~~~~~
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:20832:5: note: candidate expects 1 argument, 7 provided
/home/johannesg/Projects/llama.cpp/tools/server/server-task.cpp: In member function ‘json server_task_result_cmpl_final::to_json_oaicompat_chat()’:
/home/johannesg/Projects/llama.cpp/tools/server/server-task.cpp:843:44: error: ‘llama_build_info’ was not declared in this scope
  843 |         {"system_fingerprint", std::string(llama_build_info())},
      |                                            ^~~~~~~~~~~~~~~~
/home/johannesg/Projects/llama.cpp/tools/server/server-task.cpp:847:5: error: no matching function for call to ‘nlohmann::json_abi_v3_12_0::basic_json<nlohmann::json_abi_v3_12_0::ordered_map>::basic_json(<brace-enclosed initializer list>)’
  847 |     };
      |     ^
/home/johannesg/Projects/llama.cpp/tools/server/server-task.cpp:847:5: note: there are 10 candidates
/home/johannesg/Projects/llama.cpp/common/../vendor/nlohmann/json.hpp:21163:5: note: candidate 1: ‘template<class JsonRef, typename std::enable_if<nlohmann::json_abi_v3_12_0::detail::conjunction<nlohmann::json_abi_v3_12_0::detail::is_json_ref<JsonRef>, std::is_same<typename JsonRef::value_type, nlohmann::json_abi_v3_12_0::basic_json<nlohmann::json_abi_v3_12_0::ordered_map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::json_abi_v3_12_0::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> > >::value, int>::type <anonymous> > nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::basic_json(const JsonRef&) [with typename std::enable_if<nlohmann::json_abi_v3_12_0::detail::conjunction<nlohmann::json_abi_v3_12_0::detail::is_json_ref<JsonRef>, std::is_same<typename JsonRef::value_type, nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass> > >::value, int>::type <anonymous> = JsonRef; ObjectType = nlohmann::json_abi_v3_12_0::ordered_map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_12_0::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void]’
21163 |     basic_json(const JsonRef& ref) : basic_json(ref.moved_or_copied()) {}
      |     ^~~~~~~~~~
```

**Comment by ggerganov** [comment]
Can you confirm the contents of your `build-info.h` file?

https://github.com/ggml-org/llama.cpp/blob/master/common/build-info.h

The only way for `llama_build_info()` to not be declared is if this file is somehow different on your machine.

Maybe it is including some stale version from some other path - search for stale `build-info.h` files in your paths.

**Comment by JohannesGaessler** [comment]
Thank you, I am now able to build the project again. For whatever reason I had a stale `build-info.h` file from November 2025 in my root directory. It had these contents:

```C
#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define BUILD_NUMBER 1443
#define BUILD_COMMIT "71a09da3"
#define BUILD_COMPILER "cc (GCC) 13.2.1 20230801"
#define BUILD_TARGET "x86_64-pc-linux-gnu"

#endif // BUILD_INFO_H
```

Due to the `.gitignore` file I unfortunately did not see it listed as a stale file:

```
# Build Artifacts

/tags
/.build/
/build*
/release
/debug
/libllama.so
/llama-*
/vulkan-shaders-gen
/rpc-server
/out/
/tmp/
/autogen-*.md
/common/build-info.cpp
```

After deleting `build-info.h` I am no longer having issues.

**Comment by 0cc4m** [comment]
I also just ran into this on an Arch system. It's one of my oldest llama.cpp clones, maybe a remnant from Make times?

**Comment by CarvalhoLeonardo** [comment]
Same. Would be good to get rid of that, took me a while...
