### ISSUE TITLE
Compile bug: Compilation fails due to -D_XOPEN_SOURCE=600: error: use of undeclared identifier 'strnlen'

### ISSUE THREAD

**Issue by yurivict** [ggml-org/llama.cpp#11095]
### Git commit

4418

### Operating systems

BSD

### GGML backends

CPU

### Problem description & steps to reproduce

[This -D_XOPEN_SOURCE=600 argument](https://github.com/ggerganov/llama.cpp/blob/master/Makefile#L286) breaks compilation:

```
In file included from /usr/ports/misc/llama-cpp/work/llama.cpp-b4418/ggml/src/ggml-vulkan/ggml-vulkan.cpp:8:
/usr/local/include/vulkan/vulkan.hpp:145:41: error: use of undeclared identifier 'strnlen'
  145 |       return std::string( this->data(), strnlen( this->data(), N ) );
      |                                         ^
```

The same argument is set in cmake scripts as well.

Please don't fix POSIX support at random ancient levels.

In general it shouldn't be necessary to ever set _XOPEN_SOURCE.

FreeBSD 14.2

### First Bad Commit

n/a

### Relevant log output

```shell
n/a
```

**Comment by ggerganov** [comment]
Can you check if https://github.com/ggerganov/llama.cpp/pull/11103 fixes the build using CMake?

**Comment by noirsabb** [comment]
Hi. I had the same compilation problem under FreeBSD 14.2. #11103 did not correct the compilation error for me. Following the suggestions the following did (for me) 

File

[llama.cpp]/ggml/src/CMakeLists.txt

<code>
# Somehow in OpenBSD whenever POSIX conformance is specified
# some string functions rely on locale_t availability,
# which was introduced in POSIX.1-2008, forcing us to go higher
if (NOT (CMAKE_SYSTEM_NAME MATCHES "FreeBSD"))
    if (CMAKE_SYSTEM_NAME MATCHES "OpenBSD")
        add_compile_definitions(_XOPEN_SOURCE=700)
    else()
        add_compile_definitions(_XOPEN_SOURCE=600)
    endif()
endif()
</code>

Of course your style may vary.

File 

[llama.cpp]//Makefile

setup MK_CPPFLAGS similarly to the above so that may require review, too.

NS

**Comment by yurivict** [comment]
You should just remove all _XOPEN_SOURCE options, and let the broken systems be fixed instead.

**Comment by MatthewDruid** [comment]
Hi, to resolve problem with compilation under FreeBSD 14.2 I introduced this change

```
diff --git a/ggml/src/CMakeLists.txt b/ggml/src/CMakeLists.txt
index 0002ac18..bf7dd5bf 100644
--- a/ggml/src/CMakeLists.txt
+++ b/ggml/src/CMakeLists.txt
@@ -161,7 +161,10 @@ endif()
 # Somehow in OpenBSD whenever POSIX conformance is specified
 # some string functions rely on locale_t availability,
 # which was introduced in POSIX.1-2008, forcing us to go higher
-if (CMAKE_SYSTEM_NAME MATCHES "OpenBSD")
+if (
+    CMAKE_SYSTEM_NAME MATCHES "OpenBSD" OR
+    CMAKE_SYSTEM_NAME MATCHES "FreeBSD"
+)
     add_compile_definitions(_XOPEN_SOURCE=700)
 else()
     add_compile_definitions(_XOPEN_SOURCE=600)
```
