### ISSUE TITLE
Compile bug:  Unable to build SYCL build 10556, commit ff14356e0

### ISSUE THREAD

**Issue by crash1013** [ggml-org/llama.cpp#27479]
### Git commit

build 10556, commit ff14356e0, fails on Fedora 44 Linux and Windows 11.

### Operating systems

Windows

### GGML backends

SYCL

### Problem description & steps to reproduce

I am trying to compile llama.cpp for SYCL (Vulkan has no issues) and compiler errors cause the build to fail.

### First Bad Commit

10556 / ff14356e0

### Compile command

```shell
cmake --preset x64-windows-sycl-release ^
          -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icx ^
          -DGGML_SYCL_F16=ON ^
          -DOPENSSL_ROOT_DIR="E:\work\vcpkg\packages\openssl_x64-windows" ^
      -DOPENSSL_INCLUDE_DIR="E:\work\vcpkg\packages\openssl_x64-windows\include" ^
          -DOPENSSL_CRYPTO_LIBRARY="E:\work\vcpkg\packages\openssl_x64-windows\lib\libcrypto.lib" ^
      -DOPENSSL_SSL_LIBRARY="E:\work\vcpkg\packages\openssl_x64-windows\lib\libssl.lib" || goto :error
:: cmake --preset x64-windows-sycl-release || goto :error
```

### Relevant log output

```shell
:\work\llama.cpp\ggml\src\ggml-sycl\mmvq.cpp(1438,30): error: no matching function for call to 'mul_mat_vec_q_reorder_ncols'
 1438 |                              mul_mat_vec_q_reorder_ncols<reorder_vec_dot_q_sycl<GGML_TYPE_Q2_K>, ncols_dst>(
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
E:\work\llama.cpp\ggml\src\ggml-sycl\mmvq.cpp(1437,97): note: while substituting into a lambda expression here
 1437 |                          [=](sycl::nd_item<3> nd_item) [[sycl::reqd_sub_group_size(WARP_SIZE)]] {
      |                                                                                                 ^
E:\work\llama.cpp\ggml\src\ggml-sycl\mmvq.cpp(1435,45): note: while substituting into a lambda expression here
 1435 |     stream->submit([&](sycl::handler & cgh) {
      |                                             ^
E:\work\llama.cpp\ggml\src\ggml-sycl\mmvq.cpp(1457,17): note: in instantiation of function template specialization 'reorder_mul_mat_vec_q2_k_q8_1_sycl_ncols<8>' requested here
 1457 |         case 8: reorder_mul_mat_vec_q2_k_q8_1_sycl_ncols<8>(vx, vy, dst, ncols, nrows, stride_col_y_bytes, stride_col_dst, stream); break;
      |                 ^
E:\work\llama.cpp\ggml\src\ggml-sycl\mmvq.cpp(63,13): note: candidate function template not viable: requires 10 arguments, but 8 were provided
   63 | static void mul_mat_vec_q_reorder_ncols(const void * __restrict__ vx, const void * __restrict__ vgate,
      |             ^                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   64 |                                         const void * __restrict__ vy, float * __restrict__ dst, const int ncols,
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   65 |                                         const int nrows, const int stride_col_y_bytes, const int stride_col_dst,
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   66 |                                         const ggml_glu_op glu_op, const sycl::nd_item<3> & nd_item) {
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7 errors generated.
[26/476] Building CXX object ggml\src\ggml-sycl\CMakeFiles...r\template-instances\fattn-tile-instance-dkq96-dv96.cpp.ob
ninja: build stopped: subcommand failed.
```

**Comment by jlionhan** [comment]
same build error in arch linux introduced by ff14356

**Comment by jischebeck** [comment]
same build error on ubuntu. 

  ### Root Cause Analysis

  A signature mismatch was introduced during a refactor (likely when implementing GLU fusion support for the SYCL backend).

  1. Function Definition:
  The function mmvq.cpp:63-66 expects 10 arguments:
    static void mul_mat_vec_q_reorder_ncols(
        const void * __restrict__ vx,
        const void * __restrict__ vgate,
        const void * __restrict__ vy,
        float * __restrict__ dst,
        const int ncols,
        const int nrows,
        const int stride_col_y_bytes,
        const int stride_col_dst,
        const ggml_glu_op glu_op,
        const sycl::nd_item<3> & nd_item)

  2. The Mismatched Call:
  Inside mmvq.cpp:1438-1439, only 8 arguments are provided to the function:
    mul_mat_vec_q_reorder_ncols<reorder_vec_dot_q_sycl<GGML_TYPE_Q2_K>, ncols_dst>(
        vx, vy, dst, ncols, nrows, stride_col_y_bytes, stride_col_dst, nd_item);
  This call is missing /*vgate=*/ nullptr and /*glu_op=*/ GGML_GLU_OP_SWIGLU (or another appropriate default op). Other similar functions (e.g.
  reorder_mul_mat_vec_q3_k_q8_1_sycl_ncols) were correctly updated to pass these arguments.

  ### Solution

  To resolve the compilation error, the invocation should be updated to match the other callers:

    mul_mat_vec_q_reorder_ncols<reorder_vec_dot_q_sycl<GGML_TYPE_Q2_K>, ncols_dst>(
        vx, /*vgate=*/ nullptr, vy, dst, ncols, nrows, stride_col_y_bytes, stride_col_dst,
        /*glu_op=*/ GGML_GLU_OP_SWIGLU, nd_item);

**Comment by arthw** [comment]
PR should fix the issue: https://github.com/ggml-org/llama.cpp/pull/27490
