### PR TITLE
docs/android.md: Add dependency `libandroid-spawn` for building on termux

### LINKED ISSUE #18615: Compile bug: spawn.h not found (Android - Temux)
### Git commit

eadc4184caee5b5f68f31f19a2f65c6961748e46

Build b7631

### Operating systems

Other? (Please let us know in description)

### GGML backends

CPU

### Problem description & steps to reproduce

I am trying to compile the latest release of llama.cpp for Android using Termux following the Termux build steps, almost before the build completes, it generates an error stating spawn.h was not found.

The build-essential, git, gcc & cmake packages are installed on Termux.

Running Android 16 with the latest build of Termux.

### First Bad Commit

The last time I built llama.cpp on Android was b6811 so a while ago.

### Compile command

```shell
cmake -B build
cmake --build build --config Release
```

### Relevant log output

```shell
In file included from /data/data/com.termux/files/home/new/llama.cpp-b7631/tools/server/server-models.cpp:8:    /data/data/com.termux/files/home/new/llama.cpp-b7631/common/../vendor/sheredom/subprocess.h:234:10: fatal error:                                                              'spawn.h' file not found                            234 | #include <spawn.h>                                    |          ^~~~~~~~~                              1 error generated.                                      make[2]: *** [tools/server/CMakeFiles/llama-server.dir/build.make:115: tools/server/CMakeFiles/llama-server.dir/server-models.cpp.o] Error 1                            make[1]: *** [CMakeFiles/Makefile2:5124: tools/server/CMakeFiles/llama-server.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

### LINKED ISSUE #19388: Compile bug: llama.cpp/common/../vendor/sheredom/subprocess.h:234:10: fatal error: 'spawn.h' file not found
### Git commit

❯ git rev-parse HEAD
1946e46f4c29da7b9294d702756969839e922bb8

### Operating systems

Other? (Please let us know in description)

### GGML backends

CPU

### Problem description & steps to reproduce

I am trying to build llama.cpp on termux, android 9 pie, armv8l(emulated armv7 on armv8 cpu)
``` fastfetch
OS: Android REL 9 armv8l
Host: Samsung tablet
Kernel: Linux 3.18.91
Packages: 144 (dpkg)
Shell: zsh 5.9
DE: Android build
WM: WindowManager
Terminal: Termux 0.118.3
CPU: 2 x Cortex-A53*8 (8)
GPU: Mali-T830 [Integrated]
Locale: en_US.UTF-8
```
The problem is Platform specific by what it looks like
```
[ 60%] Linking CXX executable ../bin/test-chat-parser
[ 60%] Built target test-chat-parser
[ 61%] Building CXX object tests/CMakeFiles/test-chat-peg-parser.dir/peg-parser/simple-tokenize.cpp.o
[ 61%] Building CXX object tests/CMakeFiles/test-jinja.dir/test-jinja.cpp.o
23 warnings generated.
[ 62%] Building CXX object tests/CMakeFiles/test-chat-template.dir/get-model.cpp.o
[ 62%] Linking CXX executable ../bin/test-chat-template
[ 62%] Built target test-chat-template
[ 62%] Building CXX object tests/CMakeFiles/test-chat-peg-parser.dir/get-model.cpp.o
[ 62%] Building CXX object tests/CMakeFiles/test-jinja.dir/get-model.cpp.o
[ 62%] Building CXX object tests/CMakeFiles/test-json-partial.dir/test-json-partial.cpp.o
In file included from /data/data/com.termux/files/home/skyex/temp/llama.cpp/tests/test-jinja.cpp:7:
/data/data/com.termux/files/home/skyex/temp/llama.cpp/common/../vendor/sheredom/subprocess.h:234:10: fatal error: 'spawn.h' file not found
  234 | #include <spawn.h>
      |          ^~~~~~~~~
1 error generated.
make[2]: *** [tests/CMakeFiles/test-jinja.dir/build.make:79: tests/CMakeFiles/test-jinja.dir/test-jinja.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2991: tests/CMakeFiles/test-jinja.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 63%] Building CXX object tests/CMakeFiles/test-json-partial.dir/get-model.cpp.o
[ 63%] Linking CXX executable ../bin/test-json-partial
[ 63%] Built target test-json-partial
[ 63%] Linking CXX executable ../bin/test-chat-peg-parser
[ 63%] Built target test-chat-peg-parser
[ 64%] Linking CXX executable ../bin/test-chat
[ 64%] Built target test-chat
make: *** [Makefile:146: all] Error 2
```

### First Bad Commit

Unknow

### Compile command

```shell
(I tried to turn of tests but i dont know which or how to)
cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=softfp -O3 -funsafe-math-optimizations -funroll-loops -ftree-vectorize -fomit-frame-pointer -fstrict-aliasing -fopenmp=libomp" -DCMAKE_CXX_FLAGS="-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=softfp -O3 -funsafe-math-optimizations -funroll-loops -ftree-vectorize -fomit-frame-pointer -fstrict-aliasing -fopenmp=libomp" -DCMAKE_EXE_LINKER_FLAGS="-Wl,--gc-sections -fopenmp=libomp" -DGGML_OPENMP=ON -DGGML_STATIC_OPENMP=ON -DGGML_BUILD_TESTS=OFF
```

### Relevant log output

```shell
❯ cmake --build build --config Release -j4
[  0%] Built target build_info
[  0%] Built target sha256                                                                                                                                                            [  0%] Built target cpp-httplib                                                                                                                                                       [  1%] Built target xxhash                                                                                                                                                            [  1%] Built target sha1                                                                                                                                                              [  3%] Built target ggml-base                                                                                                                                                         [  4%] Built target llama-llava-cli
[  4%] Built target llama-gemma3-cli
[  5%] Built target llama-minicpmv-cli
[  6%] Built target llama-qwen2vl-cli
[ 10%] Built target ggml-cpu
[ 11%] Built target ggml
[ 12%] Built target llama-gguf-hash
[ 12%] Built target llama-gguf
[ 43%] Built target llama
[ 44%] Built target test-c
[ 45%] Built target llama-simple
[ 45%] Built target llama-simple-chat
[ 49%] Built target mtmd
[ 56%] Built target common
[ 56%] Built target test-sampling
[ 56%] Built target test-tokenizer-0
[ 57%] Built target test-grammar-parser
[ 58%] Built target test-grammar-integration
[ 59%] Built target test-chat
[ 60%] Built target test-llama-grammar
[ 60%] Built target test-json-schema-to-grammar
[ 60%] Built target test-quantize-stats
[ 60%] Built target test-tokenizer-1-spm
[ 60%] Built target test-gbnf-validator
[ 61%] Built target test-tokenizer-1-bpe
[ 61%] Built target test-chat-parser
[ 61%] Building CXX object tests/CMakeFiles/test-jinja.dir/test-jinja.cpp.o
[ 62%] Built target test-chat-template
[ 63%] Built target test-chat-peg-parser
[ 64%] Built target test-json-partial
[ 65%] Building CXX object tests/CMakeFiles/test-log.dir/test-log.cpp.o
[ 65%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/test-peg-parser.cpp.o
[ 66%] Building CXX object tests/CMakeFiles/test-regex-partial.dir/test-regex-partial.cpp.o
[ 66%] Building CXX object tests/CMakeFiles/test-log.dir/get-model.cpp.o
[ 66%] Linking CXX executable ../bin/test-log
[ 66%] Built target test-log
[ 66%] Building CXX object tests/CMakeFiles/test-thread-safety.dir/test-thread-safety.cpp.o
In file included from /data/data/com.termux/files/home/skyex/temp/llama.cpp/tests/test-jinja.cpp:7:
/data/data/com.termux/files/home/skyex/temp/llama.cpp/common/../vendor/sheredom/subprocess.h:234:10: fatal error: 'spawn.h' file not found
  234 | #include <spawn.h>
      |          ^~~~~~~~~
1 error generated.
make[2]: *** [tests/CMakeFiles/test-jinja.dir/build.make:79: tests/CMakeFiles/test-jinja.dir/test-jinja.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2991: tests/CMakeFiles/test-jinja.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 66%] Building CXX object tests/CMakeFiles/test-regex-partial.dir/get-model.cpp.o
[ 67%] Building CXX object tests/CMakeFiles/test-thread-safety.dir/get-model.cpp.o
[ 68%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/peg-parser/simple-tokenize.cpp.o
[ 68%] Linking CXX executable ../bin/test-regex-partial
[ 68%] Built target test-regex-partial
[ 68%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/peg-parser/test-basic.cpp.o
[ 68%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/peg-parser/test-gbnf-generation.cpp.o
[ 68%] Linking CXX executable ../bin/test-thread-safety
[ 68%] Built target test-thread-safety
[ 68%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/peg-parser/test-json-parser.cpp.o
[ 69%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/peg-parser/test-json-serialization.cpp.o
[ 69%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/peg-parser/test-unicode.cpp.o
[ 69%] Building CXX object tests/CMakeFiles/test-peg-parser.dir/get-model.cpp.o
```

### PR DESCRIPTION
**Pull request by aafsmarak**
## Overview
Without `libandroid-spawn` compilation fails on termux with:
```
fatal error: 'spawn.h' file not found
```

## Additional information
Fixes https://github.com/ggml-org/llama.cpp/issues/18615
Fixes https://github.com/ggml-org/llama.cpp/issues/19388

# Requirements

- I have read and agree with the [contributing guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md)
- AI usage disclosure:  No

### CODE REVIEW

**Comment by aafsmarak** [comment]
@ggerganov Could you take a look at this

**Review by pwilkin — APPROVED** [review]

**Comment by pwilkin** [comment]
@ggml-org/maintainers need 2nd approve please

**Review by ngxson — APPROVED** [review]
