### ISSUE TITLE
Compile bug: llama_build_info() not declared error post 6990e2f1f7581d332a6a1f34d6c567be70138184

### ISSUE THREAD

**Issue by kallewoof** [ggml-org/llama.cpp#22322]
### Git commit

All commits up to before 6990e2f1f7581d332a6a1f34d6c567be70138184 work. All commits beyond and including 6990e2f1f7581d332a6a1f34d6c567be70138184 fail.

### Operating systems

Linux

### GGML backends

CUDA

### Problem description & steps to reproduce

Commit 6990e2f1f7581d332a6a1f34d6c567be70138184 fails to compile with 
```
/llama.cpp/tools/server/server-task.cpp: In member function ‘json server_task_result_cmpl_final::to_json_oaicompat()’:
/llama.cpp/tools/server/server-task.cpp:795:44: error: ‘llama_build_info’ was not declared in this scope
  795 |         {"system_fingerprint", std::string(llama_build_info())},
      |                                            ^~~~~~~~~~~~~~~~
/llama.cpp/tools/server/server-task.cpp:799:5: error: no matching function for call to ‘nlohmann::json_abi_v3_12_0::basic_json<nlohmann::json_abi_v3_12_0::ordered_map>::basic_json(<brace-enclosed initializer list>)’
  799 |     };
      |     ^
In file included from /llama.cpp/tools/server/server-common.h:10,
                 from /llama.cpp/tools/server/server-task.h:12,
                 from /llama.cpp/tools/server/server-task.cpp:1:
/llama.cpp/common/../vendor/nlohmann/json.hpp:21163:5: note: candidate: ‘template<class JsonRef, typename std::enable_if<nlohmann::json_abi_v3_12_0::detail::conjunction<nlohmann::json_abi_v3_12_0::detail::is_json_ref<JsonRef>, std::is_same<typename JsonRef::value_type, nlohmann::json_abi_v3_12_0::basic_json<nlohmann::json_abi_v3_12_0::ordered_map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::json_abi_v3_12_0::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> > >::value, int>::type <anonymous> > nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::basic_json(const JsonRef&) [with JsonRef = JsonRef; typename std::enable_if<nlohmann::json_abi_v3_12_0::detail::conjunction<nlohmann::json_abi_v3_12_0::detail::is_json_ref<JsonRef>, std::is_same<typename JsonRef::value_type, nlohmann::json_abi_v3_12_0::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass> > >::value, int>::type <anonymous> = <anonymous>; ObjectType = nlohmann::json_abi_v3_12_0::ordered_map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_12_0::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void]’
```

### First Bad Commit

6990e2f1f7581d332a6a1f34d6c567be70138184

### Compile command

```shell
cmake -B build -DGGML_CUDA=ON -DGGML_RPC=ON -DBUILD_SHARED_LIBS=OFF -DGGML_AVX2=ON -DGGML_AVX_VNNI=ON -DGGML_CUDA_FA_ALL_QUANTS=ON
cmake --build build --config Release -j 8 --clean-first
cmake --build build --config Release -t llama-server -j 8
```

### Relevant log output

```shell
/llama.cpp/tools/server/server-task.cpp: In member function ‘json server_task_result_cmpl_final::to_json_oaicompat()’:
/llama.cpp/tools/server/server-task.cpp:795:44: error: ‘llama_build_info’ was not declared in this scope
  795 |         {"system_fingerprint", std::string(llama_build_info())},
      |                                            ^~~~~~~~~~~~~~~~
```

**Comment by ggerganov** [comment]
See https://github.com/ggml-org/llama.cpp/issues/22062

**Comment by kallewoof** [comment]
Thanks

**Comment by mollahmasud977-sys** [comment]
glömde bro

في الجمعة، 24 أبريل 2026 15:57 kallewoof ***@***.***> كتب:
