### PR TITLE
ggml-backend : keep paths in native string type when possible

### LINKED ISSUE #11198: Eval bug: Crash with filesystem error when run while in a directory containing files with certain names
### Name and Version

version: 4462 (c05e8c99)
built with cc (Debian 12.2.0-14) 12.2.0 for x86_64-linux-gnu

### Operating systems

Linux

### GGML backends

CPU

### Hardware

N/A

### Models

N/A

### Problem description & steps to reproduce

Running `llama-cli` or `llama-server` while the current directory contains a file with certain characters in the file name causes a crash with the filesystem error shown below.

Here is an example of a character that will cause the crash when present in a file name
｜

### First Bad Commit

commit 60cfa72

### Relevant log output

```shell
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Invalid or incomplete multibyte or wide character
Aborted
```

### PR DESCRIPTION
**Pull request by slaren**
Avoids conversions from `std::filesystem::path` to non-native `std::string` to prevent possible issues when converting between different encodings. When unavoidable (e.g. to print a path), checks for exceptions.

Fixes #11198

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by gnusupport** [comment]
Thanks for fixing this issue.

**Comment by MaggotHATE** [comment]
This change causes errors with w64devkit on Windows 10 (c++2a):
```
ggml-backend-reg.cpp:78:32: error: no match for 'operator=' (operand types are 'std::string' {aka 'std::__cxx11::basic_string<char>'} and 'std::u8string' {aka 'std::__cxx11::basic_string<char8_t>'})
   78 |         u8path = path.u8string();
      |                                ^
 ```

**Comment by slaren** [comment]
`path.u8string` returns a `std::string` in C++17, but a `std::u8string` in C++20. If some parts of your application need C++20 or higher, you can try building only these with C++20 enabled and continue building ggml and llama.cpp with C++17.

**Comment by MaggotHATE** [comment]
> `path.u8string` returns a `std::string` in C++17, but a `std::u8string` in C++20. If some parts of your application need C++20 or higher, you can try building only these with C++20 enabled and continue building ggml and llama.cpp with C++17.

This PR is the only thing that makes llama.cpp incompatible with C++20, shouldn't it be fixed? It seems a bit weird to leave it this way.

**Comment by slaren** [comment]
I am not sure what's the point since you can just build ggml with the correct flag, and I am not interested in supporting C++20, but if that's something that you care about feel free to open a PR.
