### PR TITLE
fix: add missing headers

### LINKED ISSUE #28557: Compile bug: error: use of undeclared identifier 'errno'
### Git commit

e71b80510c848c00175924ecf3c40333ccae8eb5

### Operating systems

Linux

### GGML backends

CPU, CUDA, AMX, BLAS, CANN, Hexagon, HIP, Metal, Musa, OpenCL, OpenVINO, RPC, SYCL, VirtGPU, Vulkan, WebGPU, zDNN, ZenDNN

### Problem description & steps to reproduce

I'm on Gentoo arm64 using clang+musl

```
$ git clone https://github.com/ggml-org/llama.cpp
$ cd llama.cpp
$ cmake -B build
$ cmake --build build --config Release
```

### First Bad Commit

37c35f0e1c625831687b146cbb0a57654ef88ca2

### Compile command

```shell
cmake --build build --config Release
```

### Relevant log output

```shell
[29/896] /usr/lib/llvm/22/bin/clang++ -DGGML_BUILD -DGGML_SCHED_MAX_COPIES=4 -DGGML_SHARED -DGGML_USE_OPENMP -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -Dggml_base_EXPORTS -I/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/. -I/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999_build/ggml/src -I/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/../include  -mcpu=neoverse-n1 -O2 -pipe -std=gnu++17 -fPIC -Wmissing-declarations -Wmissing-noreturn -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi -fopenmp=libomp -MD -MT ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o -MF ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o.d -o ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o -c /var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/gguf.cpp
FAILED: [code=1] ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o
/usr/lib/llvm/22/bin/clang++ -DGGML_BUILD -DGGML_SCHED_MAX_COPIES=4 -DGGML_SHARED -DGGML_USE_OPENMP -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -Dggml_base_EXPORTS -I/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/. -I/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999_build/ggml/src -I/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/../include  -mcpu=neoverse-n1 -O2 -pipe -std=gnu++17 -fPIC -Wmissing-declarations -Wmissing-noreturn -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi -fopenmp=libomp -MD -MT ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o -MF ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o.d -o ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o -c /var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/gguf.cpp
/var/tmp/portage/sci-misc/llama-cpp-9999/work/llama-cpp-9999/ggml/src/gguf.cpp:996:94: error: use of undeclared identifier 'errno'
  996 |         GGML_LOG_ERROR("%s: failed to open GGUF file '%s' (%s)\n", __func__, fname, strerror(errno));
      |                                                                                              ^~~~~
1 error generated.
```

### PR DESCRIPTION
**Pull request by peppergrayxyz**
## Overview

add missing headers to fix compiler bugs on clang/musl

## Additional information

Closes: #28557, #28559, #28560, #28561, #28562, #28564

## Requirements

- I have read and agree with the [contributing guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md)
- AI usage disclosure: NO

### CODE REVIEW

**Comment by fairydreaming** [comment]
@peppergrayxyz Can you rebase/merge the current master? It looks like someone merged some crappy code (hopefully it's fixed now) and the fallout from this is visible in the CI results.

Edit: NVM, merged.

**Review by fairydreaming — APPROVED** [review]

**Comment by peppergrayxyz** [comment]
Sorry, I missed the edit and rebased anyways!

**Review by danbev — APPROVED** [review]

**Comment by ggerganov** [comment]
@peppergrayxyz Which compiler version are you using? Can you try to add a CI job that reproduces the compile errors that you get?

**Comment by CISC** [comment]
> @peppergrayxyz Which compiler version are you using? Can you try to add a CI job that reproduces the compile errors that you get?

Seems to be very system specific, just did a test on Alpine without issues:
https://github.com/CISC/llama.cpp/actions/runs/34201179917/job/101980073106

**Comment by peppergrayxyz** [comment]
If it works on Alpine, then it's probably a libcxx issue. I'm on Gentoo using the llvm toolchain (clang, libcxx, libunwind, compiler-rt).

**Comment by peppergrayxyz** [comment]
The root cause is `libc++` 23 (which ships with `clang` 23.1.0)

https://releases.llvm.org/23.1.0/projects/libcxx/docs/ReleaseNotes.html:

> Potentially breaking changes
>  
> libc++ has dropped a lot of transitive includes in all language modes. This improves compile time significantly, but causes programs which rely on these includes to not compile anymore. Any errors caused by this should be fixable  by including the correct header. To ease the transition _LIBCPP_KEEP_TRANSITIVE_INCLUDES_LLVM23 can be  defined, which includes the removed headers again. This macro will be removed in LLVM 24.

I could confirm this with:
```
$ cmake -B build -DCMAKE_CXX_FLAGS="-D_LIBCPP_KEEP_TRANSITIVE_INCLUDES_LLVM23
$ cmake --build build
```

which doesn't show these errors.

As for CI: Gentoo recently moved `clang-23` to testing, but doesn't ship binary packages for it yet. However, Debian Sid has binary packages for `clang-23` and I could reproduce the exact errors: 
https://github.com/peppergrayxyz/llama.cpp/actions/runs/34216863589/job/102030576047

**Review by ggerganov — APPROVED** [review]
Ok, thanks for looking into this. I think we can merge. @CISC up to you

**Review by CISC — APPROVED** [review]

**Comment by fairydreaming** [comment]
@peppergrayxyz please retest compilation and close related bugs if they are fixed
