### ISSUE TITLE
Compile bug: ‘ggml_gelu_erf’ was not declared in this scope; did you mean ‘ggml_gelu’

### ISSUE THREAD

**Issue by utkarsh181** [ggml-org/llama.cpp#13744]
### Git commit

2d6f09800112ad71dbdd5bdd6ac592cb52f81ebd

### Operating systems

Linux

### GGML backends

Kompute

### Problem description & steps to reproduce

I'm trying to compile [llama.cpp](https://aur.archlinux.org/packages/llama.cpp-git) AUR package, but its unable to find definition for `ggml_gelu_erf`, which was added in [79799](https://github.com/ggml-org/llama.cpp/commit/797990c4bca0dca5be295c63e3fb2800dc0a69c2), 2 days ago.

### First Bad Commit

797990c4bca0dca5be295c63e3fb2800dc0a69c2

### Compile command

```shell
makepkg -sCi
```

### Relevant log output

```shell
[ 80%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/clip.cpp.o
/home/utkarsh/.local/src/aur/cur/llama.cpp-git/src/llama.cpp/tools/mtmd/clip.cpp: In member function ‘ggml_cgraph* clip_graph::build_whisper_enc()’:
/home/utkarsh/.local/src/aur/cur/llama.cpp-git/src/llama.cpp/tools/mtmd/clip.cpp:1441:19: error: ‘ggml_gelu_erf’ was not declared in this scope; did you mean ‘ggml_gelu’?
 1441 |             cur = ggml_gelu_erf(ctx0, cur);
      |                   ^~~~~~~~~~~~~
      |                   ggml_gelu
/home/utkarsh/.local/src/aur/cur/llama.cpp-git/src/llama.cpp/tools/mtmd/clip.cpp: In member function ‘ggml_tensor* clip_graph::build_ffn(ggml_tensor*, ggml_tensor*, ggml_tensor*, ggml_tensor*, ggml_tensor*, ggml_tensor*, ggml_tensor*, ffn_op_type, int) const’:
/home/utkarsh/.local/src/aur/cur/llama.cpp-git/src/llama.cpp/tools/mtmd/clip.cpp:1760:27: error: ‘ggml_gelu_erf’ was not declared in this scope; did you mean ‘ggml_gelu’?
 1760 |                     cur = ggml_gelu_erf(ctx0, cur);
      |                           ^~~~~~~~~~~~~
      |                           ggml_gelu
make[2]: *** [tools/mtmd/CMakeFiles/mtmd.dir/build.make:107: tools/mtmd/CMakeFiles/mtmd.dir/clip.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2428: tools/mtmd/CMakeFiles/mtmd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by qnixsynapse** [comment]
You would need this: cf4cb59e64d72a1b4c781f71a74de5756a4e2376

**Comment by utkarsh181** [comment]
Makes sense, but I think someone will have sync these changes to [ggml-org/ggml](https://github.com/ggml-org/ggml).

cc: @ggerganov

**Comment by ggerganov** [comment]
I started the sync, but it seems the `DIV` operation is broken currently:

https://github.com/ggml-org/ggml/pull/1238

When fixed, ping me to do the final sync.

**Comment by qnixsynapse** [comment]
Please feel free to merge it and sync with ggml for now.

**Comment by ggerganov** [comment]
The sync is not completed.

**Comment by utkarsh181** [comment]
Thanks!
