### PR TITLE
Fix #11802: Compile bug - RegQueryValueExA changed to RegQueryValueEx

### LINKED ISSUE #11802: Compile bug: error C2664: 'LSTATUS RegQueryValueExA(HKEY,LPCSTR,LPDWORD,LPDWORD,LPBYTE,LPDWORD)': cannot convert argument 2 from 'const wchar_t [20]' to 'LPCSTR'
### Git commit

$ git rev-parse HEAD
b9ab0a4d0b2ed19effec130921d05fb5c30b68c5

### Operating systems

Windows

### GGML backends

CPU

### Problem description & steps to reproduce

I'm using library [lcpp ^0.0.4](https://pub.dev/packages/lcpp).
$ git rev-parse HEAD
b9ab0a4d0b2ed19effec130921d05fb5c30b68c5

Compile error
```
ggml\src\ggml-cpu\ggml-cpu.cpp(293,21): error C2664: 'LSTATUS RegQueryValueExA(HKEY,LPCSTR,LPDWORD,LPDWORD,LPBYTE,LPDWORD)': cannot convert argument 2 from 'const wchar_t [20]' to 'LPCSTR'
```

Fix:
`RegQueryValueExA` should be changed to `RegQueryValueEx`  in lines 286 & 293.

`RegQueryValueExA` is `char*`, `RegQueryValueExW` is for `wchar*` and `RegQueryValueEx` will resolve to correct function based on setting `-DUNICODE -D_UNICODE`

### First Bad Commit

_No response_

### Compile command

```shell
flutter build windows --debug
```

### Relevant log output

```shell
\windows\flutter\ephemeral\.plugin_symlinks\lcpp\src\llama_cpp\ggml\src\ggml-cpu\ggml-cpu.cpp(286,17): error C2664: 'LSTATUS RegQueryValueExA(HKEY,LPCSTR,LPDWORD,LPDWORD,LPBYTE,LPDWORD)': cannot convert argument 2 from 'const wchar_t [20]' to 'LPCSTR' \build\windows\x64\plugins\lcpp\shared\ggml\src\ggml-cpu.vcxproj]
\windows\flutter\ephemeral\.plugin_symlinks\lcpp\src\llama_cpp\ggml\src\ggml-cpu\ggml-cpu.cpp(293,21): error C2664: 'LSTATUS RegQueryValueExA(HKEY,LPCSTR,LPDWORD,LPDWORD,LPBYTE,LPDWORD)': cannot convert argument 2 from 'const wchar_t [20]' to 'LPCSTR' \build\windows\x64\plugins\lcpp\shared\ggml\src\ggml-cpu.vcxproj]
```

### PR DESCRIPTION
**Pull request by sheldonrobinson**
*Make sure to read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md) before submitting a PR*

fix #11802

### CODE REVIEW

**Comment by slaren** [comment]
Won't this cause the value to be read as a `wchar_t` as well? I believe the correct solution here would be to continue using `RegQueryValueA`, but remove the use of the `TEXT` macro to pass the key name.

**Comment by sheldonrobinson** [comment]
The TEXT is also handled.  If `UNICODE`, `TEXT` is `L##`,  other `TEXT` is  ANSI string. See [TEXT macro (winnt.h)](https://learn.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-text)

**Comment by sheldonrobinson** [comment]
The TEXT is also handled.  If `UNICODE`, `TEXT` is `L##`,  other `TEXT` is  ANSI string. See [TEXT macro (winnt.h)](https://learn.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-text)

**Comment by sheldonrobinson** [comment]
See also
If `UNICODE`, then [`#define __TEXT(quote) L##quote `](https://gist.github.com/JamesMenetrey/d3f494262bcab48af1d617c3d39f34cf#file-winnt-h-L562)
else
[`#define __TEXT(quote) quote`](https://gist.github.com/JamesMenetrey/d3f494262bcab48af1d617c3d39f34cf#file-winnt-h-L581)
and
[`#define TEXT(quote) __TEXT(quote)`](https://gist.github.com/JamesMenetrey/d3f494262bcab48af1d617c3d39f34cf#file-winnt-h-L584)

**Comment by sheldonrobinson** [comment]
It should be `RegQueryValueEx` and `TEXT`.

**Comment by sheldonrobinson** [comment]
Ok, agreed. Keep `RegQueryValueExA`, remove `TEXT`

**Review by slaren — APPROVED** [review]
Thanks.
