### PR TITLE
gguf-py: moved scripts directory

### LINKED ISSUE #9566: Bug: gguf pypi package corrupts environment
### What happened?

installing `gguf` using `pip install gguf` will register `gguf` AND `scripts`
which means that any app that has `scripts` in their structure will suddenly start failing just because `gguf` is installed.

looking at <https://github.com/ggerganov/llama.cpp/blob/master/gguf-py/pyproject.toml>
```js
packages = [
    {include = "gguf"},
    {include = "gguf/py.typed"},
    {include = "scripts"},
]
```
culprit is clear - `scripts` folder should be moved to be under `gguf`, not as a separate package.
if that is too much, then at least rename scripts package to be `gguf_scripts`

### Name and Version

latest commit as of date of issue: [d39e267](https://github.com/ggerganov/llama.cpp/commit/d39e26741f9f02340651dbc640c9776e1a1128ef)

### What operating system are you seeing the problem on?

Linux, Mac, Windows, BSD

### Relevant log output

```shell
import gguf
from scripts import test_module

test_module.some_method()


```log
ImportError: cannot import name 'test_module' from 'scripts' (venv/lib/python3.12/site-packages/scripts/__init__.py)
```
```

### LINKED ISSUE #11089: Misc. bug: gguf pypy package dumps /scripts/ and /examples/ into site-packages
### Name and Version

https://pypi.org/project/gguf/ latest

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

Other (Please specify in the next section)

### Problem description & steps to reproduce

do a `pip install gguf` inside of a conda env. Now the package has created both a /scripts/ and an /examples/ inside your site-packages. 

I'm not sure it's particular to my environment, but running any other project with a /scripts/ folder has a relatively high chance of trying to import from GGUF "scripts" instead of it's own folder, at least on py 3.10.

If there is any other reason this happens, let me know. I have now checked 2 environments where I had to install GGUF and both have this issue. The solution is to simply delete the offending folders but you now have lost the scripts. Should they not be in the gguf folder so that it's gguf/scripts?

### First Bad Commit

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by VJHack**
When installing the `gguf` pypi package, only one root level package should be registered. Currently two seprate packages get registered (`scripts` and `gguf`) which can cause issues when your project already has a `scripts` folder.

This PR moves the scripts directory inside the `gguf` package, making it a subpackage of `gguf`.

```
gguf-py
├── LICENSE
├── README.md
├── examples
│   ├── reader.py
│   └── writer.py
├── gguf
│   ├── __init__.py
│   ├── constants.py
│   ├── gguf.py
│   ├── gguf_reader.py
│   ├── gguf_writer.py
│   ├── lazy.py
│   ├── metadata.py
│   ├── py.typed
│   ├── quants.py
│   ├── scripts
│   │   ├── __init__.py
│   │   ├── gguf_convert_endian.py
│   │   ├── gguf_dump.py
│   │   ├── gguf_hash.py
│   │   ├── gguf_new_metadata.py
│   │   └── gguf_set_metadata.py
│   ├── tensor_mapping.py
│   ├── utility.py
│   └── vocab.py
├── poetry.lock
├── pyproject.toml
└── tests
    ├── __init__.py
    ├── test_metadata.py
    └── test_quants.py
```

Fixes #11089 and Fixes #9566

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by VJHack** [comment]
@ggerganov Pyright checks are failing in all pipelines because safetensors released version 0.5.1 to PyPi with a bug. Waiting on[ this fix ](https://github.com/huggingface/safetensors/pull/557)to get merged and published.

**Comment by VJHack** [comment]
safetensor version 0.5.2 was just released. That fixed the issue.

**Comment by LostRuins** [comment]
I think this commit broke the local detection of gguf library for non-installed setups 

For example
https://github.com/ggerganov/llama.cpp/blob/8a1d9c25fafbaf4182dd0b785dd6303ee40d55bc/gguf-py/gguf/scripts/gguf_dump.py#L15-L16

should be instead:
```
if "NO_LOCAL_GGUF" not in os.environ and (Path(__file__).parent.parent.parent.parent / 'gguf-py').exists():
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
```

This will need to be changed in 7 other files.

**Comment by VJHack** [comment]
@LostRuins I'm seeing around 11 places where this needs to be updated. Will push the fix as soon as possible. Thanks for pointing that out!
