### ISSUE TITLE
Compile bug: error: use of undeclared identifier 'strtol'

### ISSUE THREAD

**Issue by peppergrayxyz** [ggml-org/llama.cpp#28561]
### Git commit

e71b80510c848c00175924ecf3c40333ccae8eb5

### Operating systems

Linux

### GGML backends

AMX, BLAS, CANN, CPU, CUDA, Hexagon, HIP, Metal, Musa, OpenVINO, OpenCL, RPC, SYCL, VirtGPU, Vulkan, WebGPU, zDNN, ZenDNN

### Problem description & steps to reproduce

I'm on Gentoo arm64 using clang+musl

```
$ git clone https://github.com/ggml-org/llama.cpp
$ cd llama.cpp
$ cmake -B build
$ cmake --build build --config Release
```

### First Bad Commit

4aa962e2b0d04e6be6944f899edbdbe26177e492

### Compile command

```shell
cmake --build build --config Release
```

### Relevant log output

```shell
/home/pepper/dev/ghrepos/llama.cpp/src/llama-vocab.cpp:3172:20: error: use of undeclared identifier 'strtol'
 3172 |             return strtol(buf.c_str(), NULL, 16);
      |                    ^~~~~~
/home/pepper/dev/ghrepos/llama.cpp/src/llama-vocab.cpp:3177:20: error: use of undeclared identifier 'strtol'
 3177 |             return strtol(buf.c_str(), NULL, 16);
      |                    ^~~~~~
2 errors generated.
```

**Comment by peppergrayxyz** [comment]
`#include <cstdlib>` is missing in `src/llama-vocab.cpp`
