### ISSUE TITLE
Compile bug: error: use of undeclared identifier 'rand'/'RAND_MAX'

### ISSUE THREAD

**Issue by peppergrayxyz** [ggml-org/llama.cpp#28564]
### Git commit

e71b80510c848c00175924ecf3c40333ccae8eb5

### Operating systems

Linux

### GGML backends

AMX, BLAS, CANN, CPU, CUDA, Hexagon, HIP, Metal, Musa, OpenCL, OpenVINO, RPC, SYCL, VirtGPU, Vulkan, WebGPU, zDNN, ZenDNN

### Problem description & steps to reproduce

I'm on Gentoo arm64 using clang+musl

```
$ git clone https://github.com/ggml-org/llama.cpp
$ cd llama.cpp
$ cmake -B build
$ cmake --build build --config Release
```

### First Bad Commit

b0f27361f3539a81d983a8b045f3c61e682d9fc0

### Compile command

```shell
cmake --build build --config Release
```

### Relevant log output

```shell
/home/pepper/dev/ghrepos/llama.cpp/tests/test-sampling.cpp:326:44: error: use of undeclared identifier 'rand'
  326 |         const float logit = 2.0f*((double)(rand())/RAND_MAX - 0.5);
      |                                            ^~~~
/home/pepper/dev/ghrepos/llama.cpp/tests/test-sampling.cpp:326:52: error: use of undeclared identifier 'RAND_MAX'
  326 |         const float logit = 2.0f*((double)(rand())/RAND_MAX - 0.5);
      |                                                    ^~~~~~~~
```

**Comment by peppergrayxyz** [comment]
`#include <cstdlib>` is missing in `tests/test-sampling.cpp`
