### ISSUE TITLE
Misc. bug: SYCL undefined reference to _Z22__spirv_GroupBroadcastifDv3_

### ISSUE THREAD

**Issue by RinCat** [ggml-org/llama.cpp#24928]
### Name and Version

version: 9763 (dec5ca557)
built with IntelLLVM 2026.0.0 for Linux x86_64

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
/opt/llama.cpp/llama-server -m /srv/AI/models/Text/Qwen3.6-27B-Uncensored-HauhauCS-Balanced/Qwen3.6-27B-Uncensored-HauhauCS-Balanced-Q4_K_P.gguf --mmproj /srv/AI/models/Text/Qwen3.6-27B-Uncensored-HauhauCS-Balanced/mmproj-Qwen3.6-27B-Uncensored-HauhauCS-Balanced-f16.gguf --device SYCL0 --split-mode none --main-gpu 0 --temperature 1.0 --top-p 0.95 --min-p 0.0 --top-k 20 --repeat-penalty 1.0 --presence-penalty 1.5 -ngl 999 -c 262144 -ctk q8_0 -ctv q8_0 --flash-attn on --no-host --no-mmap --kv-unified --parallel 1 --cache-ram 0 --host 0.0.0.0 --port 8080
```

### Problem description & steps to reproduce

1. Start llama-server with SYCL backend
2. SYCL GPU kernel build failed with error: undefined reference to `_Z22__spirv_GroupBroadcastifDv3_`

The same system was working, just llama.cpp version change.

### First Bad Commit

ac79caa7ce61dbd800451ce43adb3dd9bf2f633b

### Relevant log output

<details>
<summary>Build Config</summary>

```console
cmake -B build-sycl   -DGGML_SYCL=ON -DGGML_VULKAN=ON -DGGML_SYCL_TARGET=INTEL -DGGML_SYCL_F16=ON   -DBUILD_SHARED_LIBS=OFF   -DCMAKE_C_COMPILER=/opt/intel/oneapi/compiler/latest/bin/icx   -DCMAKE_CXX_COMPILER=/opt/intel/oneapi/compiler/latest/bin/icpx   -DMKL_DIR=/opt/intel/oneapi/mkl/latest/lib/cmake/mkl   -DTBB_DIR=/opt/intel/oneapi/tbb/latest/lib/cmake/tbb   -DCMAKE_PREFIX_PATH="/opt/intel/oneapi/mkl/latest;/opt/intel/oneapi/tbb/latest"   -DCMAKE_BUILD_TYPE=Release   -DCMAKE_C_FLAGS_RELEASE="-O3 -DNDEBUG"   -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG" 
-- The C compiler identification is IntelLLVM 2026.0.0
-- The CXX compiler identification is IntelLLVM 2026.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/intel/oneapi/compiler/latest/bin/icx - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/oneapi/compiler/latest/bin/icpx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE=Release
-- Found Git: /usr/bin/git (found version "2.53.0")
-- The ASM compiler identification is IntelLLVM
-- Found assembler: /opt/intel/oneapi/compiler/latest/bin/icx
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Found OpenMP_C: -fiopenmp (found version "5.1")
-- Found OpenMP_CXX: -fiopenmp (found version "5.1")
-- Found OpenMP: TRUE (found version "5.1")
-- Including CPU backend
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native 
-- GGML_SYCL_TARGET=INTEL
-- Performing Test SUPPORTS_SYCL
-- Performing Test SUPPORTS_SYCL - Success
-- Using oneAPI Release SYCL compiler (icpx).
-- SYCL found
-- SYCL Compiler version: 20260000
-- SYCL_INCLUDE_DIR: /opt/intel/oneapi/compiler/2026.0/include
-- SYCL_LIBRARY=/opt/intel/oneapi/compiler/2026.0/lib/libsycl.so
-- Found IntelSYCL: /opt/intel/oneapi/compiler/2026.0/include (found version "202012")
-- GGML_SYCL_SUPPORT_LEVEL_ZERO ON
-- Level Zero loader found: /lib64/libze_loader.so
-- Level Zero headers found: /usr/include
-- Found oneDNN: /opt/intel/oneapi/dnnl/2026.0/lib/libdnnl.so.3.11
-- MKL_VERSION: 2026.0.0
-- MKL_ROOT: /opt/intel/oneapi/mkl/2026.0
-- MKL_ARCH: intel64
-- MKL_SYCL_LINK: None, set to ` dynamic` by default
-- MKL_LINK: None, set to ` dynamic` by default
-- MKL_SYCL_INTERFACE_FULL: None, set to ` intel_ilp64` by default
-- MKL_INTERFACE_FULL: None, set to ` intel_ilp64` by default
-- MKL_SYCL_THREADING: None, set to ` tbb_thread` by default
-- MKL_THREADING: None, set to ` intel_thread` by default
-- MKL_SYCL_MPI: None, set to ` intelmpi` by default
-- MKL_MPI: None, set to ` intelmpi` by default
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_scalapack_ilp64.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_cdft_core.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_intel_ilp64.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_intel_thread.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_core.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_blacs_intelmpi_ilp64.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_sycl_distributed_dft.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_sycl_blas.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_sycl_lapack.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_sycl_dft.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_sycl_sparse.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_sycl_data_fitting.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_sycl_rng.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_sycl_stats.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_sycl_vm.so
-- Found /opt/intel/oneapi/mkl/2026.0/lib/libmkl_tbb_thread.so
-- Found /opt/intel/oneapi/tbb/2023.0/lib/intel64/gcc4.8/libtbb.so.12
-- Found /opt/intel/oneapi/compiler/2026.0/lib/libiomp5.so
-- find GGML_SYCL_GRAPH
-- find GGML_SYCL_HOST_MEM_FALLBACK
-- Including SYCL backend
-- Found Vulkan: /usr/lib64/libvulkan.so (found version "1.4.341") found components: glslc glslangValidator
-- Vulkan found
-- GL_KHR_cooperative_matrix supported by glslc
-- GL_NV_cooperative_matrix2 supported by glslc
-- GL_NV_cooperative_matrix_decode_vector not supported by glslc
-- GL_EXT_integer_dot_product supported by glslc
-- GL_EXT_bfloat16 supported by glslc
-- Including Vulkan backend
-- ggml version: 0.15.1
-- ggml commit:  ac79caa7c
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "3.5.7")
-- Performing Test OPENSSL_VERSION_SUPPORTED
-- Performing Test OPENSSL_VERSION_SUPPORTED - Success
-- OpenSSL found: 3.5.7
-- Generating embedded license file for target: llama-app
-- Configuring done (3.6s)
-- Generating done (0.6s)
-- Build files have been written to: /tmp/llama.cpp/build-sycl
```
</details>

<details>
<summary>Logs</summary>

```console
0.00.185.868 I log_info: verbosity = 3 (adjust with the `-lv N` CLI arg)
0.00.185.870 I device_info:
0.00.186.015 I   - SYCL0   : Intel(R) Graphics [0xe223] (31023 MiB, 31023 MiB free)
0.00.186.324 I   - Vulkan0 : Intel(R) Arc(tm) A770 Graphics (DG2) (16288 MiB, 14659 MiB free)
0.00.186.669 I   - Vulkan1 : Intel(R) Graphics (BMG G31) (32656 MiB, 29149 MiB free)
0.00.186.672 I   - CPU     : AMD Ryzen 9 3900X 12-Core Processor (64192 MiB, 64192 MiB free)
0.00.186.780 I system_info: n_threads = 12 (n_threads_batch = 12) / 24 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | BMI2 = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 | 
0.00.186.791 I srv          init: running without SSL
0.00.186.930 I srv          init: using 23 threads for HTTP server
0.00.187.185 I srv         start: binding port with default address family
0.00.188.308 I srv  llama_server: loading model
0.00.188.312 I srv    load_model: loading model '/srv/AI/models/Text/Qwen3.6-27B-Uncensored-HauhauCS-Balanced/Qwen3.6-27B-Uncensored-HauhauCS-Balanced-Q4_K_P.gguf'
0.01.430.176 I srv    load_model: [mtmd] estimated worst-case memory usage of mmproj is 1157.64 MiB
0.01.430.187 I common_init_result: fitting params to device memory ...
0.01.430.188 I common_init_result: (for bugs during this step try to reproduce them with -fit off, or provide --verbose logs if the bug only occurs with -fit on)
0.06.157.359 I common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
The program was built for 1 devices
Build program log for 'Intel(R) Graphics [0xe223]':

error: undefined reference to `_Z22__spirv_GroupBroadcastifDv3_m'
in function: '__spirv_GroupBroadcast(int, float, unsigned long vector[3])' called by kernel: 'typeinfo name for ggml_sycl_op_rms_norm_back(ggml_backend_sycl_context&, ggml_tensor*)::'lambda'(sycl::_V1::handler&)::operator()(sycl::_V1::handler&) const::'lambda'(sycl::_V1::nd_item<3>)'

error: backend compiler failed build.
Exception caught at file:/tmp/llama.cpp/ggml/src/ggml-sycl/ggml-sycl.cpp, line:4908
Error OP RMS_NORM
```
</details>

**Comment by arthw** [comment]
@RinCat 
How many GPUs in your PC?
Are the SYCL0 and Vulkan1 are same physical GPUs?

I don't know if SYCL and Vulan backends can work together in same process.

Two suggestions:
1. `rm -rf build`, then build again and test.
2. Use pure SYCL backend to run with the 3 GPUs above.

Thank you!

**Comment by RinCat** [comment]
Hi,

> [@RinCat](https://github.com/RinCat) How many GPUs in your PC? Are the SYCL0 and Vulkan1 are same physical GPUs?

Only 2, one B70, one A770

> I don't know if SYCL and Vulan backends can work together in same process.

I just use one GPU at a time, not mix backend.

> Two suggestions:
> 
>     1. `rm -rf build`, then build again and test.

I had already build many times and point the commit start this issue, not sure how. 

>     2. Use pure SYCL backend to run with the 3 GPUs above.

SYCL backend on A770 is so slow compare to Vulkan. So I run one model on Vulkan with A770 and one model on SYCL with B70.

**Comment by arthw** [comment]
@RinCat 

1. In the building cmd, remove `-DGGML_VULKAN=ON`.
Only build SYCL backend.

2.use `export ONEAPI_DEVICE_SELECTOR="level_zero:0"` to allow to use the first GPU (B70. Change it for your case).
--main-gpu in llama-server is out of work now.

If you want to run a case on multiple GPUs with different backends, please try with RPC backend.
I heard someone run it successfully. 
But I have no experiment of RPC backend. You could check with the guide of it.

**Comment by RinCat** [comment]
@arthw with SYCL backend only, same issue for me

```
0.00.202.835 I common_init_result: fitting params to device memory ...
0.00.202.836 I common_init_result: (for bugs during this step try to reproduce them with -fit off, or provide --verbose logs if the bug only occurs with -fit on)
0.56.547.255 I common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
The program was built for 1 devices
Build program log for 'Intel(R) Graphics [0xe223]':

error: undefined reference to `_Z22__spirv_GroupBroadcastifDv3_m'
in function: '__spirv_GroupBroadcast(int, float, unsigned long vector[3])' called by kernel: 'typeinfo name for ggml_sycl_op_rms_norm_back(ggml_backend_sycl_context&, ggml_tensor*)::'lambda'(sycl::_V1::handler&)::operator()(sycl::_V1::handler&) const::'lambda'(sycl::_V1::nd_item<3>)'

error: backend compiler failed build.
Exception caught at file:/tmp/llama.cpp/ggml/src/ggml-sycl/ggml-sycl.cpp, line:4996
Error OP RMS_NORM
```

**Comment by arthw** [comment]
Could you share the full log and run cmd?

**Comment by RinCat** [comment]
`/opt/llama.cpp/llama-server -m /srv/AI/models/Text/Qwen3.6-27B-Uncensored-HauhauCS-Balanced/Qwen3.6-27B-Uncensored-HauhauCS-Balanced-Q4_K_P.gguf --mmproj /srv/AI/models/Text/Qwen3.6-27B-Uncensored-HauhauCS-Balanced/mmproj-Qwen3.6-27B-Uncensored-HauhauCS-Balanced-f16.gguf --device SYCL0 --split-mode none --main-gpu 0 --temperature 1.0 --top-p 0.95 --min-p 0.0 --top-k 20 --repeat-penalty 1.0 --presence-penalty 1.5 -ngl 999 -c 262144 -ctk q8_0 -ctv q8_0 --flash-attn on --no-host --no-mmap --kv-unified --parallel 1 --cache-ram 0 --host 0.0.0.0 --port 8080 --verbose`

[llama.log](https://github.com/user-attachments/files/29236920/llama.log)

**Comment by arthw** [comment]
`env | grep SYCL`

**Comment by RinCat** [comment]
> `env | grep SYCL`

it is empty.
I only used oneapi override
```
:: initializing oneAPI environment ...
   -bash: BASH_VERSION = 5.3.9(1)-release
   args: Using "$@" for setvars.sh arguments: 
:: compiler -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpl -- latest
:: ipp -- latest
:: mkl -- latest
:: mpi -- latest
:: tbb -- latest
:: tcm -- latest
:: umf -- latest
:: oneAPI environment initialized ::
 ```

**Comment by arthw** [comment]
`export ONEAPI_DEVICE_SELECTOR="level_zero:0`

**Comment by RinCat** [comment]
Samething, and here is the full env

```
CLASSPATH=/opt/intel/oneapi/mpi/2021.18/share/java/mpi.jar
CMAKE_PREFIX_PATH=/opt/intel/oneapi/tbb/2023.0/env/..:/opt/intel/oneapi/mkl/2026.0/lib/cmake:/opt/intel/oneapi/ipp/2026.0/lib/cmake/ipp:/opt/intel/oneapi/dpl/2022.12/lib/cmake/oneDPL:/opt/intel/oneapi/dnnl/2026.0/lib/cmake:/opt/intel/oneapi/compiler/2026.0
CMPLR_ROOT=/opt/intel/oneapi/compiler/2026.0
CONFIG_PROTECT_MASK='/etc/sandbox.d /etc/gentoo-release /etc/ca-certificates.conf'
CPATH=/opt/intel/oneapi/umf/1.1/include:/opt/intel/oneapi/dev-utilities/2026.0/include
CPLUS_INCLUDE_PATH=/opt/intel/oneapi/umf/1.1/include:/opt/intel/oneapi/tbb/2023.0/env/../include:/opt/intel/oneapi/mpi/2021.18/include:/opt/intel/oneapi/mkl/2026.0/include:/opt/intel/oneapi/ipp/2026.0/include:/opt/intel/oneapi/dpl/2022.12/include:/opt/intel/oneapi/dnnl/2026.0/include
C_INCLUDE_PATH=/opt/intel/oneapi/umf/1.1/include:/opt/intel/oneapi/tbb/2023.0/env/../include:/opt/intel/oneapi/mpi/2021.18/include:/opt/intel/oneapi/mkl/2026.0/include:/opt/intel/oneapi/ipp/2026.0/include:/opt/intel/oneapi/dnnl/2026.0/include
DIAGUTIL_PATH=/opt/intel/oneapi/compiler/2026.0/etc/compiler/sys_check/sys_check.sh
DNNLROOT=/opt/intel/oneapi/dnnl/2026.0
DPLROOT=/opt/intel/oneapi/dpl/2022.12
DPL_ROOT=/opt/intel/oneapi/dpl/2022.12
EDITOR=vim
FI_PROVIDER_PATH=/opt/intel/oneapi/mpi/2021.18/opt/mpi/libfabric/lib/prov:/usr/lib64/libfabric
GCC_SPECS=''
GDB_INFO=/opt/intel/oneapi/debugger/2026.0/share/info/
GPG_TTY=/dev/pts/1
HOME=/root
INFOPATH=/opt/intel/oneapi/debugger/2026.0/share/info:/usr/share/gcc-data/x86_64-pc-linux-gnu/15/info:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.46.0/info:/usr/share/autoconf-2.72/info:/usr/share/automake-1.18.1/info:/usr/share/info
INTEL_PYTHONHOME=/opt/intel/oneapi/debugger/2026.0/opt/debugger
IPPROOT=/opt/intel/oneapi/ipp/2026.0
IPP_TARGET_ARCH=intel64
I_MPI_ROOT=/opt/intel/oneapi/mpi/2021.18
LD_LIBRARY_PATH=/opt/intel/oneapi/tcm/1.5/lib:/opt/intel/oneapi/umf/1.1/lib:/opt/intel/oneapi/tcm/1.5/env/../lib:/opt/intel/oneapi/tbb/2023.0/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.18/opt/mpi/libfabric/lib:/opt/intel/oneapi/mpi/2021.18/lib:/opt/intel/oneapi/mkl/2026.0/lib:/opt/intel/oneapi/ipp/2026.0/lib:/opt/intel/oneapi/dnnl/2026.0/lib:/opt/intel/oneapi/debugger/2026.0/opt/debugger/lib:/opt/intel/oneapi/compiler/2026.0/opt/compiler/lib:/opt/intel/oneapi/compiler/2026.0/lib
LESS='-R -M --shift 5'
LESSOPEN='|lesspipe %s'
LIBRARY_PATH=/opt/intel/oneapi/tcm/1.5/lib:/opt/intel/oneapi/umf/1.1/lib:/opt/intel/oneapi/tbb/2023.0/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.18/lib:/opt/intel/oneapi/mkl/2026.0/lib:/opt/intel/oneapi/ipp/2026.0/lib:/opt/intel/oneapi/dnnl/2026.0/lib:/opt/intel/oneapi/compiler/2026.0/lib
LOGNAME=root
MANPAGER=manpager
MANPATH=/opt/intel/oneapi/mpi/2021.18/share/man:/opt/intel/oneapi/debugger/2026.0/share/man:/opt/intel/oneapi/compiler/2026.0/share/man:/usr/share/gcc-data/x86_64-pc-linux-gnu/15/man:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.46.0/man:/usr/local/share/man:/usr/share/man:/usr/lib/llvm/21/share/man:/usr/lib/llvm/16/share/man
MANPATHN=''
MKLROOT=/opt/intel/oneapi/mkl/2026.0
NLSPATH=/opt/intel/oneapi/compiler/2026.0/lib/compiler/locale/%l_%t/%N
OCL_ICD_FILENAMES=/opt/intel/oneapi/compiler/2026.0/lib/libintelocl.so
OLDPWD=/tmp/llama.cpp/build-sycl
ONEAPI_DEVICE_SELECTOR=level_zero:0
ONEAPI_ROOT=/opt/intel/oneapi
PAGER=/usr/bin/less
PATH=/opt/intel/oneapi/mpi/2021.18/bin:/opt/intel/oneapi/mkl/2026.0/bin:/opt/intel/oneapi/dev-utilities/2026.0/bin:/opt/intel/oneapi/debugger/2026.0/opt/debugger/bin:/opt/intel/oneapi/compiler/2026.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/21/bin:/usr/lib/llvm/16/bin
PKG_CONFIG_PATH=/opt/intel/oneapi/tbb/2023.0/env/../lib/pkgconfig:/opt/intel/oneapi/mpi/2021.18/lib/pkgconfig:/opt/intel/oneapi/mkl/2026.0/lib/pkgconfig:/opt/intel/oneapi/dpl/2022.12/lib/pkgconfig:/opt/intel/oneapi/dnnl/2026.0/lib/pkgconfig:/opt/intel/oneapi/compiler/2026.0/lib/pkgconfig
PWD=/tmp/llama.cpp/build-sycl/bin
SETVARS_COMPLETED=1
SHELL=/bin/zsh
SHLVL=1
TBBROOT=/opt/intel/oneapi/tbb/2023.0/env/..
TCMROOT=/opt/intel/oneapi/tcm/1.5/env/..
TCM_ROOT=/opt/intel/oneapi/tcm/1.5
TERM=tmux-256color
UMF_ROOT=/opt/intel/oneapi/umf/1.1
USER=root
VISUAL=vim
```

**Comment by arthw** [comment]
Got it!
I don't see any clue.

I will reproduce it locally.

**Comment by RinCat** [comment]
nvm, it was a bug in Intel Graphics Compiler, updating it fixed this issue.
