### ISSUE TITLE
Compile bug: gcc-12: error: unrecognized command-line option ‘-compress-mode=size’

### ISSUE THREAD

**Issue by KPFprojects** [ggml-org/llama.cpp#14260]
### Git commit

$ git rev-parse HEAD
ef035803eb9dbc306ea9a8ff82e30af12b567cf7

### Operating systems

Linux Ubuntu 25.04 
kernel 6.14.0-15-generic
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  575.57.08  Release Build

### GGML backends

CUDA

### Problem description & steps to reproduce

I am trying to compile llama.cpp with CUDA support:
$ cmake -B build -DGGML_CUDA=ON -DGGML_CCACHE=OFF
$ cmake --build build --config Release

### First Bad Commit

I don't know when the issue first started.

### Compile command

```shell
$ cmake -B build -DGGML_CUDA=ON -DGGML_CCACHE=OFF
$ cmake --build build --config Release
```

### Relevant log output

```shell
$ cmake -B build -DGGML_CUDA=ON -DGGML_CCACHE=OFF
-- The C compiler identification is GNU 14.2.0
-- The CXX compiler identification is GNU 14.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.48.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- Found CUDAToolkit: /usr/local/cuda/targets/x86_64-linux/include (found version "12.9.86")
-- CUDA Toolkit found
-- Using CUDA architectures: native
-- The CUDA compiler identification is NVIDIA 12.2.140 with host compiler GNU 12.4.0
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- CUDA host compiler is GNU 12.4.0
-- Including CUDA backend
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "8.12.1")
-- Configuring done (5.1s)
-- Generating done (0.1s)


$ cmake --build build --config Release
[  0%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml.c.o
[  0%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml.cpp.o
[  1%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-alloc.c.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-backend.cpp.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-opt.cpp.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-threading.cpp.o
[  2%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-quants.c.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o
[  2%] Linking CXX shared library ../../bin/libggml-base.so
[  2%] Built target ggml-base
[  3%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/acc.cu.o
gcc-12: error: unrecognized command-line option ‘-compress-mode=size’
gmake[2]: *** [ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/build.make:80: ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/acc.cu.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2226: ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/all] Error 2
```

**Comment by slaren** [comment]
cmake is detecting CUDA 12.9, but your compiler in `/usr/bin/nvcc` seems to be CUDA 12.4.

**Comment by KPFprojects** [comment]
> cmake is detecting CUDA 12.9, but your compiler in `/usr/bin/nvcc` seems to be CUDA 12.4.

That is correct. Previous releases have built with that. I think the last time I tried to build was maybe a week or two ago and it worked despite the disparity. 

```
$ which nvcc
/usr/local/cuda-12.9/bin/nvcc


$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Tue_May_27_02:21:03_PDT_2025
Cuda compilation tools, release 12.9, V12.9.86
Build cuda_12.9.r12.9/compiler.36037853_0


$ cmake -B build -DGGML_CUDA=ON -DGGML_CCACHE=OFF -DCUDAToolkit_ROOT=/usr/local/cuda-12.9
-- The C compiler identification is GNU 14.2.0
-- The CXX compiler identification is GNU 14.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.48.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- Found CUDAToolkit: /usr/local/cuda-12.9/targets/x86_64-linux/include (found version "12.9.86")
-- CUDA Toolkit found
-- Using CUDA architectures: native
-- The CUDA compiler identification is NVIDIA 12.2.140 with host compiler GNU 12.4.0
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- CUDA host compiler is GNU 12.4.0
-- Including CUDA backend
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "8.12.1")
-- Configuring done (5.1s)
-- Generating done (0.1s)
```

**Comment by KPFprojects** [comment]
If I try the following:
```
$ cmake -B build -DGGML_CUDA=ON -DGGML_CCACHE=OFF -DCMAKE_CUDA_COMPILER=/usr/local/cuda-12.9/bin/nvcc -DCUDAToolkit_ROOT=/usr/local/cuda-12.9
-- The C compiler identification is GNU 14.2.0
-- The CXX compiler identification is GNU 14.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.48.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- Found CUDAToolkit: /usr/local/cuda-12.9/targets/x86_64-linux/include (found version "12.9.86")
-- CUDA Toolkit found
-- Using CUDA architectures: native
CMake Error at /usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:865 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/local/cuda-12.9/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp -v


  The output was:

  2

  nvcc warning : Support for offline compilation for architectures prior to
  '<compute/sm/lto>_75' will be removed in a future release (Use
  -Wno-deprecated-gpu-targets to suppress warning).

  #$ _NVVM_BRANCH_=nvvm

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ _HERE_=/usr/local/cuda-12.9/bin

  #$ _THERE_=/usr/local/cuda-12.9/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_DIR_=targets/x86_64-linux

  #$ TOP=/usr/local/cuda-12.9/bin/..

  #$ CICC_PATH=/usr/local/cuda-12.9/bin/../nvvm/bin

  #$ NVVMIR_LIBRARY_DIR=/usr/local/cuda-12.9/bin/../nvvm/libdevice

  #$
  LD_LIBRARY_PATH=/usr/local/cuda-12.9/bin/../lib:/usr/local/cuda-12.9/lib64

  #$
  PATH=/usr/local/cuda-12.9/bin/../nvvm/bin:/usr/local/cuda-12.9/bin:/home/user/llama.cpp/build/bin:/usr/local/cuda-12.9/bin:/home/user/miniconda3/bin:/home/user/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin


  #$ INCLUDES="-I/usr/local/cuda-12.9/bin/../targets/x86_64-linux/include"

  #$ LIBRARIES=
  "-L/usr/local/cuda-12.9/bin/../targets/x86_64-linux/lib/stubs"
  "-L/usr/local/cuda-12.9/bin/../targets/x86_64-linux/lib"

  #$ CUDAFE_FLAGS=

  #$ PTXAS_FLAGS=

  #$ rm tmp/a_dlink.reg.c

  #$ gcc -D__CUDA_ARCH_LIST__=520 -D__NV_LEGACY_LAUNCH -E -x c++ -D__CUDACC__
  -D__NVCC__ "-I/usr/local/cuda-12.9/bin/../targets/x86_64-linux/include"
  -D__CUDACC_VER_MAJOR__=12 -D__CUDACC_VER_MINOR__=9
  -D__CUDACC_VER_BUILD__=86 -D__CUDA_API_VER_MAJOR__=12
  -D__CUDA_API_VER_MINOR__=9 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1
  -D__CUDACC_DEVICE_ATOMIC_BUILTINS__=1 -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" -o "tmp/CMakeCUDACompilerId.cpp4.ii"

  #$ cudafe++ --c++17 --gnu_version=140200 --display_error_number
  --orig_src_file_name "CMakeCUDACompilerId.cu" --orig_src_path_name
  "/home/user/llama.cpp/build/CMakeFiles/3.31.6/CompilerIdCUDA/CMakeCUDACompilerId.cu"
  --allow_managed --m64 --parse_templates --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.cpp" --stub_file_name
  "CMakeCUDACompilerId.cudafe1.stub.c" --gen_module_id_file
  --module_id_file_name "tmp/CMakeCUDACompilerId.module_id"
  "tmp/CMakeCUDACompilerId.cpp4.ii"

  /usr/include/x86_64-linux-gnu/bits/mathcalls.h(79): error: exception
  specification is incompatible with that of previous function "cospi"
  (declared at line 2601 of
  /usr/local/cuda-12.9/bin/../targets/x86_64-linux/include/crt/math_functions.h)


     extern double cospi (double __x) noexcept (true); extern double __cospi (double __x) noexcept (true);
                                      ^

  /usr/include/x86_64-linux-gnu/bits/mathcalls.h(81): error: exception
  specification is incompatible with that of previous function "sinpi"
  (declared at line 2556 of
  /usr/local/cuda-12.9/bin/../targets/x86_64-linux/include/crt/math_functions.h)


     extern double sinpi (double __x) noexcept (true); extern double __sinpi (double __x) noexcept (true);
                                      ^

  /usr/include/x86_64-linux-gnu/bits/mathcalls.h(79): error: exception
  specification is incompatible with that of previous function "cospif"
  (declared at line 2623 of
  /usr/local/cuda-12.9/bin/../targets/x86_64-linux/include/crt/math_functions.h)


     extern float cospif (float __x) noexcept (true); extern float __cospif (float __x) noexcept (true);
                                     ^

  /usr/include/x86_64-linux-gnu/bits/mathcalls.h(81): error: exception
  specification is incompatible with that of previous function "sinpif"
  (declared at line 2579 of
  /usr/local/cuda-12.9/bin/../targets/x86_64-linux/include/crt/math_functions.h)


     extern float sinpif (float __x) noexcept (true); extern float __sinpif (float __x) noexcept (true);
                                     ^
  4 errors detected in the compilation of "CMakeCUDACompilerId.cu".

  # --error 0x2 --

Call Stack (most recent call first):
  /usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  /usr/share/cmake-3.31/Modules/CMakeDetermineCUDACompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID)
  ggml/src/ggml-cuda/CMakeLists.txt:43 (enable_language)


-- Configuring incomplete, errors occurred!
```

**Comment by TheTerrasque** [comment]
Also seeing this. This seem to have happened after updating the server, which also installed cuda 12.9 - env var were still pointing to 12.5

Even after updating env vars to point to 12.9 it still gives same error. This is on ubuntu 22.04 with nvidia cuda repositories added

**Comment by WasamiKirua** [comment]
same issue here. This must be related to  Ubuntu 25 because the build was perfectly working in ubuntu 24.04 with the same procedure I have always used for the installation of drivers, cuda and so on. 

```
cmake -B build -DGGML_CUDA=ON
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native 
-- CUDA Toolkit found
-- Using CUDA architectures: native
CMake Error at /usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:865 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/local/cuda-12.9/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp -v



  The output was:

  2

  nvcc warning : Support for offline compilation for architectures prior to
  '<compute/sm/lto>_75' will be removed in a future release (Use
  -Wno-deprecated-gpu-targets to suppress warning).

  #$ _NVVM_BRANCH_=nvvm

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ _HERE_=/usr/local/cuda-12.9/bin

  #$ _THERE_=/usr/local/cuda-12.9/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_DIR_=targets/x86_64-linux

  #$ TOP=/usr/local/cuda-12.9/bin/..

  #$ CICC_PATH=/usr/local/cuda-12.9/bin/../nvvm/bin

  #$ NVVMIR_LIBRARY_DIR=/usr/local/cuda-12.9/bin/../nvvm/libdevice

  #$
  LD_LIBRARY_PATH=/usr/local/cuda-12.9/bin/../lib:/usr/local/cuda/lib64:/usr/local/cuda-12.9/lib64


  #$
  PATH=/usr/local/cuda-12.9/bin/../nvvm/bin:/usr/local/cuda-12.9/bin:/home/wasami/.atuin/bin:/home/wasami/.pyenv/shims:/home/wasami/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/cuda-12.9/bin


  #$ INCLUDES="-I/usr/local/cuda-12.9/bin/../targets/x86_64-linux/include"

  #$ LIBRARIES=
  "-L/usr/local/cuda-12.9/bin/../targets/x86_64-linux/lib/stubs"
  "-L/usr/local/cuda-12.9/bin/../targets/x86_64-linux/lib"

  #$ CUDAFE_FLAGS=

  #$ PTXAS_FLAGS=

  #$ rm tmp/a_dlink.reg.c

  #$ gcc -D__CUDA_ARCH_LIST__=520 -D__NV_LEGACY_LAUNCH -E -x c++ -D__CUDACC__
  -D__NVCC__ "-I/usr/local/cuda-12.9/bin/../targets/x86_64-linux/include"
  -D__CUDACC_VER_MAJOR__=12 -D__CUDACC_VER_MINOR__=9
  -D__CUDACC_VER_BUILD__=86 -D__CUDA_API_VER_MAJOR__=12
  -D__CUDA_API_VER_MINOR__=9 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1
  -D__CUDACC_DEVICE_ATOMIC_BUILTINS__=1 -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" -o "tmp/CMakeCUDACompilerId.cpp4.ii"

  #$ cudafe++ --c++17 --gnu_version=140200 --display_error_number
  --orig_src_file_name "CMakeCUDACompilerId.cu" --orig_src_path_name
  "/home/wasami/llama.cpp/build/CMakeFiles/3.31.6/CompilerIdCUDA/CMakeCUDACompilerId.cu"
  --allow_managed --m64 --parse_templates --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.cpp" --stub_file_name
  "CMakeCUDACompilerId.cudafe1.stub.c" --gen_module_id_file
  --module_id_file_name "tmp/CMakeCUDACompilerId.module_id"
  "tmp/CMakeCUDACompilerId.cpp4.ii"

  /usr/include/x86_64-linux-gnu/bits/mathcalls.h(79): error: exception
  specification is incompatible with that of previous function "cospi"
  (declared at line 2601 of
  /usr/local/cuda-12.9/bin/../targets/x86_64-linux/include/crt/math_functions.h)


     extern double cospi (double __x) noexcept (true); extern double __cospi (double __x) noexcept (true);
                                      ^

  

  /usr/include/x86_64-linux-gnu/bits/mathcalls.h(81): error: exception
  specification is incompatible with that of previous function "sinpi"
  (declared at line 2556 of
  /usr/local/cuda-12.9/bin/../targets/x86_64-linux/include/crt/math_functions.h)


     extern double sinpi (double __x) noexcept (true); extern double __sinpi (double __x) noexcept (true);
                                      ^

  

  /usr/include/x86_64-linux-gnu/bits/mathcalls.h(79): error: exception
  specification is incompatible with that of previous function "cospif"
  (declared at line 2623 of
  /usr/local/cuda-12.9/bin/../targets/x86_64-linux/include/crt/math_functions.h)


     extern float cospif (float __x) noexcept (true); extern float __cospif (float __x) noexcept (true);
                                     ^

  

  /usr/include/x86_64-linux-gnu/bits/mathcalls.h(81): error: exception
  specification is incompatible with that of previous function "sinpif"
  (declared at line 2579 of
  /usr/local/cuda-12.9/bin/../targets/x86_64-linux/include/crt/math_functions.h)


     extern float sinpif (float __x) noexcept (true); extern float __sinpif (float __x) noexcept (true);
                                     ^

  

  4 errors detected in the compilation of "CMakeCUDACompilerId.cu".

  # --error 0x2 --





Call Stack (most recent call first):
  /usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  /usr/share/cmake-3.31/Modules/CMakeDetermineCUDACompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID)
  ggml/src/ggml-cuda/CMakeLists.txt:43 (enable_language)
```

`llama.cpp on  master is 📦 v0.0.0 via △ via 🐍 system 
❯ which nvcc
/usr/local/cuda-12.9/bin/nvcc

llama.cpp on  master is 📦 v0.0.0 via △ via 🐍 system 
❯ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Tue_May_27_02:21:03_PDT_2025
Cuda compilation tools, release 12.9, V12.9.86
Build cuda_12.9.r12.9/compiler.36037853_0`

**Comment by TheTerrasque** [comment]
I seem to have figured out what caused it. I modified the cmake file referred to in https://github.com/ggml-org/llama.cpp/issues/12325#issuecomment-2722117184 to print both toolkit and compiler, and noticed it used nvcc 12.1 - I have the files for that still, but there's no symlinks or env vars pointing to it. 

Eventually I grepped the llama.cpp src folder, and found `build/CMakeCache.txt` having a ref to that old compiler.

I deleted that file and ran cmake again, and now it compiled successfully.

**Comment by KPFprojects** [comment]
> I seem to have figured out what caused it. I modified the cmake file referred to in [#12325 (comment)](https://github.com/ggml-org/llama.cpp/issues/12325#issuecomment-2722117184) to print both toolkit and compiler, and noticed it used nvcc 12.1 - I have the files for that still, but there's no symlinks or env vars pointing to it.
> 
> Eventually I grepped the llama.cpp src folder, and found `build/CMakeCache.txt` having a ref to that old compiler.
> 
> I deleted that file and ran cmake again, and now it compiled successfully.

$ cmake -B build -DGGML_CUDA=ON -DGGML_CCACHE=OFF

does create a ./build/CMakeCache.txt with
//CUDA compiler
CMAKE_CUDA_COMPILER:FILEPATH=/usr/bin/nvcc
//Path to a program.
CUDAToolkit_NVCC_EXECUTABLE:FILEPATH=/usr/local/cuda-12.9/bin/nvcc

manually modifying
//CUDA compiler
CMAKE_CUDA_COMPILER:FILEPATH=/usr/local/cuda-12.9/bin/nvcc

then running 
$ cmake --build build --config Release
$ cmake --build build --config Release -j20
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- CUDA Toolkit found
-- Using CUDA architectures: native
-- CUDA host compiler is GNU 12.4.0
-- Including CUDA backend
-- Configuring done (0.2s)
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CUDA_COMPILER= /usr/local/cuda-12.9/bin/nvcc

-- The C compiler identification is GNU 14.2.0
-- The CXX compiler identification is GNU 14.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.48.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "8.12.1")
-- Configuring done (0.8s)
-- Generating done (0.1s)


and compilation finishes. But, when running llama-server or llama-cli with --n-gpu-layers 99 the following warning is seen:
warning: no usable GPU found, --gpu-layers option will be ignored
warning: one possible reason is that llama.cpp was compiled without GPU support

checking GPU usage confirms no VRAM being used.

Deleting /usr/bin/nvcc results in https://github.com/ggml-org/llama.cpp/issues/14260#issuecomment-2984114231 (above) errors.

Did your compilation compile with gpu support?

**Comment by TheTerrasque** [comment]
Yes, it compiled successfully with GPU support. In my case it seemed to be that CMAKE_CUDA_COMPILER path didn't update but instead used an old cached version. When I deleted the cache file and had cmake regenerate it, it picked the correct nvcc.
