### ISSUE TITLE
Compile bug: fatal error: 'hip/hip_fp16.h' file not found

### ISSUE THREAD

**Issue by MangoTCF** [ggml-org/llama.cpp#27067]
### Git commit

$git rev-parse HEAD
47a39665e7081dc482feec169961acc09750a5c4

### Operating systems

Linux

### GGML backends

HIP

### Problem description & steps to reproduce

Trying to compile llama-cpp on an Arch Linux container exactly "by the book" leads to this error appearing.
Funnily enough, adding `add_compile_options(-isystem /opt/rocm/include/)` to the top-level CMakeLists.txt works until it fails again, later, with `ld.lld: error: unable to find library -lamdhip64` 

### First Bad Commit

Unknown, may be an Arch regression or something

### Compile command

```shell
HIPCXX="$(hipconfig -l)/clang" HIP_PATH="$(hipconfig -R)"     cmake -S . -B build -DGGML_HIP=ON -DGPU_TARGETS=gfx1031 -DCMAKE_BUILD_TYPE=Release -GNinja     && cmake --build build --config Release -- -j 16
```

### Relevant log output

```shell
/home/mango/ai/llama.cpp/ggml/src/ggml-hip/../ggml-common.h:51:10: fatal error: 'hip/hip_fp16.h' file not found
   51 | #include <hip/hip_fp16.h>
      |          ^~~~~~~~~~~~~~~~
make[2]: *** [ggml/src/ggml-hip/CMakeFiles/ggml-hip.dir/build.make:130: ggml/src/ggml-hip/CMakeFiles/ggml-hip.dir/__/ggml-cuda/argmax.cu.o] Error 1
1 error generated when compiling for gfx1031.
```

**Comment by MangoTCF** [comment]
A very, very bad and dirty patch that seems to fix the compilation problem is this:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b2092d12d..1896f6269 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -2,6 +2,8 @@ cmake_minimum_required(VERSION 3.14...3.28) # for add_link_options and implicit
 project("llama.cpp" C CXX)
 include(CheckIncludeFileCXX)
 
+add_compile_options(-isystem /opt/rocm/include/)
+add_link_options(-L /opt/rocm/lib)
 ### llama.cpp version
 set(LLAMA_VERSION_MAJOR 0)
 set(LLAMA_VERSION_MINOR 1)
```
for the love of god do not use in production. also will almost certainly explode when trying to build non-HIP llama.cpp. will test my usecase and report back if this leads to further failures

**Comment by MangoTCF** [comment]
After some further testing this is ruled to be a cache issue. Sorry for taking your time, if any was taken. Closing now.
