### PR TITLE
fix: GLM-DSA crash in llama-tokenize when using vocab_only

### LINKED ISSUE #22026: llama-tokenize bug: llama-hparams.cpp:92: fatal error
### Name and Version

$ /Users/sidney_fong/maxx_local/llama.cpp/llama-cli --version
ggml_metal_device_init: tensor API disabled for pre-M5 and pre-A19 devices
ggml_metal_library_init: using embedded metal library
ggml_metal_library_init: loaded in 0.020 sec
ggml_metal_rsets_init: creating a residency set collection (keep_alive = 180 s)
ggml_metal_device_init: GPU name:   MTL0
ggml_metal_device_init: GPU family: MTLGPUFamilyApple9  (1009)
ggml_metal_device_init: GPU family: MTLGPUFamilyCommon3 (3003)
ggml_metal_device_init: GPU family: MTLGPUFamilyMetal3  (5001)
ggml_metal_device_init: simdgroup reduction   = true
ggml_metal_device_init: simdgroup matrix mul. = true
ggml_metal_device_init: has unified memory    = true
ggml_metal_device_init: has bfloat            = true
ggml_metal_device_init: has tensor            = false
ggml_metal_device_init: use residency sets    = true
ggml_metal_device_init: use shared buffers    = true
ggml_metal_device_init: recommendedMaxWorkingSetSize  = 498216.21 MB
version: 8826 (30dce2cf2)
built with AppleClang 15.0.0.15000309 for Darwin arm64

### Operating systems

Mac

### GGML backends

Metal

### Hardware

The legendary Mac Studio Ultra with 512GB RAM :D 

### Models

Only happens with GLM 5.1 so far:

https://huggingface.co/bartowski/zai-org_GLM-5.1-GGUF/blob/main/zai-org_GLM-5.1-Q4_K_M

### Problem description & steps to reproduce

(Note: normal inference seems fine AFAICT. Only crashes with the tokenize command)

Crashes when running llama-tokenize:

```
llama-tokenize -m zai-org_GLM-5.1-Q4_K_M-00001-of-00012.gguf -p 'haha'
```

...

```
/Users/runner/work/llama.cpp/llama.cpp/src/llama-hparams.cpp:92: fatal error
WARNING: Using native backtrace. Set GGML_BACKTRACE_LLDB for more info.
WARNING: GGML_BACKTRACE_LLDB may cause native MacOS Terminal.app to crash.
See: https://github.com/ggml-org/llama.cpp/pull/17869
0   libggml-base.0.9.11.dylib           0x0000000104a50468 ggml_print_backtrace + 276
1   libggml-base.0.9.11.dylib           0x0000000104a50654 ggml_abort + 156
2   libllama.0.0.8826.dylib             0x00000001046b84cc _ZNK13llama_hparams17n_embd_head_v_mlaEv + 0
3   libllama.0.0.8826.dylib             0x000000010474a7b0 _ZNK11llama_model10print_infoEv + 1188
4   libllama.0.0.8826.dylib             0x0000000104669820 _ZL31llama_model_load_from_file_implP12gguf_contextPFvP11ggml_tensorPvES3_RKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEERNS6_6vectorISC_NSA_ISC_EEEEP7__sFILE18llama_model_params + 3272
5   libllama.0.0.8826.dylib             0x000000010466a084 llama_model_load_from_file + 192
6   llama-tokenize                      0x0000000104333d90 main + 3348
7   dyld                                0x00000001944f2b98 start + 6076
```

### First Bad Commit

_No response_

### Relevant log output

<details>
<summary>Logs</summary>

```console

```

[tokenize-crash.txt](https://github.com/user-attachments/files/26807590/tokenize-crash.txt)

</details>

### PR DESCRIPTION
**Pull request by ssam18**
When running llama-tokenize with GLM-DSA models, the process crashes with a fatal error in llama-hparams.cpp. This happens because vocab_only mode skips the full hparams loading, leaving n_layer and the MLA params uninitialized, but print_info still calls n_embd_head_k_mla() which internally falls back to n_embd_head_k(0) and hits the abort when n_layer is 0. Fixed by guarding the DeepSeek2/GLM-DSA/Mistral4 print block with consistent with how other non-vocab hparams are already handled in print_info. Fixes #22026

### CODE REVIEW

**Review by CISC — APPROVED** [review]
Could you add it to the other arch blocks too please, none of those should/need be printed?

**Comment by ssam18** [comment]
> Could you add it to the other arch blocks too please, none of those should/need be printed?

done

**Review by CISC — APPROVED** [review]

**Review by taronaeo — APPROVED** [review]

**Review by CISC — APPROVED** [review]
