### ISSUE TITLE
Eval bug:  Vulkan SIGSEGV on model load in libvulkan on AMD Polaris

### ISSUE THREAD

**Issue by FireCulex** [ggml-org/llama.cpp#27403]
### Name and Version

~/github/llama.cpp tags/b10078*
❯ llama-cli --version
[2026-08-19 11:08:14.043] [MANGOHUD] [warning] [gpu_fdinfo.cpp:428] Intel i915 gt dir: failed to open /sys/bus/pci/devices/0000:00:02.0/drm/card1/gt/gt0/throttle_reason_status
[2026-08-19 11:08:14.044] [MANGOHUD] [info] [gpu.cpp:90] Set renderD129 as active GPU (driver=amdgpu id=1002:67df pci_dev=0000:01:00.0)
[2026-08-19 11:08:14.053] [MANGOHUD] [info] [cpu.cpp:636] hwmon: using input: /sys/class/hwmon/hwmon5/temp1_input
version: 10078 (f04801018)
built with GNU 16.1.1 for Linux x86_64

### Operating systems

Linux

### GGML backends

Vulkan

### Hardware

❯ sudo lspci -vvv -s 01:00.0
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev e7) (prog-if 00 [VGA controller])
	Subsystem: Sapphire Technology Limited Radeon RX 570 Pulse 4GB
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0, Cache Line Size: 64 bytes
	Interrupts: pin B disabled, MSI(X) routed to IRQ 142
	Region 0: Memory at 2000000000 (64-bit, prefetchable) [size=8G]
	Region 2: Memory at 2200000000 (64-bit, prefetchable) [size=2M]
	Region 4: I/O ports at e000 [size=256]
	Region 5: Memory at f7e00000 (32-bit, non-prefetchable) [size=256K]
	Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [48] Vendor Specific Information: Len=08 <?>
	Capabilities: [50] Power Management version 3
		Flags: PMEClk- DSI- D1+ D2+ AuxCurrent=0mA PME(D0-,D1+,D2+,D3hot+,D3cold+)
		Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [58] Express (v2) Legacy Endpoint, IntMsgNum 0
		DevCap:	MaxPayload 256 bytes, PhantFunc 0, Latency L0s <4us, L1 unlimited
			ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset- TEE-IO-
		DevCtl:	CorrErr- NonFatalErr- FatalErr- UnsupReq-
			RlxdOrd+ ExtTag+ PhantFunc- AuxPwr- NoSnoop+
			MaxPayload 256 bytes, MaxReadReq 512 bytes
		DevSta:	CorrErr+ NonFatalErr- FatalErr- UnsupReq+ AuxPwr- TransPend-
		LnkCap:	Port #0, Speed 8GT/s, Width x16, ASPM L1, Exit Latency L1 <1us
			ClockPM+ Surprise- LLActRep- BwNot- ASPMOptComp+
		LnkCtl:	ASPM Disabled; RCB 64 bytes, LnkDisable- CommClk+
			ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt- FltModeDis-
		LnkSta:	Speed 8GT/s, Width x16
			TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
		DevCap2: Completion Timeout: Not Supported, TimeoutDis- NROPrPrP- LTR+
			 10BitTagComp- 10BitTagReq- OBFF Not Supported, ExtFmt+ EETLPPrefix+, MaxEETLPPrefixes 1
			 EmergencyPowerReduction Not Supported, EmergencyPowerReductionInit-
			 FRS-
			 AtomicOpsCap: 32bit+ 64bit+ 128bitCAS-
		DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis-
			 AtomicOpsCtl: ReqEn+
			 IDOReq- IDOCompl- LTR+ EmergencyPowerReductionReq-
			 10BitTagReq- OBFF Disabled, EETLPPrefixBlk-
		LnkCap2: Supported Link Speeds: 2.5-8GT/s, Crosslink- Retimer- 2Retimers- DRS-
		LnkCtl2: Target Link Speed: 8GT/s, EnterCompliance- SpeedDis-
			 Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
			 Compliance Preset/De-emphasis: -6dB de-emphasis, 0dB preshoot
		LnkSta2: Current De-emphasis Level: -3.5dB, EqualizationComplete+ EqualizationPhase1+
			 EqualizationPhase2+ EqualizationPhase3+ LinkEqualizationRequest-
			 Retimer- 2Retimers- CrosslinkRes: unsupported, FltMode-
	Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit+
		Address: 00000000fee00538  Data: 0000
	Capabilities: [100 v1] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
	Capabilities: [150 v2] Advanced Error Reporting
		UESta:	DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP-
			ECRC- UnsupReq- ACSViol- UncorrIntErr- BlockedTLP- AtomicOpBlocked- TLPBlockedErr-
			PoisonTLPBlocked- DMWrReqBlocked- IDECheck- MisIDETLP- PCRC_CHECK- TLPXlatBlocked-
		UEMsk:	DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP-
			ECRC- UnsupReq- ACSViol- UncorrIntErr- BlockedTLP- AtomicOpBlocked- TLPBlockedErr-
			PoisonTLPBlocked- DMWrReqBlocked- IDECheck- MisIDETLP- PCRC_CHECK- TLPXlatBlocked-
		UESvrt:	DLP+ SDES+ TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF+ MalfTLP+
			ECRC- UnsupReq- ACSViol- UncorrIntErr+ BlockedTLP- AtomicOpBlocked- TLPBlockedErr-
			PoisonTLPBlocked- DMWrReqBlocked- IDECheck- MisIDETLP- PCRC_CHECK- TLPXlatBlocked-
		CESta:	RxErr- BadTLP- BadDLLP- Rollover- Timeout- AdvNonFatalErr+ CorrIntErr- HeaderOF-
		CEMsk:	RxErr- BadTLP- BadDLLP- Rollover- Timeout- AdvNonFatalErr+ CorrIntErr- HeaderOF-
		AERCap:	First Error Pointer: 00, ECRCGenCap+ ECRCGenEn- ECRCChkCap+ ECRCChkEn-
			MultHdrRecCap- MultHdrRecEn- TLPPfxPres- HdrLogCap-
		HeaderLog: 00000000 00000000 00000000 00000000
	Capabilities: [200 v1] Physical Resizable BAR
		BAR 0: current size: 8GB, supported: 256MB 512MB 1GB 2GB 4GB 8GB
	Capabilities: [270 v1] Secondary PCI Express
		LnkCtl3: LnkEquIntrruptEn- PerformEqu-
		LaneErrStat: 0
	Capabilities: [2b0 v1] Address Translation Service (ATS)
		ATSCap:	Invalidate Queue Depth: 00
		ATSCtl:	Enable-, Smallest Translation Unit: 00
	Capabilities: [2c0 v1] Page Request Interface (PRI)
		PRICtl: Enable- Reset-
		PRISta: RF- UPRGI- Stopped+ PASID-
		Page Request Capacity: 00000020, Page Request Allocation: 00000000
	Capabilities: [2d0 v1] Process Address Space ID (PASID)
		PASIDCap: Exec+ Priv+, Max PASID Width: 10
		PASIDCtl: Enable- Exec- Priv-
	Capabilities: [320 v1] Latency Tolerance Reporting
		Max snoop latency: 71680ns
		Max no snoop latency: 71680ns
	Capabilities: [328 v1] Alternative Routing-ID Interpretation (ARI)
		ARICap:	MFVC- ACS-, Next Function: 1
		ARICtl:	MFVC- ACS-, Function Group: 0
	Capabilities: [370 v1] L1 PM Substates
		L1SubCap: PCI-PM_L1.2+ PCI-PM_L1.1+ ASPM_L1.2+ ASPM_L1.1+ L1_PM_Substates+
			  PortCommonModeRestoreTime=0us PortTPowerOnTime=170us
		L1SubCtl1: PCI-PM_L1.2- PCI-PM_L1.1- ASPM_L1.2- ASPM_L1.1-
			   T_CommonMode=0us LTR1.2_Threshold=0ns
		L1SubCtl2: T_PwrOn=10us
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu

### Models

Qwen3.5-4B.Q4_K_M.gguf
Qwen3.5-9B-Q4_K_M.gguf

### Problem description & steps to reproduce

on 665892536 did a  git pull. Noticed llama-server crashed with a status error of 500. llama-cli would also crash. Did a git bisects until I found offending commit.

### First Bad Commit

/github/llama.cpp tags/b10077*
❯ git bisect good
f0480101800d33a72ed58fa86a8a6be01b54bd52 is the first 'bad' commit
commit f0480101800d33a72ed58fa86a8a6be01b54bd52 (tag: b10078)
Author: Winston Ma <winstonma@ymail.com>
Date:   Tue Jul 21 23:40:45 2026 +0800

    vulkan: Refactor vk_queue to use per-instance mutexes and unique handles (#23570)

    * Refactor vk_queue to use per-instance mutexes and unique handles

    * integrates VK_KHR_internally_synchronized_queues, abstracting the queue submission into a polymorphic interface that completely bypasses host-side mutex locking when driver-side synchronization is supported

    * fix compilation error

    * fix duplicate pNext chain for VkPhysicalDeviceInternallySynchronizedQueuesFeaturesKHR

    * add fallback defines for VK_KHR_internally_synchronized_queues

    * add null checks for queues in vk_device_struct destructor

    * use unique_ptr for outer queues to enforce exclusive ownership and optimize lifetime

    * use static constexpr for eInternallySynchronizedKHR

    * add lock guard to ggml_vk_create_aliased_queue for thread safety

    * initialize sync_query_features.internallySynchronizedQueues to VK_FALSE

    * reuse sync_query_features for internallySynchronizedQueues and simplify chaining

    * refactor internallySynchronizedQueues detection

    * fix internallySynchronizedQueues query guard

    * use eInternallySynchronizedKHR constant

    * fix self-referential alias for eInternallySynchronizedKHR

    * use macro for eInternallySynchronizedKHR fallback

    * fix internallySynchronizedQueues query timing in ggml-vulkan.cpp to prevent device creation mismatch

    * reset sync_query_features.pNext before reusing in device creation chain, also removed the redundant second probe call

    * refactor internally synchronized queues detection to use chained feature query and avoid redundant API calls

    * Update ggml/src/ggml-vulkan/ggml-vulkan.cpp

    Co-authored-by: Jeff Bolz <jbolz@nvidia.com>

    * Update ggml/src/ggml-vulkan/ggml-vulkan.cpp

    Co-authored-by: Jeff Bolz <jbolz@nvidia.com>

    * Update ggml/src/ggml-vulkan/ggml-vulkan.cpp

    Co-authored-by: Jeff Bolz <jbolz@nvidia.com>

    * Update ggml/src/ggml-vulkan/ggml-vulkan.cpp

    Co-authored-by: Jeff Bolz <jbolz@nvidia.com>

    * Update ggml/src/ggml-vulkan/ggml-vulkan.cpp

    Co-authored-by: Jeff Bolz <jbolz@nvidia.com>

    * Update ggml/src/ggml-vulkan/ggml-vulkan.cpp

    Co-authored-by: Jeff Bolz <jbolz@nvidia.com>

    * rename sync_enable_features to internally_synchronized_queues_features

    * queue_flags is still computed before has_internally_synchronized_queues is set

    * fix trailing whitespace

    * replace eInternallySynchronizedKHR macro with static constexpr

    * preserve source queue semantics in single-queue aliased transfer queue

    * vulkan: fix cmd_pool access via pointer for compute_queue unique_ptr

    * vulkan: lock queue during debug label emission when not internally synchronized

    ---------

    Co-authored-by: Jeff Bolz <jbolz@nvidia.com>

 ggml/src/ggml-vulkan/ggml-vulkan.cpp | 195 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------
 1 file changed, 139 insertions(+), 56 deletions(-)

### Relevant log output

❯ build/bin/llama-cli --model /mnt/wd_black/Downloads/models/Qwen3.5-4B-Q4_K_M.gguf -n 1
[2026-08-19 10:11:51.963] [MANGOHUD] [warning] [gpu_fdinfo.cpp:428] Intel i915 gt dir: failed to open /sys/bus/pci/devices/0000:00:02.0/drm/card1/gt/gt0/throttle_reason_status
[2026-08-19 10:11:51.963] [MANGOHUD] [info] [gpu.cpp:90] Set renderD129 as active GPU (driver=amdgpu id=1002:67df pci_dev=0000:01:00.0)
[2026-08-19 10:11:51.972] [MANGOHUD] [info] [cpu.cpp:636] hwmon: using input: /sys/class/hwmon/hwmon5/temp1_input

Loading model... -fish: Job 1, 'build/bin/llama-cli --model /mn…' terminated by signal SIGSEGV (Address boundary error)

❯ sudo dmesg
[ 2188.889374] llama-cli[53691]: segfault at 0 ip 00007f0e5d8e7c70 sp 00007f0e213da2b0 error 6 in libvulkan.so.1.4.357[1dc70,7f0e5d8d1000+60000] likely on CPU 2 (core 2, socket 0)
[ 2188.889383] Code: 83 ec 10 64 48 8b 1c 25 28 00 00 00 48 89 5c 24 08 48 89 f3 48 89 e6 e8 6e fe ff ff 48 85 c0 74 24 48 8b 04 24 48 85 c0 74 1b <48> 89 03 31 c0 48 8b 54 24 08 64 48 2b 14 25 28 00 00 00 75 0d 48

$ zstd -dc /var/lib/systemd/coredump/core.llama-cli.1000.0c309be52c85452f9743b8c35eb00f9b.111160.1787164796000000.zst > /tmp/core2 && gdb -batch -ex "bt" -ex "quit" /home/culex/github/llama.cpp/build/bin/llama-cli /tmp/core2 2>&1
This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
  <https://debuginfod.cachyos.org>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[New LWP 111179]
[New LWP 111177]
[New LWP 111183]
[New LWP 111178]
[New LWP 111182]
[New LWP 111165]
[New LWP 111184]
[New LWP 111166]
[New LWP 111185]
[New LWP 111164]
[New LWP 111167]
[New LWP 111180]
[New LWP 111175]
[New LWP 111181]
[New LWP 111160]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `build/bin/llama-cli --model /mnt/wd_black/Downloads/models/Qwen3.5-4B-Q4_K_M.gguf -n 1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f37a217fc70 in ?? () from /usr/lib/libvulkan.so.1
[Current thread is 1 (Thread 0x7f37693fe6c0 (LWP 111179))]
#0  0x00007f37a217fc70 in ?? () from /usr/lib/libvulkan.so.1
#1  0x00007f377c25310a in ?? () from /usr/lib/mangohud/libMangoHud.so
#2  0x00007f37a218cb04 in ?? () from /usr/lib/libvulkan.so.1
#3  0x00007f37a218e88c in ?? () from /usr/lib/libvulkan.so.1
#4  0x00007f37a21afcd6 in vkCreateDevice () from /usr/lib/libvulkan.so.1
#5  0x00007f37a249e985 in ggml_vk_get_device(unsigned long) () from /home/culex/github/llama.cpp/build/bin/libggml-vulkan.so.0
#6  0x00007f37a24a3e95 in ggml_backend_vk_host_buffer_type () from /home/culex/github/llama.cpp/build/bin/libggml-vulkan.so.0
#7  0x00007f37a599bdf2 in make_cpu_buft_list(std::vector<llama_device, std::allocator<llama_device> > const&, bool, bool) () from /home/culex/github/llama.cpp/build/bin/libllama.so.0
#8  0x00007f37a59a66c5 in llama_model_base::load_tensors(llama_model_loader&) () from /home/culex/github/llama.cpp/build/bin/libllama.so.0
#9  0x00007f37a58c06d3 in llama_model_load(gguf_context*, void (*)(ggml_tensor*, void*), void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, _IO_FILE*, llama_model_params&) () from /home/culex/github/llama.cpp/build/bin/libllama.so.0
#10 0x00007f37a58c2052 in llama_model_load_from_file_impl(gguf_context*, void (*)(ggml_tensor*, void*), void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, _IO_FILE*, llama_model_params) () from /home/culex/github/llama.cpp/build/bin/libllama.so.0
#11 0x00007f37a58c3c6e in llama_model_load_from_file () from /home/culex/github/llama.cpp/build/bin/libllama.so.0
#12 0x00007f37a5e74bdf in common_get_device_memory_data_impl(char const*, llama_model_params const*, llama_context_params const*, std::vector<ggml_backend_device*, std::allocator<ggml_backend_device*> >&, unsigned int&, unsigned int&, unsigned int&, ggml_log_level) () from /home/culex/github/llama.cpp/build/bin/libllama-common.so.0
#13 0x00007f37a5e75dea in common_params_fit_impl(char const*, llama_model_params*, llama_context_params*, float*, llama_model_tensor_buft_override*, unsigned long*, unsigned int, ggml_log_level) () from /home/culex/github/llama.cpp/build/bin/libllama-common.so.0
#14 0x00007f37a5e7b430 in common_fit_params(char const*, llama_model_params*, llama_context_params*, float*, llama_model_tensor_buft_override*, unsigned long*, unsigned int, ggml_log_level) () from /home/culex/github/llama.cpp/build/bin/libllama-common.so.0
#15 0x00007f37a5e3e325 in common_init_result::common_init_result(common_params&, bool) () from /home/culex/github/llama.cpp/build/bin/libllama-common.so.0
#16 0x00007f37a5e40feb in common_init_from_params(common_params&, bool) () from /home/culex/github/llama.cpp/build/bin/libllama-common.so.0
#17 0x00007f37a6dcf342 in server_context_impl::load_model(common_params&) () from /home/culex/github/llama.cpp/build/bin/libllama-server-impl.so
#18 0x00007f37a6ced8e3 in llama_server(common_params&, int, char**) () from /home/culex/github/llama.cpp/build/bin/libllama-server-impl.so
#19 0x00007f37a72c4c01 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<cli_server::start(common_params&)::{lambda()#1}> > >::_M_run() () from /home/culex/github/llama.cpp/build/bin/libllama-cli-impl.so
#20 0x00007f37a1f05e26 in ?? () from /usr/lib/libstdc++.so.6
#21 0x00007f37a1aaca9f in ?? () from /usr/lib/libc.so.6
#22 0x00007f37a1b4f3dc in ?? () from /usr/lib/libc.so.6

Nemotron was kind enough to get me back up [90659384237c02ee3cbaeb668bfd2a5842ede701](https://github.com/ggml-org/llama.cpp/commit/90659384237c02ee3cbaeb668bfd2a5842ede701)

**Comment by jeffbolznv** [comment]
> https://github.com/ggml-org/llama.cpp/issues/1 0x00007f377c25310a in ?? () from /usr/lib/mangohud/libMangoHud.so

Please try running with this implicit layer disabled.

**Comment by FireCulex** [comment]
> > [#1](https://github.com/ggml-org/llama.cpp/issues/1) 0x00007f377c25310a in ?? () from /usr/lib/mangohud/libMangoHud.so
> 
> Please try running with this implicit layer disabled.

MANGOHUD=0 or adding blacklist = llama-cli,llama-server to MangoHud.conf works as opposed to gating internally_sync_support.

**Comment by jeffbolznv** [comment]
OK, then this sounds like a bug in that layer, it probably doesn't support internally synchronized queues.
