### ISSUE TITLE
Compile bug: Can't compile with opencl 2.0

### ISSUE THREAD

**Issue by johndoanee** [ggml-org/llama.cpp#15368]
### Git commit

git clone https://github.com/ggml-org/llama.cpp.git

### Operating systems

Linux

### GGML backends

OpenCL

### Problem description & steps to reproduce

**Hi,I tried compile llama.cpp for opencl on Debian 13.0.0, AMD R5 5600g using the following code:**
`cmake -B build -DGGML_OPENCL=ON -DGGML_OPENCL_TARGET_VERSION=200`
`cmake --build build --config Release`

**It failed with these informations:**

/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp: In function ‘ggml_backend_opencl_context* ggml_cl2_init(ggml_backend_dev_t)’:
/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp:2234:42: error: ‘CL_DEVICE_NON_UNIFORM_WORK_GROUP_SUPPORT’ was not declared in this scope
 2234 |         CL_CHECK(clGetDeviceInfo(device, CL_DEVICE_NON_UNIFORM_WORK_GROUP_SUPPORT, sizeof(cl_bool),
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp:43:24: note: in definition of macro ‘CL_CHECK’
   43 |         cl_int err_ = (err);                                        \
      |                        ^~~
/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp: In function ‘bool ggml_opencl_supports_op(ggml_backend_dev_t, const ggml_tensor*)’:
/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp:2560:136: note: ‘#pragma message: TODO: implement BF16, Q4_0, Q4_1, Q5_0, Q5_1, Q8_0, IQ4_NL support (https://github.com/ggml-org/llama.cpp/pull/14661)’
 2560 | 5_1, Q8_0, IQ4_NL support (https://github.com/ggml-org/llama.cpp/pull/14661)")
      |                                                                              ^

/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp:2604:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
 2604 |             }
      |             ^
/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp:2605:9: note: here
 2605 |         case GGML_OP_MUL:
      |         ^~~~
gmake[2]: *** [ggml/src/ggml-opencl/CMakeFiles/ggml-opencl.dir/build.make:384：ggml/src/ggml-opencl/CMakeFiles/ggml-opencl.dir/ggml-opencl.cpp.o] error 1
gmake[1]: *** [CMakeFiles/Makefile2:2252：ggml/src/ggml-opencl/CMakeFiles/ggml-opencl.dir/all] error 2
gmake: *** [Makefile:146：all] error 2

**If compile without -DGGML_OPENCL_TARGET_VERSION=200, it can be success.But it can't support my device. The clinfo information is following:**

Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.1 AMD-APP (3625.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback 
  Platform Extensions function suffix             AMD
  Platform Host timer resolution                  1ns

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     gfx90c:xnack-
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 2.0 
  Driver Version                                  3625.0 (HSA1.1,LC)
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     GPU
  Device Board Name (AMD)                         AMD Radeon Graphics
  Device PCI-e ID (AMD)                           0x1638
  Device Topology (AMD)                           PCI-E, 0000:30:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               7
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             1900MHz
  Graphics IP (AMD)                               9.0
  Device Partition                                (core)
    Max number of sub-devices                     7
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size (AMD)                 256
  Max work group size (AMD)                       1024
  Preferred work group size multiple (kernel)     64
  Wavefront width (AMD)                           64
  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (cl_khr_fp16)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              66423103488 (61.86GiB)
  Global free memory (AMD)                        64688920 (61.69GiB) 64688920 (61.69GiB)
  Global memory channels (AMD)                    4
  Global memory banks per channel (AMD)           4
  Global memory bank width (AMD)                  256 bytes
  Error Correction support                        No
  Max memory allocation                           56459637960 (52.58GiB)
  Unified memory for Host and Device              Yes
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   Yes
    Fine-grained system sharing                   No
    Atomics                                       No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Preferred alignment for atomics                 
    SVM                                           0 bytes
    Global                                        0 bytes
    Local                                         0 bytes
  Max size for global variable                    56459637960 (52.58GiB)
  Preferred total size of global vars             66423103488 (61.86GiB)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        16384 (16KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 8192 images
    Base address alignment for 2D image buffers   256 bytes
    Pitch alignment for 2D image buffers          256 pixels
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             16384x16384x8192 pixels
    Max number of read image args                 128
    Max number of write image args                8
    Max number of read/write image args           64
  Max number of pipe args                         16
  Max active pipe reservations                    16
  Max pipe packet size                            625063112 (596.1MiB)
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Local memory size per CU (AMD)                  65536 (64KiB)
  Local memory banks (AMD)                        32
  Max number of constant args                     8
  Max constant buffer size                        56459637960 (52.58GiB)
  Preferred constant buffer size (AMD)            16384 (16KiB)
  Max size of kernel argument                     1024
  Queue properties (on host)                      
    Out-of-order execution                        No
    Profiling                                     Yes
  Queue properties (on device)                    
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Preferred size                                262144 (256KiB)
    Max size                                      8388608 (8MiB)
  Max queues on device                            1
  Max events on device                            1024
  Prefer user sync for interop                    Yes
  Number of P2P devices (AMD)                     0
  Profiling timer resolution                      1ns
  Profiling timer offset since Epoch (AMD)        0ns (Thu Jan  1 08:00:00 1970)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Thread trace supported (AMD)                  No
    Number of async queues (AMD)                  8
    Max real-time compute queues (AMD)            8
    Max real-time compute units (AMD)             7
  printf() buffer size                            4194304 (4MiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_image2d_from_buffer cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [AMD]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   gfx90c:xnack-
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   gfx90c:xnack-
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   gfx90c:xnack-

ICD loader properties
  ICD loader Name                                 Khronos OpenCL ICD Loader
  ICD loader Vendor                               Khronos Group
  ICD loader Version                              3.0.6
  ICD loader Profile                              OpenCL 3.0

### Compile command

```shell
cmake -B build -DGGML_OPENCL=ON -DGGML_OPENCL_TARGET_VERSION=200
cmake --build build --config Release
```

### Relevant log output

```shell
/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp: In function ‘ggml_backend_opencl_context* ggml_cl2_init(ggml_backend_dev_t)’:
/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp:2234:42: error: ‘CL_DEVICE_NON_UNIFORM_WORK_GROUP_SUPPORT’ was not declared in this scope
 2234 |         CL_CHECK(clGetDeviceInfo(device, CL_DEVICE_NON_UNIFORM_WORK_GROUP_SUPPORT, sizeof(cl_bool),
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp:43:24: note: in definition of macro ‘CL_CHECK’
   43 |         cl_int err_ = (err);                                        \
      |                        ^~~
/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp: In function ‘bool ggml_opencl_supports_op(ggml_backend_dev_t, const ggml_tensor*)’:
/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp:2560:136: note: ‘#pragma message: TODO: implement BF16, Q4_0, Q4_1, Q5_0, Q5_1, Q8_0, IQ4_NL support (https://github.com/ggml-org/llama.cpp/pull/14661)’
 2560 | 5_1, Q8_0, IQ4_NL support (https://github.com/ggml-org/llama.cpp/pull/14661)")
      |                                                                              ^

/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp:2604:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
 2604 |             }
      |             ^
/root/llama.cpp/ggml/src/ggml-opencl/ggml-opencl.cpp:2605:9: note: here
 2605 |         case GGML_OP_MUL:
      |         ^~~~
gmake[2]: *** [ggml/src/ggml-opencl/CMakeFiles/ggml-opencl.dir/build.make:384：ggml/src/ggml-opencl/CMakeFiles/ggml-opencl.dir/ggml-opencl.cpp.o] error 1
gmake[1]: *** [CMakeFiles/Makefile2:2252：ggml/src/ggml-opencl/CMakeFiles/ggml-opencl.dir/all] error 2
gmake: *** [Makefile:146：all] error 2
```

**Comment by baonudesifeizhai** [comment]
same on my side , i will try to fix it

**Comment by baonudesifeizhai** [comment]
<img width="836" height="454" alt="Image" src="https://github.com/user-attachments/assets/23600d7a-e68b-434a-b631-d9f4c3d61afa" />
