### ISSUE TITLE
Compile bug: common.cuh(3): fatal error c1083 cannot open include file: "ggml.h" : No such file or directory

### ISSUE THREAD

**Issue by seandennis** [ggml-org/llama.cpp#13073]
### Git commit

llama.cpp\ggml\src\ggml-cuda\common.cuh(3): fatal error C1083: Cannot open include file: 'ggml.h': No such file
 or directory

I have tried may ways to build this. I tried with CUDA 11.7, now CUDA 12.8. I'm a novice and I am building with Develper Command Prompt for VS 2022

This is my prompt cmake -B build -DGGML_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES="86" -DGGML_CCACHE=OFF -DLLAMA_CURL=OFF

it is when it gets to cmake --build build --config Release .

I have tried many ways including using Gemini 2,5 Pro. it suggested this

cmake .. -G "Visual Studio 17 2022" -A x64 -DGGML_CUDA=ON -DLLAMA_BUILD_EXAMPLES=ON -DLLAMA_BUILD_SERVER=ON -DLLAMA_CURL=OFF 

but got the same issue

Gemini even suggest to paste this onto line 54 of the ggml-cude folder and CmakeList.txt file with this

target_include_directories(ggml-cuda PRIVATE ../include ../src)

as I said I am not a programmer, just getting Gemini to teach me some stuff. But it gave the same error everytime.

### Operating systems

Windows

### GGML backends

CUDA

### Problem description & steps to reproduce

I have tried may ways to build this. I tried with CUDA 11.7, now CUDA 12.8. I'm a novice and I am building with Develper Command Prompt for VS 2022

This is my prompt cmake -B build -DGGML_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES="86" -DGGML_CCACHE=OFF -DLLAMA_CURL=OFF

it is when it gets to cmake --build build --config Release .

### First Bad Commit

I had no issues with the CPU build

### Compile command

```shell
cmake -B build -DGGML_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES="86" -DGGML_CCACHE=OFF -DLLAMA_CURL=OFF

and

cmake --build build --config Release
```

### Relevant log output

```shell
U:\AI's\llama.cpp\ggml\src\ggml-cuda\common.cuh(3): fatal error C1083: Cannot open include file: 'ggml.h': No such file
 or directory [U:\AI's\llama.cpp\build\ggml\src\ggml-cuda\ggml-cuda.vcxproj]
  fattn-vec-f16-instance-hs64-f16-f16.cu
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 12.8.targets
(800,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8\bin\nvcc.exe"  --use-loc
al-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64" -x cu
   -I"U:\AI's\llama.cpp\ggml\src\ggml-cuda\.." -I"U:\AI's\llama.cpp\ggml\src\..\include" -I"C:\Program Files\NVIDIA GPU
 Computing Toolkit\CUDA\v12.8\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8\include"     --keep-
dir ggml-cuda\x64\Release -use_fast_math -maxrregcount=0    --machine 64 --compile -cudart static -std=c++17 --generate
-code=arch=compute_86,code=[compute_86,sm_86] -compress-mode=size -Xcompiler="/EHsc -Ob2"   -D_WINDOWS -DNDEBUG -DGGML_
BACKEND_BUILD -DGGML_BACKEND_SHARED -D_CRT_SECURE_NO_WARNINGS -DGGML_SCHED_MAX_COPIES=4 -D_XOPEN_SOURCE=600 -DGGML_CUDA
_PEER_MAX_BATCH_SIZE=128 -DGGML_CUDA_USE_GRAPHS -DGGML_SHARED -D"CMAKE_INTDIR=\"Release\"" -Dggml_cuda_EXPORTS -D_WINDL
L -D_MBCS -D"CMAKE_INTDIR=\"Release\"" -Dggml_cuda_EXPORTS -Xcompiler "/EHsc /W1 /nologo /O2 /FS   /MD /GR" -Xcompiler
"/Fdggml-cuda.dir\Release\vc143.pdb" -o ggml-cuda.dir\Release\fattn-vec-f16-instance-hs64-f16-f16.obj "U:\AI's\llama.cp
p\ggml\src\ggml-cuda\template-instances\fattn-vec-f16-instance-hs64-f16-f16.cu"" exited with code 2. [U:\AI's\llama.cpp
\build\ggml\src\ggml-cuda\ggml-cuda.vcxproj]
  Compiling CUDA source file ..\..\..\..\ggml\src\ggml-cuda\template-instances\fattn-vec-f32-instance-hs128-f16-f16.cu.
  ..
```

**Comment by seandennis** [comment]
Ok I found the issue. Gemini 2.5 pro found the issue in less then 150,000 tokens.

it was in my folder name that was the issue. I have a folder called AI's. The problem was the " ' " in the name.
