### PR TITLE
Fix KleidiAI compilation errors with -DGGML_NATIVE=OFF (issue #14464)

### LINKED ISSUE #14464: Compile bug:
### Git commit

a7417f55945eb7c7a5ea6807e66564b8066a4e50

### Operating systems

Linux

### GGML backends

CPU

### Problem description & steps to reproduce

I'm trying to create a portable arm64 build, which includes KleidiAI to have optimizations which are selected during runtime. 

To make the binary portable to all arm64 CPUs, I use the `-DGGML_NATIVE=OFF` flag. To enable arm64 support I add `-DGGML_CPU_AARCH64=ON`, followed by `-DGGML_CPU_KLEIDIAI=ON` to enable KleidiAI. The build fails with this combination with the log added below.

When I remove `-DGGML_NATIVE=OFF`, the build succeeds. But my understanding is that it builds for the host CPU's features, so the resulting binary is not portable. Please correct me if my understanding is wrong.

Is there a recommended way to build `llama.cpp` for arm64, being portable to different versions of the CPU, while still getting the best optimization available using KleidiAI?

### First Bad Commit

_No response_

### Compile command

```shell
cmake -B build -DGGML_NATIVE=OFF -DGGML_CPU_AARCH64=ON -DGGML_CPU_KLEIDIAI=ON -DLLAMA_CURL=OFF
```

### Relevant log output

```shell
$ rm -rf build

$ cmake -B build -DGGML_NATIVE=OFF -DGGML_CPU_AARCH64=ON -DGGML_CPU_KLEIDIAI=ON -DLLAMA_CURL=OFF
-- The C compiler identification is GNU 13.3.0
-- The CXX compiler identification is GNU 13.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.43.0") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: aarch64
-- GGML_SYSTEM_ARCH: ARM
-- Including CPU backend
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- ARM detected
-- Performing Test GGML_COMPILER_SUPPORTS_FP16_FORMAT_I3E
-- Performing Test GGML_COMPILER_SUPPORTS_FP16_FORMAT_I3E - Failed
-- ARM feature FMA enabled
-- Using KleidiAI optimized kernels if applicable
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Adding CPU backend variant ggml-cpu:  
-- Configuring done (3.5s)
-- Generating done (0.2s)
-- Build files have been written to: /home/ubuntu/llama.cpp/build

$ cmake --build build --config Release
[  0%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml.c.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml.cpp.o
[  1%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-alloc.c.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-backend.cpp.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-opt.cpp.o
[  3%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-threading.cpp.o
[  3%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-quants.c.o
[  3%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o
[  3%] Linking CXX shared library ../../bin/libggml-base.so
[  3%] Built target ggml-base
[  4%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ggml-cpu.c.o
[  4%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ggml-cpu.cpp.o
[  4%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/repack.cpp.o
[  4%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/hbm.cpp.o
[  6%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/quants.c.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/traits.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/amx/amx.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/amx/mmq.cpp.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/binary-ops.cpp.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/unary-ops.cpp.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/vec.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ops.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/llamafile/sgemm.cpp.o
[  9%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/arch/arm/quants.c.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/arch/arm/repack.cpp.o
[ 10%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/kleidiai/kleidiai.cpp.o
[ 10%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/kleidiai/kernels.cpp.o
/home/ubuntu/llama.cpp/ggml/src/ggml-cpu/kleidiai/kernels.cpp:28:30: error: zero-size array ‘gemm_gemv_kernels’
   28 | static ggml_kleidiai_kernels gemm_gemv_kernels[] = {
      |                              ^~~~~~~~~~~~~~~~~
gmake[2]: *** [ggml/src/CMakeFiles/ggml-cpu.dir/build.make:300: ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/kleidiai/kernels.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1752: ggml/src/CMakeFiles/ggml-cpu.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

### PR DESCRIPTION
**Pull request by baonudesifeizhai**
This commit fixes compilation errors that occur when building with -DGGML_NATIVE=OFF, which resulted in zero-size arrays in KleidiAI code.

Changes made:

1. kernels.cpp:
   - Add conditional compilation around gemm_gemv_kernels array
   - Provide fallback empty array when no ARM features available
   - Guard kernel selection functions with feature checks

2. kleidiai.cpp:
   - Replace GGML_ASSERT(kernels) with null pointer checks
   - Return appropriate error codes when no kernels available
   - Prevent crashes when KleidiAI is unavailable

3. CMakeLists.txt:
   - Add architecture check to only enable KleidiAI on ARM systems
   - Fix KleidiAI download URL (GitHub -> GitLab)
   - Use git clone instead of archive download for reliability

Fixes: https://github.com/ggml-org/llama.cpp/issues/14464
Tested: Successfully compiles with -DGGML_NATIVE=OFF on x86_64

*Make sure to read the [contributing guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md) before submitting a PR*

### CODE REVIEW

File: ggml/src/ggml-cpu/CMakeLists.txt [hunk 1]
```diff
@@ -495,17 +495,17 @@ function(ggml_add_cpu_backend_variant_impl tag_name)
...
             cmake_policy(SET CMP0135 NEW)
         endif()
 
         FetchContent_Declare(KleidiAI_Download
-            URL ${KLEIDIAI_DOWNLOAD_URL}
-            DOWNLOAD_EXTRACT_TIMESTAMP NEW
-            URL_HASH MD5=${KLEIDIAI_ARCHIVE_MD5})
+            GIT_REPOSITORY https://git.gitlab.arm.com/kleidi/kleidiai.git
+            GIT_TAG ${KLEIDIAI_COMMIT_TAG}
+            GIT_SHALLOW TRUE)
```
Comment (chaxu01) [inline ggml/src/ggml-cpu/CMakeLists.txt]: Since KleidiAI v2.x is expected to introduce some API changes, it's safer to continue using the static tarball from GitHub for now. This ensures compatibility with the current integration and avoids unexpected breakages.

File: ggml/src/ggml-cpu/kleidiai/kleidiai.cpp [hunk 2]
```diff
@@ -344,7 +350,9 @@ class tensor_traits : public ggml::cpu::tensor_traits {
 
 public:
     int repack(struct ggml_tensor * tensor, const void * data, size_t data_size) {
-        GGML_ASSERT(ctx.kernels);
+        if (!ctx.kernels) {
+            return -1;  // No suitable kernel available
+        }
```
Comment (chaxu01) [inline ggml/src/ggml-cpu/kleidiai/kleidiai.cpp]: Replacing GGML_ASSERT(ctx.kernels) with a return value silently fails if no kernel is available, but there's no fallback.

Comment (chaxu01) [reply ggml/src/ggml-cpu/kleidiai/kleidiai.cpp]: Consider keeping the GGML_ASSERT(ctx.kernels) to catch misconfigurations early, or at least add a GGML_LOG_DEBUG message to warn when no suitable kernel is available.

**Review by chaxu01 — CHANGES_REQUESTED** [review]

**Review by chaxu01 — APPROVED** [review]

File: ggml/src/ggml-cpu/kleidiai/kleidiai.cpp [hunk 3]
```diff
@@ -276,7 +284,11 @@ class tensor_traits : public ggml::cpu::tensor_traits {
         GGML_TENSOR_BINARY_OP_LOCALS
 
         ggml_kleidiai_kernels *kernels = ggml_kleidiai_select_kernels(ctx.features, dst);
-        GGML_ASSERT(kernels);
+        if (!kernels) {
+            // No suitable KleidiAI kernel available, fallback to standard CPU implementation
+            GGML_LOG_DEBUG("%s: No suitable KleidiAI kernel available for Q4_0 operation, falling back to standard CPU implementation\n", __func__);
+            return false;  // Let the system fallback to standard CPU implementation
+        }
```
Comment (ggerganov) [inline ggml/src/ggml-cpu/kleidiai/kleidiai.cpp]: In the compute calls, it's better to keep the `GGML_ASSERT`s. These would never get called if `repack()` has already bailed.

File: ggml/src/ggml-cpu/kleidiai/kleidiai.cpp (hunk 2 above)
Comment (ggerganov) [reply ggml/src/ggml-cpu/kleidiai/kleidiai.cpp]: I don't understand the change - if `repack()` returns -1, we will immediately assert on line 405:

```c++
    auto OK            = tensor_traits->repack(tensor, data, size);

    GGML_ASSERT(OK == 0);
```

**Comment by CISC** [comment]
@baonudesifeizhai It looks like this PR is ready, but needs rebasing?

**Comment by baonudesifeizhai** [comment]
> @baonudesifeizhai It looks like this PR is ready, but needs rebasing?

already rebase .... there comes so many changes ...

**Comment by CISC** [comment]
> > @baonudesifeizhai It looks like this PR is ready, but needs rebasing?
> 
> already rebase .... there comes so many changes ...

Such is the life in the fast lane. :)

You seem to have made a bad merge though.

**Comment by BradHutchings** [comment]
I ran into this problem this week. Is there any chance this fix can be updated and merged?
