### ISSUE TITLE
Compile bug: Sudden loss of the ability to compile llama.cpp (Ubuntu 24.04)

### ISSUE THREAD

**Issue by compilebunny** [ggml-org/llama.cpp#15257]
### Git commit

$ git rev-parse HEAD
be48528b068111304e4a0bb82c028558b5705f05

What could have changed?

### Operating systems

Linux

### GGML backends

CUDA

### Problem description & steps to reproduce

I have been compiling llama.cpp weekly using the same system for a few months now. I've suddenly started getting the following errors regarding "__builtin_dynamic_object_size"

$ gcc --version 
gcc (Ubuntu 11.4.0-9ubuntu1) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0

$ g++ --version
g++ (Ubuntu 11.4.0-9ubuntu1) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### First Bad Commit

Unknown

### Compile command

```shell
cmake -B build -DGGML_CUDA=ON -DGGML_CCACHE=OFF -DGGML_CUDA_FA_ALL_QUANTS=ON -DLLAMA_CURL=OFF -DCMAKE_CUDA_ARCHITECTURES="90"

cmake --build build --config Release -j 10
```

### Relevant log output

```shell
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/traits.cpp.o
/usr/include/x86_64-linux-gnu/bits/stdlib.h(39): error: identifier "__builtin_dynamic_object_size" is undefined
```

**Comment by dagbs** [comment]
Have you tried to go back and re-compile an old version to see if it's a commit issue or a library issue?

**Comment by JohannesGaessler** [comment]
I don't understand why the linked commit in particular would be causing issues. Just to be clear: does the commit immediately before still work and the linked commit does not?

**Comment by compilebunny** [comment]
I checked the previous commit and the one before -- neither of them will compile either.

Ages ago, I downgraded to gcc-11 because something in llama.cpp wasn't compatible with gcc-12.

Has the recommended toolchain for llama.cpp changed? It certainly isn't in the build documentation.

**Comment by JohannesGaessler** [comment]
Try removing and recreating the build directory. Try compiling with `GGML_CCACHE=OFF`. If both of those don't work, try whether an old commit still works and do a git bisect to identify the exact commit that introduced the issue.
