### PR TITLE
ggml-cpu: gate __fp16 on __ARM_FP16_FORMAT_IEEE

### LINKED ISSUE #26677: llama.cpp fails to compile in ../ggml/src/ggml-cpu/simd-mappings.h with: 45:9: error: unknown type name '__fp16'
### Git commit

I'm on 74ade52741203e5c8f81eaf06a96cb1cfe15f2a3

### Operating systems

Linux

### GGML backends

CPU

### Problem description & steps to reproduce

hi, I want to compile firefox-nightly on linux and it fails very early with an error from third_party/llama.cpp 

```
 .deps/gmp-fake-openh264.o.pp  -fdiagnostics-color  /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/dom/media/gmp-plugin-openh264/gmp-fake-openh264.cpp
 0:52.09 E /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:45:9: error: unknown type name '__fp16'; did you mean '__bf16'?
 0:52.09 E    45 |         __fp16 tmp;
 0:52.10 E       |         ^~~~~~
 0:52.10 E       |         __bf16
 0:52.10 E /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:52:9: error: unknown type name '__fp16'; did you mean '__bf16'?
 0:52.10 E    52 |         __fp16 tmp = f;
 0:52.11 E       |         ^~~~~~
 0:52.11 E       |         __bf16
```

this is a neon build for armv7a, using gcc

non-neon works with gcc

### First Bad Commit

I will fill this out later, once I've found a standalone build script for llama.cpp

### Compile command

```shell
I believe this is all: 

 
 0:50.94 gmake[4]: Entering directory '/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/third_party/llama.cpp'
 0:50.98 third_party/llama.cpp/ggml-alloc.o
 0:50.99 third_party/llama.cpp/ggml-c.o
 0:51.01 /usr/bin/armv7a-unknown-linux-gnueabihf-gcc --sysroot /usr/armv7a-unknown-linux-gnueabihf -o ggml-alloc.o -c  -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/system_wrappers -include /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/config/gcc_hidden.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstrict-flex-arrays=1 -DNDEBUG=1 -DTRIMMED=1 -D_GNU_SOURCE=1 -DGGML_USE_CPU=1 '-DGGML_VERSION="GGML_VERSION"' '-DGGML_COMMIT="GGML_COMMIT"' -DGGML_SHARED=1 -DLLAMA_SHARED=1 -DGGML_BUILD=1 -DLLAMA_BUILD=1 -DGGML_BACKEND_SHARED=1 -DGGML_BACKEND_BUILD=1 -DMOZ_HAS_MOZGLUE -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/third_party/llama.cpp -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/include -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/include -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/src -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/include -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nspr -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nss -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nspr -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/include/nss -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/libpng16 -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/pixman-1 -DMOZILLA_CLIENT -include /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/mozilla-config.h -mthumb -mfpu=neon -mfloat-abi=hard -mno-thumb-interwork -pthread -ffunction-sections -fdata-sections -fno-math-errno -pipe -fPIC -pipe -fomit-frame-pointer -O2 -fno-omit-frame-pointer -funwind-tables -Wall -Wempty-body -Wignored-qualifiers -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Winvalid-utf8 -Wduplicated-cond -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=free-nonheap-object -Wno-multistatement-macros -Wno-error=class-memaccess -Wformat -Wformat-security -Wformat-overflow=2 -Werror=implicit-function-declaration -Wno-psabi -Wno-error=builtin-macro-redefined -Wno-sign-compare -Wno-unused-function -Wno-unreachable-code -Wno-tautological-unsigned-enum-zero-compare -fno-strict-aliasing -ffp-contract=off  -MD -MP -MF .deps/ggml-alloc.o.pp  -fdiagnostics-color  /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-alloc.c
 0:51.64 /usr/bin/armv7a-unknown-linux-gnueabihf-gcc --sysroot /usr/armv7a-unknown-linux-gnueabihf -o ggml-c.o -c  -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/system_wrappers -include /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/config/gcc_hidden.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstrict-flex-arrays=1 -DNDEBUG=1 -DTRIMMED=1 -D_GNU_SOURCE=1 -DGGML_USE_CPU=1 '-DGGML_VERSION="GGML_VERSION"' '-DGGML_COMMIT="GGML_COMMIT"' -DGGML_SHARED=1 -DLLAMA_SHARED=1 -DGGML_BUILD=1 -DLLAMA_BUILD=1 -DGGML_BACKEND_SHARED=1 -DGGML_BACKEND_BUILD=1 -DMOZ_HAS_MOZGLUE -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/third_party/llama.cpp -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/include -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/include -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/src -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/include -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nspr -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nss -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nspr -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/include/nss -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/libpng16 -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/pixman-1 -DMOZILLA_CLIENT -include /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/mozilla-config.h -mthumb -mfpu=neon -mfloat-abi=hard -mno-thumb-interwork -pthread -ffunction-sections -fdata-sections -fno-math-errno -pipe -fPIC -pipe -fomit-frame-pointer -O2 -fno-omit-frame-pointer -funwind-tables -Wall -Wempty-body -Wignored-qualifiers -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Winvalid-utf8 -Wduplicated-cond -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=free-nonheap-object -Wno-multistatement-macros -Wno-error=class-memaccess -Wformat -Wformat-security -Wformat-overflow=2 -Werror=implicit-function-declaration -Wno-psabi -Wno-error=builtin-macro-redefined -Wno-sign-compare -Wno-unused-function -Wno-unreachable-code -Wno-tautological-unsigned-enum-zero-compare -fno-strict-aliasing -ffp-contract=off  -MD -MP -MF .deps/ggml-c.o.pp  -fdiagnostics-color  /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-c.c
 0:51.64 third_party/llama.cpp/quants-arm.o
 0:51.77 third_party/llama.cpp/ggml-cpu-c.o
 0:51.83 /usr/bin/armv7a-unknown-linux-gnueabihf-gcc --sysroot /usr/armv7a-unknown-linux-gnueabihf -o quants-arm.o -c  -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/system_wrappers -include /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/config/gcc_hidden.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstrict-flex-arrays=1 -DNDEBUG=1 -DTRIMMED=1 -D_GNU_SOURCE=1 -DGGML_USE_CPU=1 '-DGGML_VERSION="GGML_VERSION"' '-DGGML_COMMIT="GGML_COMMIT"' -DGGML_SHARED=1 -DLLAMA_SHARED=1 -DGGML_BUILD=1 -DLLAMA_BUILD=1 -DGGML_BACKEND_SHARED=1 -DGGML_BACKEND_BUILD=1 -DMOZ_HAS_MOZGLUE -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/third_party/llama.cpp -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/include -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/include -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/src -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/include -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nspr -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nss -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/nspr -I/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/dist/include/nss -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/libpng16 -I/usr/armv7a-unknown-linux-gnueabihf/usr/include/pixman-1 -DMOZILLA_CLIENT -include /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/mozilla-config.h -mthumb -mfpu=neon -mfloat-abi=hard -mno-thumb-interwork -pthread -ffunction-sections -fdata-sections -fno-math-errno -pipe -fPIC -pipe -fomit-frame-pointer -O2 -fno-omit-frame-pointer -funwind-tables -Wall -Wempty-body -Wignored-qualifiers -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Winvalid-utf8 -Wduplicated-cond -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=free-nonheap-object -Wno-multistatement-macros -Wno-error=class-memaccess -Wformat -Wformat-security -Wformat-overflow=2 -Werror=implicit-function-declaration -Wno-psabi -Wno-error=builtin-macro-redefined -Wno-sign-compare -Wno-unused-function -Wno-unreachable-code -Wno-tautological-unsigned-enum-zero-compare -fno-strict-aliasing -ffp-contract=off  -MD -MP -MF .deps/quants-arm.o.pp  -fdiagnostics-color  /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu/arch/arm/quants-arm.c
 0:52.09 E /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:45:9: error: unknown type name '__fp16'; did you mean '__bf16'?
 0:52.10 E /home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/third_party/llama.cpp/ggml/src/ggml-cpu/simd-mappings.h:52:9: error: unknown type name '__fp16'; did you mean '__bf16'?
 0:55.40 gmake[4]: Leaving directory '/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox_build/third_party/llama.cpp'
 0:55.41 E gmake[3]: *** [/home/tmp/portage/portage/www-client/firefox-155.0/work/firefox-155.0/config/recurse.mk:79: third_party/llama.cpp/target-objects] Error 2
```

### Relevant log output

```shell
I will attach the full build log later.
```

### PR DESCRIPTION
**Pull request by ServeurpersoCom**
## Overview

Building for 32 bit Arm with NEON and GCC fails with "unknown type name '__fp16'".

The NEON block is selected on __ARM_NEON alone, but that only means NEON is available. The __fp16 type also needs the IEEE half format, free on AArch64 but requested with -mfp16-format=ieee on 32 bit Arm, and refused otherwise.

Adding __ARM_FP16_FORMAT_IEEE to the condition sends that one configuration to the generic lookup path and leaves every other toolchain on the same code.

Tested by @stefson on native Arm, GCC and Clang, with and without NEON.

## Additional information

Fixes #26677

## Requirements

- I have read and agree with the [contributing guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md)
- AI usage disclosure: YES

### CODE REVIEW

**Review by taronaeo — APPROVED** [review]

**Comment by taronaeo** [comment]
@JonathanC-ARM Any chance could you take a look at this? :)

File: ggml/src/ggml-cpu/simd-mappings.h
Comment (JonathanC-ARM) [inline ggml/src/ggml-cpu/simd-mappings.h]: Could you add && defined(__ARM_FP16_FORMAT_IEEE) here also, essentially if you use NEON + FMA the same type of unknown type error can occur.

**Comment by JonathanC-ARM** [comment]
Code looks good, I tested before/after the patch and it fixes the issue as described. 

I did the following:
```
CC=/home/jonclo01/pkg/gcc-arm-none-eabi-x86_64/bin/arm-none-eabi-gcc
$CC -std=c11 -march=armv7-a -mfpu=neon -mfloat-abi=hard \
    -Iggml/include -Iggml/src -Iggml/src/ggml-cpu \
    -Iggml/src/ggml-cpu/arch/arm \
    -fsyntax-only ggml/src/ggml-cpu/arch/arm/quants.c
```

Seen the two errors described. I then applied the patch, issue went away.

I noticed that further down the file there's a similar guard with neon and fma.

```
  $CC -std=c11 -march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard \
    -Iggml/include -Iggml/src -Iggml/src/ggml-cpu \
    -include ggml/src/ggml-cpu/vec.h \
    -fsyntax-only -x c /dev/null
```

This uncovers a similar issue, and if you apply the change as suggested this also fixes that.

File: ggml/src/ggml-cpu/simd-mappings.h
Comment (ServeurpersoCom) [reply ggml/src/ggml-cpu/simd-mappings.h]: Good catch, the F16 macros in that block dereference __fp16 on both paths so neon-vfpv4 trips the same way, guard added there too. Thanks for testing both configurations

**Review by JonathanC-ARM — APPROVED** [review]
Looks good to me @ServeurpersoCom

**Comment by ServeurpersoCom** [comment]
Please need 2nd approval @ggml-org/maintainers :D

**Review by taronaeo — APPROVED** [review]

**Comment by ServeurpersoCom** [comment]
2nd approval is missing from someone with write access:)

**Review by pwilkin — APPROVED** [review]

**Comment by ServeurpersoCom** [comment]
Thanks
