### ISSUE TITLE
Compile bug: BUILD_TOOLS now requires BUILD_SERVER

### ISSUE THREAD

**Issue by 65a** [ggml-org/llama.cpp#18046]
### Git commit

HEAD

### Operating systems

Linux

### GGML backends

HIP

### Problem description & steps to reproduce

Try to compile llama.cpp as a CMake dependency with BUILD_TOOLS on (for MTMD) and BUILD_SERVER off.

### First Bad Commit

6c2131773c5975c719863a21a8195a66dea4a4d0

### Compile command

```shell
n/a
```

### Relevant log output

```shell
server-common.h:7:10: fatal error: 'mtmd.h' file not found
    7 | #include "mtmd.h"
      |          ^~~~~~~~
[ 96%] Linking CXX executable ../../bin/llama-gguf-split
[ 96%] Linking CXX executable ../../bin/llama-batched-bench
1 error generated.
make[2]: *** [tools/cli/CMakeFiles/llama-cli.dir/build.make:76: tools/cli/CMakeFiles/llama-cli.dir/cli.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:843: tools/cli/CMakeFiles/llama-cli.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by 65a** [comment]
Fixing the mtmd.h header (as I tried in #18045 ) then leads to issues with `-lserver-context` and so on. Re-enabling BUILD_SERVER resolves the issue.
